dateModified: 1714449503
elementSources:
  craft\elements\Entry:
    -
      heading: 'Primary Content'
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:b1ee8bc9-827b-4fec-943c-c6ff229adb59' # Articles
      tableAttributes:
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:247cf34e-12cf-4324-b034-3209f48a18ff' # Page Content
      tableAttributes:
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: 'Secondary Content'
      type: heading
    -
      key: 'section:4688dcb4-257f-4a94-b8b7-db234f63e0a9' # Landing Pages
      type: native
    -
      heading: 'Meta Content'
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:667ee826-8732-4bc8-8dbe-b7aefad82b15' # Collections
      tableAttributes:
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:685e625d-7180-40dc-a031-953f5f9a8cef' # Reusable Pieces
      tableAttributes:
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:83a6e4e2-3e52-435e-bcb4-ced4dc7e387e' # Taxonomies
      tableAttributes:
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: true
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - link
      type: native
email:
  fromEmail: craft@example.com
  fromName: 'Craft CMS'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0c3eb4bf-9fe7-422e-9947-289edfc00105: Redirect # Redirect
    1eb561c2-313a-4ea5-9332-dd8effd8eb73: Bit # Bit
    1fc4d14e-bdf2-4cfa-a95c-64f6dac73d40: Collections # Collections
    4b2a900b-f8d6-4b24-aee5-10ebc4051eb6: 'RSS Feed' # RSS Feed
    4b104ed0-4b08-424b-a744-f9bbf418fc2f: Images # Images
    06d15756-5b0e-4a06-a8db-0f2343d4b25f: Fragment # Fragment
    8b83b1c6-3917-4365-bc67-1f94599cbb08: Private # Private
    14dff90f-f8fc-444e-bc75-e51f72aa490d: Text # Text
    31cc93a2-d38f-4943-b7c2-473b72eb69a1: Variant # Variant
    80b8014d-fa4b-4271-9c59-73cd7c7c6d78: Article # Article
    83a6e4e2-3e52-435e-bcb4-ced4dc7e387e: Taxonomies # Taxonomies
    93a86902-7a1b-4986-ba7f-35cef71233ac: 'Craft CMS' # Craft CMS
    99d1e742-e9ee-4468-8f52-06f9672d8f68: Fullpage # Fullpage
    247cf34e-12cf-4324-b034-3209f48a18ff: 'Page Content' # Page Content
    581b9070-f50c-49a0-91c7-2921437ad0fb: Color # Color
    667ee826-8732-4bc8-8dbe-b7aefad82b15: Collections # Collections
    685e625d-7180-40dc-a031-953f5f9a8cef: 'Reusable Pieces' # Reusable Pieces
    4248eeb1-ca4d-476f-9998-7780ee611c74: Image # Image
    4688dcb4-257f-4a94-b8b7-db234f63e0a9: 'Landing Pages' # Landing Pages
    7487ca3f-f51b-40e9-a538-40ab5b2c4a27: Text # Text
    96192f21-960f-489c-a380-96e4b51f2777: 'Card Deck' # Card Deck
    2508516d-3329-44ec-8518-04f2a29ca3f3: 'External Media' # External Media
    21710874-0ba0-423c-82ec-7fd855abb982: 'Dynamic Collection' # Dynamic Collection
    a28f735a-3f02-4039-aaf6-a9c50e93122f: Sidebar # Sidebar
    ab7d33f0-3a17-47ea-a6a8-ad94734ee9a2: Bits # Bits
    b1ee8bc9-827b-4fec-943c-c6ff229adb59: Articles # Articles
    b54aca1f-5631-4f76-a248-e953c4ada5bd: Icon # Icon
    b4753be4-da84-4306-82e8-a9473ca5398f: 'Body Builder' # Body Builder
    b4783a60-e9ff-40a2-8e9e-159b24fad0a9: Media # Media
    bb561dd8-e748-4c68-9107-2ffd5db410d8: Topic # Topic
    d8bf6768-4ff5-4727-ac20-12f8f0344542: Media # Media
    d34bee8e-bf22-451d-8339-a4342630833d: 'Craft CMS' # Craft CMS
    d554a8e7-e8ad-493b-aaa8-d611bf04b257: 'Website / Content URL' # Website / Content URL
    d7748b2a-ae79-4961-b103-a5aa758e39ab: 'Static Collection' # Static Collection
    e56447b6-2288-47ba-89a8-e90f3970f3c7: 'Sidebar Fragment' # Sidebar Fragment
    ef0d77ed-a6ab-49db-afe4-2be38730d402: Simple # Simple
    f3d34d10-7741-40ba-9fae-27d87f771b4d: Summary # Summary
    f240ce26-8d9d-4668-b18b-73371d5c5211: Entries # Entries
    faaa512e-f0ed-4151-97de-d73bdc9a4f5e: Component # Component
    ff76eb70-820e-4752-b138-daef62692e3f: 'Body Fragment' # Body Fragment
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  empty-coalesce:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: UOS5WIL2BA65FWV43LPHM9NT
    schemaVersion: 2.1.0
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  selectplus:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 8F7J3RTMNWCHFZDNV5PYH126
    schemaVersion: 3.0.12
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Craft CMS'
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
