headingLevels:
  - 2
  - 3
  - 4
name: 'Simple Text'
options:
  alignment:
    options:
      - left
      - center
      - right
      - justify
  highlight:
    options:
      -
        class: marker-green
        color: var(--ck-highlight-marker-green)
        model: greenMarker
        title: 'Green marker'
        type: marker
      -
        class: pen-red
        color: var(--ck-highlight-pen-red)
        model: redPen
        title: 'Red pen'
        type: pen
  style:
    definitions:
      -
        classes:
          - knockout
        element: h3
        name: 'Knockout (H3)'
      -
        classes:
          - marker
        element: span
        name: Marker
toolbar:
  - heading
  - alignment
  - '|'
  - link
  - bold
  - italic
  - style
  - '|'
  - bulletedList
  - numberedList
  - todoList
