headingLevels:
  - 1
js: "return {\r\n  highlight: {\r\n    options: [\r\n      {\r\n        class: 'marker-green',\r\n        color: 'var(--ck-highlight-marker-green)',\r\n        model: 'greenMarker',\r\n        title: 'Green marker',\r\n        type: 'marker',\r\n      },\r\n      {\r\n        class: 'pen-red',\r\n        color: 'var(--ck-highlight-pen-red)',\r\n        model: 'redPen',\r\n        title: 'Red pen',\r\n        type: 'pen',\r\n      },\r\n    ],\r\n  },\r\n  toolbar: [\r\n    'heading',\r\n    '|',\r\n    'bulletedList',\r\n    'numberedList',\r\n    'highlight',\r\n    'undo',\r\n    'redo',\r\n  ],\r\n}"
name: Headline
toolbar:
  - heading
  - '|'
  - bold
  - italic
