defaultPlacement: end
fieldLayouts:
  903c6c72-8980-4588-b988-dbe4b012acfc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 5e779e41-2ef6-45b9-ab4b-e61688db3e27
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: 3ad1ef73-2207-440e-897a-c7d434109a6b
            userCondition: null
            warning: null
          -
            attribute: newWindow
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: 4cbfbb9e-8bba-4f1f-83ad-281560015454
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: f52f9a51-b662-4f9e-9c8a-b93ea966007a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\UrlSuffixField
            uid: 962f15ec-f2a2-48bd-b8a7-4baacf539871
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\ClassesField
            uid: 470fece8-20b2-4558-bc50-11230895d8b6
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\CustomAttributesField
            uid: 8a87be4d-bd76-444e-950b-3db98c5ae645
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: a43db574-bac8-4920-8b23-5475617a4cb2
        userCondition: null
handle: account
instructions: ''
maxNodes: null
name: Account
permissions:
  craft\commerce\elements\Product:
    enabled: ''
    permissions: '*'
  craft\elements\Asset:
    enabled: ''
    permissions: '*'
  craft\elements\Category:
    enabled: ''
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions:
      - 'section:247cf34e-12cf-4324-b034-3209f48a18ff' # Core Pages
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  putyourlightson\campaign\elements\CampaignElement:
    enabled: ''
    permissions: '*'
  verbb\events\elements\Event:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
  verbb\navigation\nodetypes\SiteType:
    enabled: ''
propagationMethod: all
siteSettings:
  5435578f-4317-4fbf-b24f-a5fd4d2e9f68: # French
    enabled: true
  d34bee8e-bf22-451d-8339-a4342630833d: # Canada
    enabled: true
  e7f9ef82-aa7c-4def-8477-dbe7648488b5: # USA
    enabled: true
sortOrder: 7
structure:
  maxLevels: 2
  uid: 571da5a0-3eae-462e-bc8d-7cfbf12f4f8a
