changedFieldIndicator: 440180381
field: c3f20b8d-cdd0-43a3-99eb-82b7227efd55 # External embeds
fieldLayouts:
  ebf0ffeb-440f-4fd8-9df2-bdc2da78f0fd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e2b4c062-1d0e-44da-b5ad-e58d576cb573 # URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 481304d9-1817-452a-b6e8-4a63dfa672ec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 701f481b-981f-47d6-92c9-55d90b39a67e # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 555707ba-b567-426e-a7aa-ccf0f55db325
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6521930c-ca7f-49d9-978b-f0d0d7fe98c1 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9bcdfdd4-1960-4b13-895a-3e0859613ef8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fca5420c-cfc5-4a47-a768-e76e28e66dbf # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee6a8620-7583-47d3-b6ce-e72584fbb86d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2837a036-6824-4d2f-983d-7d613e1064d3
        userCondition: null
fields:
  701f481b-981f-47d6-92c9-55d90b39a67e: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Images
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
        - json
      branchLimit: null
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: '{# for fields inside a supertable inside a matrix block #} {{- ( object.owner.owner.variants   ?? null  ) ? "products/#{object.owner.owner.type.handle|lower}/" : '''' -}} {{- ( object.owner.owner.product    ?? null  ) ? "products/#{object.owner.owner.product.type.handle|lower}/" : '''' -}} {{- ( object.owner.owner.section    ?? null  ) ? "#{object.owner.owner.section.handle|lower}/" : '''' -}} {{- ( object.owner.owner.parentUri  ?? null  ) ? "#{object.owner.owner.parentUri|replace(''__'','''')}/" : '''' -}} {{object.owner.owner.slug}}'
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose cover image'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  6521930c-ca7f-49d9-978b-f0d0d7fe98c1: # Headline
    columnSuffix: eahzqahy
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Headline.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  e2b4c062-1d0e-44da-b5ad-e58d576cb573: # URL
    columnSuffix: vkcqiuwt
    contentColumnType: string(255)
    fieldGroup: null
    handle: sourceUrl
    instructions: null
    name: URL
    searchable: true
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  fca5420c-cfc5-4a47-a768-e76e28e66dbf: # Summary
    columnSuffix: alexdevy
    contentColumnType: text
    fieldGroup: null
    handle: summary
    instructions: null
    name: Summary
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
