changedFieldIndicator: 798915563
field: 6f3a7e60-9dca-477c-a7ae-5036b3eb5b3a # External embeds
fieldLayouts:
  5f5bba65-dfcb-469c-add6-37ab8159bbc9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2d5bb889-39ec-4fa2-a335-4da112f02883 # URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58873737-0778-42a2-ba92-2fe12aa8846a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7cdd6c44-0763-4da7-b111-11aab2acc10a # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e76f9f4-6649-4079-b331-75fd8ea4335b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 09e50183-d1b1-42d2-b180-e0361635c25d # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22e6073c-b0c6-4786-875b-fee50cb6713b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4f577f48-b93a-4e3f-b645-62bb283d8097 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b74eb058-2259-4e53-a7da-f85ad9d4b29c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d368f5aa-bce0-4719-9907-215fa6eaa5d6
        userCondition: null
fields:
  2d5bb889-39ec-4fa2-a335-4da112f02883: # URL
    columnSuffix: rnqgiooo
    contentColumnType: string(255)
    fieldGroup: null
    handle: sourceUrl
    instructions: null
    name: URL
    searchable: true
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  4f577f48-b93a-4e3f-b645-62bb283d8097: # Summary
    columnSuffix: lkiwwwti
    contentColumnType: text
    fieldGroup: null
    handle: summary
    instructions: null
    name: Summary
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  7cdd6c44-0763-4da7-b111-11aab2acc10a: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Images
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
        - json
      branchLimit: null
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: '{# for fields inside a supertable inside a matrix block #} {{- ( object.owner.owner.variants   ?? null  ) ? "products/#{object.owner.owner.type.handle|lower}/" : '''' -}} {{- ( object.owner.owner.product    ?? null  ) ? "products/#{object.owner.owner.product.type.handle|lower}/" : '''' -}} {{- ( object.owner.owner.section    ?? null  ) ? "#{object.owner.owner.section.handle|lower}/" : '''' -}} {{- ( object.owner.owner.parentUri  ?? null  ) ? "#{object.owner.owner.parentUri|replace(''__'','''')}/" : '''' -}} {{object.owner.owner.slug}}'
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose cover image'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  09e50183-d1b1-42d2-b180-e0361635c25d: # Headline
    columnSuffix: hmhynzdx
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Headline.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
