changedFieldIndicator: null
field: 93f90adb-ea61-4a42-9c1b-8e8cd9cd401a # Inline Content Items
fieldLayouts:
  04f3ca97-a5b1-4246-a098-74bb28e48eec:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cc85d929-74a4-4c0e-865b-e9f6908ee04f # Bit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd85deed-9b59-4ba3-98d9-18302203ec6f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cf40ed12-2f61-4865-b636-bff9d855e9fd # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 238d9024-216a-403a-a373-5679ae5ba4ae
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7daa91a4-3926-420c-bbe9-ff190309a2a2 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a33c1017-8c9d-4107-8d58-b0b10c77c92c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec76e3a7-f51a-4255-be63-5608063cfe33 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87dce675-47d8-4b09-adff-5ebf42aeadc4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ab2b7bc8-1fc2-426e-b6aa-8eb51dfb8116
        userCondition: null
fields:
  7daa91a4-3926-420c-bbe9-ff190309a2a2: # Text
    columnSuffix: iyisjndl
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  cc85d929-74a4-4c0e-865b-e9f6908ee04f: # Bit
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: bit
    instructions: null
    name: Bit
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - 76ffa016-f8cb-45e0-9205-f66adc3e654b
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - 29ded7b8-e4a1-43ce-b030-eac97433cb97 # Reusable Bits
      selectionLabel: 'Pick Bit'
      showSiteMenu: false
      sources:
        - 'section:a52e2b08-2e30-4b00-8784-4104c409d3ed' # Modular Content
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  cf40ed12-2f61-4865-b636-bff9d855e9fd: # Headline
    columnSuffix: ojmywfbf
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: HeadlineWithLink.json
      removeEmptyTags: true
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  ec76e3a7-f51a-4255-be63-5608063cfe33: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
        - json
      branchLimit: null
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: '{# for fields inside a supertable inside a matrix block #} {{- ( object.owner.owner.variants   ?? null  ) ? "products/#{object.owner.owner.type.handle|lower}/" : '''' -}} {{- ( object.owner.owner.product    ?? null  ) ? "products/#{object.owner.owner.product.type.handle|lower}/" : '''' -}} {{- ( object.owner.owner.section    ?? null  ) ? "#{object.owner.owner.section.handle|lower}/" : '''' -}} {{- ( object.owner.owner.parentUri  ?? null  ) ? "#{object.owner.owner.parentUri|replace(''__'','''')}/" : '''' -}} {{object.owner.owner.slug}}'
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
