changedFieldIndicator: 320939661
field: 5347a201-6da8-47ff-bc5b-20a0dc63d44e # Custom Items
fieldLayouts:
  79dd7d9f-7ef5-438e-9e9f-d231cc488aca:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1ddd814c-a3f1-4689-bb67-33d04ad8307a # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61cadeca-8dfa-4a6e-86ec-b11ac8f1e6a4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 69c2d7dc-3df8-4df1-a444-d2ae376da00c # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 69ae4ad8-d5b8-4026-a6cd-9eccd9a8f0be
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fd647249-c4ea-4ade-99ab-13f9e53bba3f # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d93f1dbf-17fa-41ab-b73e-bdf543d358d6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0e802755-824f-48de-979f-ee9d5fd2bf97
        userCondition: null
fields:
  1ddd814c-a3f1-4689-bb67-33d04ad8307a: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: HeadlineWithLink.json
      removeEmptyTags: true
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  69c2d7dc-3df8-4df1-a444-d2ae376da00c: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: SimpleAir.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  fd647249-c4ea-4ade-99ab-13f9e53bba3f: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
        - json
      branchLimit: null
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: '{# for fields inside a supertable inside a matrix block #} {{- ( object.owner.owner.variants   ?? null  ) ? "products/#{object.owner.owner.type.handle|lower}/" : '''' -}} {{- ( object.owner.owner.product    ?? null  ) ? "products/#{object.owner.owner.product.type.handle|lower}/" : '''' -}} {{- ( object.owner.owner.section    ?? null  ) ? "#{object.owner.owner.section.handle|lower}/" : '''' -}} {{- ( object.owner.owner.parentUri  ?? null  ) ? "#{object.owner.owner.parentUri|replace(''__'','''')}/" : '''' -}} {{object.owner.owner.slug}}'
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose Image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
