defaultPlacement: end
enableVersioning: true
handle: sitehub
name: Sitehub
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary content entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  94414f3a-f6f6-40ce-b8ea-c865fc1fc491: # Main Site
    enabledByDefault: true
    hasUrls: true
    template: _site/sitehub/core/entry
    uriFormat: '{{parent.uri ?? "sitehub/#{object.type.handle}"}}/{{slug}}'
structure:
  maxLevels: null
  uid: 39b68498-7951-42fa-a7ec-f051d09ba2dd
type: structure
