columnSuffix: null
handle: bits
instructions: null
name: Bits
searchable: false
settings:
  createButtonLabel: Add
  entryTypes:
    - 1eb561c2-313a-4ea5-9332-dd8effd8eb73 # Bit
    - 80b8014d-fa4b-4271-9c59-73cd7c7c6d78 # Article
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
