columnSuffix: null
handle: bits
instructions: null
name: Bits
searchable: false
settings:
  createButtonLabel: Add
  entryTypes:
    - 1eb561c2-313a-4ea5-9332-dd8effd8eb73 # Bit
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: none
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
