columnSuffix: null
contentColumnType: string
fieldGroup: ea1a69ed-b5c5-46cf-a629-4435f7f7cad0 # Matrix Builders
handle: bodyBuilder
instructions: null
name: 'Body Builder'
searchable: true
settings:
  contentTable: '{{%matrixcontent_bodybuilder}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: none
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
