columnSuffix: nbwrlrxg
contentColumnType: string(255)
fieldGroup: b7f29b8a-788f-4f46-a93e-cdfdfa91d44b # Buttons & Links
handle: feed
instructions: null
name: Feed
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
