columnSuffix: gqqtpzit
contentColumnType: text
fieldGroup: 481eb25d-9439-4ee3-85c2-e1a0e6d62d11 # Redactor
handle: headline
instructions: null
name: Headline
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: ''
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: Headline.json
  removeEmptyTags: true
  removeInlineStyles: true
  removeNbsp: false
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
