columnSuffix: hjoahmzs
contentColumnType: string
fieldGroup: b7f29b8a-788f-4f46-a93e-cdfdfa91d44b # URLs & Links
handle: hyperlink
instructions: null
name: Hyperlink
searchable: false
settings:
  allowCustomText: true
  allowTarget: false
  autoNoReferrer: false
  customTextMaxLength: 0
  customTextRequired: false
  defaultLinkName: entry
  defaultText: ''
  enableAllLinkTypes: false
  enableAriaLabel: false
  enableElementCache: false
  enableTitle: false
  typeSettings:
    asset:
      allowCrossSiteLink: false
      allowCustomQuery: false
      enabled: false
      sources: '*'
    category:
      allowCrossSiteLink: false
      allowCustomQuery: false
      enabled: false
      sources: '*'
    custom:
      allowAliases: false
      disableValidation: false
      enabled: false
    email:
      allowAliases: false
      disableValidation: false
      enabled: false
    entry:
      allowCrossSiteLink: false
      allowCustomQuery: false
      enabled: true
      sources:
        - 'section:3721b4d6-42d5-41fc-b6e7-76204b42c91a' # Articles
        - 'section:8c9174b7-2c31-491e-a3f9-0374374c967c' # Landing Pages
        - 'section:942cbdfb-d50d-4dcd-9032-4f483562d1dd' # Topics & Tags
        - 'section:650e7d1d-63e5-42f9-b3ab-4febfb502723' # Primary Pages
    site:
      enabled: true
      sites: '*'
    tel:
      allowAliases: false
      disableValidation: false
      enabled: false
    url:
      allowAliases: false
      disableValidation: false
      enabled: true
    user:
      allowCrossSiteLink: false
      allowCustomQuery: false
      enabled: false
      sources: '*'
translationKeyFormat: null
translationMethod: none
type: lenz\linkfield\fields\LinkField
