columnSuffix: null
handle: issue
instructions: null
name: Issue
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
      -
        - conditionRules
        -
          -
            __assoc__:
              -
                - class
                - craft\elements\conditions\entries\TypeConditionRule
              -
                - uid
                - 72d6c943-b657-44a3-ac83-1d63df4af7ec
              -
                - operator
                - in
              -
                - values
                -
                  - 16eeaaf8-6778-46b1-887b-f4a83630cda3 # Magazine Issue
  selectionLabel: Choose
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:b1ee8bc9-827b-4fec-943c-c6ff229adb59' # Knowledge Base
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
