columnSuffix: null
handle: knowledge
instructions: null
name: Knowledge
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: Choose
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:b1ee8bc9-827b-4fec-943c-c6ff229adb59' # Knowledge Base
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
