columnSuffix: null
handle: layout
instructions: null
name: 'Copy Layout'
searchable: false
settings:
  columnType: null
  configFile: _config/_layout.json.twig
translationKeyFormat: null
translationMethod: none
type: simplicateca\metasettings\fields\MetaSettingsField
