columnSuffix: null
handle: links
instructions: null
name: 'Outbound Links & Accounts'
searchable: true
settings:
  addRowLabel: Add
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Type
            -
              - handle
              - type
            -
              - width
              - '40'
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - 'Auto Detect'
                    -
                      - value
                      - autoDetect
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - 'Amazon Referrer'
                    -
                      - value
                      - amazon
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Email
                    -
                      - value
                      - email
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Facebook
                    -
                      - value
                      - facebook
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Google
                    -
                      - value
                      - google
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Instagram
                    -
                      - value
                      - instagram
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - LinkedIn
                    -
                      - value
                      - linkedin
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Notes
                    -
                      - value
                      - notes
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Phone
                    -
                      - value
                      - phone
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - TikTok
                    -
                      - value
                      - tiktok
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Twitter/X
                    -
                      - value
                      - twitter
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Website
                    -
                      - value
                      - website
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Youtube
                    -
                      - value
                      - youtube
                    -
                      - default
                      - false
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Value
            -
              - handle
              - value
            -
              - width
              - '60'
            -
              - type
              - singleline
  defaults: null
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
