columnSuffix: null
contentColumnType: string
fieldGroup: dc717c0e-4ef4-4f7e-b352-1a7ba8e2ff40 # Assets
handle: media
instructions: null
name: Media
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: false
  allowedKinds:
    - audio
    - compressed
    - excel
    - pdf
    - powerpoint
    - video
    - word
  branchLimit: null
  defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
  restrictedLocationSubpath: null
  selectionLabel: 'Choose file'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
