columnSuffix: null
handle: menu
instructions: null
name: Menu
searchable: false
settings:
  addRowLabel: 'Add item'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Label
            -
              - handle
              - label
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Link
            -
              - handle
              - link
            -
              - width
              - ''
            -
              - type
              - url
      -
        - col4
        -
          __assoc__:
            -
              - heading
              - Depth
            -
              - handle
              - depth
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - '0'
                    -
                      - value
                      - '0'
                    -
                      - default
                      - true
                -
                  __assoc__:
                    -
                      - label
                      - '1'
                    -
                      - value
                      - '1'
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - '2'
                    -
                      - value
                      - '2'
                    -
                      - default
                      - false
  defaults: null
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
