columnSuffix: null
handle: outline
instructions: null
name: Outline
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 941927ac-1577-4a48-adde-7f457a78ace6 # Outline
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
