columnSuffix: null
contentColumnType: string
fieldGroup: ea1a69ed-b5c5-46cf-a629-4435f7f7cad0 # Content Builders
handle: pageExtras
instructions: null
name: 'Page Extras'
searchable: false
settings:
  contentTable: '{{%matrixcontent_pageextras}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: none
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
