columnSuffix: null
handle: richtext
instructions: null
name: Richtext
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 39c47069-569c-4d33-864a-57b76ff50497 # Richtext - Basic
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
