columnSuffix: decgcazw
contentColumnType: text
fieldGroup: e0dac603-c510-4bb5-8701-e25672d93744 # Common
handle: stats
instructions: null
name: Stats
searchable: false
settings:
  addRowLabel: 'Add a stat'
  columnType: text
  columns:
    __assoc__:
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Prefix
            -
              - handle
              - prefixSymbol
            -
              - width
              - 1%
            -
              - type
              - singleline
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Number
            -
              - handle
              - number
            -
              - width
              - 10%
            -
              - type
              - number
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - Postfix
            -
              - handle
              - postfixSymbol
            -
              - width
              - 1%
            -
              - type
              - singleline
      -
        - col5
        -
          __assoc__:
            -
              - heading
              - 'Stat Label'
            -
              - handle
              - label
            -
              - width
              - 15%
            -
              - type
              - singleline
      -
        - col6
        -
          __assoc__:
            -
              - heading
              - Note
            -
              - handle
              - note
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col2
          - ''
        -
          - col1
          - ''
        -
          - col3
          - ''
        -
          - col5
          - ''
        -
          - col6
          - ''
    -
      __assoc__:
        -
          - col2
          - ''
        -
          - col1
          - ''
        -
          - col3
          - ''
        -
          - col5
          - ''
        -
          - col6
          - ''
  maxRows: null
  minRows: 1
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
