columnSuffix: null
handle: text
instructions: null
name: Text
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: ef0d77ed-a6ab-49db-afe4-2be38730d402 # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
