columnSuffix: null
handle: topics
instructions: null
name: Topics
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: true
  maxRelations: null
  minRelations: null
  selectionLabel: 'Choose Topic'
  showCardsInGrid: false
  showSiteMenu: true
  sources:
    - 'section:83a6e4e2-3e52-435e-bcb4-ced4dc7e387e' # Topics
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
