columnSuffix: null
handle: variant
instructions: null
name: Subtype
searchable: false
settings:
  columnType: null
  configFile: _config/_variant.json.twig
translationKeyFormat: null
translationMethod: none
type: simplicateca\metasettings\fields\MetaSettingsField
