defaultPlacement: end
fieldLayouts:
  c8d846b3-7162-4e76-b1bf-8e0b47fae7b3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 2eb6da45-f3c5-411b-aaa5-1b97bf202f3a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: 888b6738-b9b4-4e2d-b8a7-5ea5b985b8fb
            userCondition: null
            warning: null
          -
            attribute: newWindow
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            orientation: null
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: aa217a6b-c29a-4bb2-902e-18b914acf079
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: 289d3632-8871-4105-a783-0093a5015415
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\UrlSuffixField
            uid: 8d1ba919-94cc-4452-b6c5-a767a6fbf19b
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\ClassesField
            uid: aa095808-7e42-4d28-862a-49cd6bd36f69
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            orientation: null
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\CustomAttributesField
            uid: 8f117706-31ba-4031-ad41-67c753f25436
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: 8607ca9b-3afd-4371-bab4-aaf2f7140474
        userCondition: null
handle: legal
instructions: ''
maxNodes: null
name: 'Footer - Legal Menu'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions:
      - 'section:942cbdfb-d50d-4dcd-9032-4f483562d1dd' # Topics
      - 'section:3721b4d6-42d5-41fc-b6e7-76204b42c91a' # News
      - 'section:8c9174b7-2c31-491e-a3f9-0374374c967c' # Landing Pages
      - 'section:650e7d1d-63e5-42f9-b3ab-4febfb502723' # Primary Pages
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
  verbb\navigation\nodetypes\SiteType:
    enabled: '1'
propagationMethod: none
siteSettings:
  41b193c3-f554-4c48-8c8a-7ac2645f083f: # Main Site
    enabled: true
  34463b82-dd3f-441c-b9c6-59c351e847aa: # Main Site (FRENCH)
    enabled: true
sortOrder: 4
structure:
  maxLevels: 1
  uid: 6af44de4-c664-467a-aa7e-ebae66b83613
