defaultPlacement: end
fieldLayouts:
  9ea0ed09-a2ca-4369-bd27-80cbae5f3458:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 09042c3b-b303-4b3d-9fcc-e80205067075
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: 32c569d1-d602-4f35-a3e4-d70b29907fcc
            userCondition: null
            warning: null
          -
            attribute: newWindow
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            orientation: null
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: 11e57b40-ebde-465c-9e41-70bdc7dc0105
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: 78284955-9c25-48e0-a101-af21dd12471a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\UrlSuffixField
            uid: 037f4399-ba6e-4423-b83c-8413a3fc743d
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\ClassesField
            uid: 0d2bcf5a-d7f7-44fa-895b-35412982fc85
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            orientation: null
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\CustomAttributesField
            uid: a5a9c479-0b25-4a5c-bfef-6a73c7564c7b
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: 8c4fe6be-094c-4072-9ecb-2a91ff322b77
        userCondition: null
handle: primary
instructions: null
maxNodes: null
name: Primary
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: ''
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions:
      - 'section:942cbdfb-d50d-4dcd-9032-4f483562d1dd' # Topics
      - 'section:3721b4d6-42d5-41fc-b6e7-76204b42c91a' # News
      - 'section:8c9174b7-2c31-491e-a3f9-0374374c967c' # Landing Pages
      - 'section:650e7d1d-63e5-42f9-b3ab-4febfb502723' # Primary Pages
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
  verbb\navigation\nodetypes\SiteType:
    enabled: ''
propagationMethod: all
siteSettings:
  41b193c3-f554-4c48-8c8a-7ac2645f083f: # Main Site
    enabled: true
  34463b82-dd3f-441c-b9c6-59c351e847aa: # Main Site (FRENCH)
    enabled: true
sortOrder: 3
structure:
  maxLevels: 2
  uid: 73e32a07-4773-48cf-94f7-6cfc39f43331
