field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Body Builder
fieldLayouts:
  b140a9b2-9811-44ea-82e0-e32fa3582bd8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b7ec333d-193c-4bfe-b1c2-637e039f302d # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26724913-ce96-4be7-b2f5-86dc5ffff9eb
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ed9bfc64-1a0b-4a1d-9b9d-8563510c5d9d # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f98e343-13ef-42be-aa7e-6b7a35b1ddd1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: adc05109-eaa7-4f80-b156-5b250a28e878 # Collection
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ecb71c9-cf08-4a15-a9cc-6560a4a97919
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 3382d393-09d2-42d7-8459-07cd8933ece5 # Content Entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14ff069e-b183-49af-82ee-5d9bce2ca46a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ca0addca-320c-4b2c-94c4-f063b00c270a # Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b700b263-06f3-4225-b41a-4228bb12245a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9588272c-eb48-44c0-bb46-e95f8c0d6016 # Component
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b3eb16e-d048-4a16-b530-6329bfa81b9c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4e6dab12-ff70-4db1-9095-aec90d712602 # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c6b1041-1de6-465d-af7e-5d2c49b231cd
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8ecf45da-7553-48ac-b52d-a45f8bc90317 # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fe5567a-e450-4f98-93fe-f5daa278c6e6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4e479aee-581c-4e9e-9c85-c891dca6fd51
        userCondition: null
fields:
  4e6dab12-ff70-4db1-9095-aec90d712602: # Copy
    columnSuffix: wwmudfrl
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Copy
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  8ecf45da-7553-48ac-b52d-a45f8bc90317: # Theme
    columnSuffix: sbrwrmrk
    contentColumnType: text
    fieldGroup: null
    handle: theme
    instructions: null
    name: Theme
    searchable: false
    settings:
      columnType: null
      configFile: _site/json/theme.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  3382d393-09d2-42d7-8459-07cd8933ece5: # Content Entries
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entries
    instructions: null
    name: 'Content Entries'
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionLabel: Choose
      showSiteMenu: false
      sources:
        - 'section:3721b4d6-42d5-41fc-b6e7-76204b42c91a' # Articles
        - 'section:3552382f-ca3b-44ba-95f4-2be9f7773370' # Profiles
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  9588272c-eb48-44c0-bb46-e95f8c0d6016: # Component
    columnSuffix: nzhsczao
    contentColumnType: text
    fieldGroup: null
    handle: component
    instructions: null
    name: Component
    searchable: false
    settings:
      columnType: null
      configFile: _site/json/variant.attention.component.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  adc05109-eaa7-4f80-b156-5b250a28e878: # Collection
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: collections
    instructions: null
    name: Collection
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionLabel: Choose
      showSiteMenu: false
      sources:
        - 'section:2b05c141-a297-4820-ac7d-81e736dbf84b' # Collections
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  b7ec333d-193c-4bfe-b1c2-637e039f302d: # Variant
    columnSuffix: fvriqqes
    contentColumnType: text
    fieldGroup: null
    handle: variant
    instructions: null
    name: Variant
    searchable: false
    settings:
      columnType: null
      configFile: _site/json/variant.attention.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  ca0addca-320c-4b2c-94c4-f063b00c270a: # Form
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: form
    instructions: null
    name: Form
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionLabel: Choose
      showSiteMenu: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\formie\fields\Forms
  ed9bfc64-1a0b-4a1d-9b9d-8563510c5d9d: # Layout
    columnSuffix: htdbqbuc
    contentColumnType: text
    fieldGroup: null
    handle: layout
    instructions: null
    name: Layout
    searchable: false
    settings:
      columnType: null
      configFile: _site/json/layout.twozone.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
handle: attention
name: Attention
sortOrder: 5
