field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Body Builder
fieldLayouts:
  a1f0f4d1-9056-4f56-b262-8722794749a3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b65678be-7ed0-4665-aaaa-bd9d406b60f4 # Block Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27aa5c02-8af4-4d6b-b0ee-34f54488cb79
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ae3f34db-5fe5-4438-86f0-377cfaebf02a # Content Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33aeadab-024e-46c6-9f23-3bdae21f68da
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0e2362da-4175-4b8f-a6f7-d881f03be73e # Source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b84a41ca-ff56-45f0-829b-d405ac1ea8e3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 85a35bf9-39c4-475c-9abf-7839f75bb8e6 # Collection
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f591dd80-b8a8-49ba-8cc4-f8948b67172e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 5347a201-6da8-47ff-bc5b-20a0dc63d44e # Inline Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4043fe8b-846c-4408-af28-90d689ede417
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9a818c17-ad1d-488d-945a-777b6b8b702f # Content Entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3683d32b-df1e-4a5a-b7ed-621696fce332
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c6677eab-6c78-4ca1-93cd-0faa266d1c45 # Primary Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6017252d-7c65-4716-8587-0267805477aa
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 7b72b671-dcdc-49b2-95cd-44a8e8be7cad # Theme & Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9125f69-85d0-464d-a645-9adf0935f0d9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6272049f-8eaf-4847-a1fc-52a1f881a7a9
        userCondition: null
fields:
  0e2362da-4175-4b8f-a6f7-d881f03be73e: # Source
    columnSuffix: knlnnrsn
    contentColumnType: text
    fieldGroup: null
    handle: source
    instructions: null
    name: Source
    searchable: false
    settings:
      columnType: null
      configFile: _config/block.sources.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  7b72b671-dcdc-49b2-95cd-44a8e8be7cad: # Theme & Spacing
    columnSuffix: ngczrvyg
    contentColumnType: text
    fieldGroup: null
    handle: theme
    instructions: null
    name: 'Theme & Spacing'
    searchable: false
    settings:
      columnType: null
      configFile: _config/theme.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  9a818c17-ad1d-488d-945a-777b6b8b702f: # Content Entries
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entries
    instructions: null
    name: 'Content Entries'
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - ad670189-2bcf-47e9-a6ec-7d4673cc6428
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - d3282cfb-d044-4890-b553-9a0b87393027 # Insights & Ideas
                      - 8000f4a4-93b8-4f5b-b6b2-b26e6c12e366 # News & Updates
                      - 9d712dc3-2d54-4b21-bbc3-251dad2d4dc9 # Default
                      - e0521335-ccc2-4893-a505-4baacf112dee # Standard
                      - 1da13089-e303-46d0-930f-aefd062df474 # Standard w/ Sidebar
                      - b26498c0-236e-4738-85e6-666d3439cbc5 # Default
                      - 29ded7b8-e4a1-43ce-b030-eac97433cb97 # Content Bits ★
                      - 912adfc2-2bca-47f1-9da2-f1ed5514623c # Public
      selectionLabel: Choose
      showSiteMenu: false
      sources:
        - 'section:3721b4d6-42d5-41fc-b6e7-76204b42c91a' # Articles
        - 'section:fff3cc82-2855-4031-b003-b91d6e16088b' # FAQs
        - 'section:650e7d1d-63e5-42f9-b3ab-4febfb502723' # Primary Pages
        - 'section:3552382f-ca3b-44ba-95f4-2be9f7773370' # Profiles
        - 'section:a52e2b08-2e30-4b00-8784-4104c409d3ed' # Reusable Content
        - 'section:942cbdfb-d50d-4dcd-9032-4f483562d1dd' # Topics & Tags
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  85a35bf9-39c4-475c-9abf-7839f75bb8e6: # Collection
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: collections
    instructions: null
    name: Collection
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionLabel: Choose
      showSiteMenu: false
      sources:
        - 'section:2b05c141-a297-4820-ac7d-81e736dbf84b' # Collections
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  5347a201-6da8-47ff-bc5b-20a0dc63d44e: # Inline Items
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: null
    name: 'Inline Items'
    searchable: true
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 508840169
      columns:
        __assoc__:
          -
            - 4b14309d-1992-4d32-aea0-2585f21d1fb9 # Bit
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 1ddd814c-a3f1-4689-bb67-33d04ad8307a # Headline
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 69c2d7dc-3df8-4df1-a444-d2ae376da00c # Text
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - fd647249-c4ea-4ade-99ab-13f9e53bba3f # Image
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_16_items}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: none
      selectionLabel: 'Add Item'
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  ae3f34db-5fe5-4438-86f0-377cfaebf02a: # Content Layout
    columnSuffix: ulxtrpcp
    contentColumnType: text
    fieldGroup: null
    handle: layout
    instructions: null
    name: 'Content Layout'
    searchable: false
    settings:
      columnType: null
      configFile: _config/layout.twozone.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  b65678be-7ed0-4665-aaaa-bd9d406b60f4: # Block Variant
    columnSuffix: uzgufcyh
    contentColumnType: text
    fieldGroup: null
    handle: variant
    instructions: null
    name: 'Block Variant'
    searchable: false
    settings:
      columnType: null
      configFile: _config/block.collection.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  c6677eab-6c78-4ca1-93cd-0faa266d1c45: # Primary Copy
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: 'Primary Copy'
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: collection
name: 'Card Deck'
sortOrder: 4
