field: 4e35d6a3-a782-43b2-9eef-24ce9981139c # Header Builder
fieldLayouts:
  e33f433d-80d7-424f-9422-a4529e78ba28:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: fd6d87e0-2eb5-4d92-a444-248b2b64cdc9 # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd0d9f87-4729-4a00-bf80-b4cf560ab4ac
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 57c70792-3dc3-41c3-b589-5905564ed8bf # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf88b170-93ef-47a2-952c-9e392f99fe76
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: fc6a5bc8-a476-4c9b-abc1-03951e7655b2 # Headline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73ace366-ae63-405d-835c-de0ceec37dab
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: f3397041-ad37-43bc-a34d-a9fd1098dc5d # Where are the Collection items located?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c329009a-ab73-45a3-8bc0-ea03ba648b0c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f2b51270-1b49-4e0a-9754-9489a1448bd1 # Supporting Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3eea7ac2-8d2b-48ff-bfb2-82d02eb2de35
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: fa5bb5a3-a50d-4e85-b791-d7fa879c4cc3 # Entries in this Collection
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df64e4f7-ec09-43d1-8ead-ebd7fb7e1e5b
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 83e0e738-2b3a-412b-9ca3-a81fef9fc5cf # Assets in this Collection
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f99de22d-4301-40ca-bd86-e64ca329cf4a
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 3bcee476-f047-43a5-aac1-4ab876c81fc9 # Content feed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d75fbfe-7782-4db6-8fec-53e882da8fe3
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 15a49573-5f4a-4cbe-9f48-01ef2d09552a # Limit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61c114c6-c518-4307-a2d1-825a3439e809
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 7924e3d9-3886-49e6-b154-7f04f943b3e1 # Feed interface
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4644574-4578-46d3-84e7-2f7377600861
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 93f90adb-ea61-4a42-9c1b-8e8cd9cd401a # Items in this collection
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64a162f9-54b9-4f0b-ac54-46b1f1e81355
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 9b24caba-a07d-4707-a391-0384522221b0 # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85c5a712-2ce5-4a1a-9670-14f7b0c22644
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 5a201db9-2e0b-480d-80e0-8ce0a885dea5 # Interspace
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f4eb469-4b5e-4bb0-9b27-8f3c6590cf17
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 8b1f2295-a4ae-41c4-bad9-3ad9eec5ce93
        userCondition: null
fields:
  3bcee476-f047-43a5-aac1-4ab876c81fc9: # Content feed
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: feeds
    instructions: null
    name: 'Content feed'
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - 019a627e-97f7-4413-92bb-90db7c2fb81f
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - 514c0347-c4dd-4b9a-9979-452fc7db526e # Content Feeds
      selectionLabel: 'Choose feed'
      showSiteMenu: false
      sources:
        - 'section:942cbdfb-d50d-4dcd-9032-4f483562d1dd' # Taxonomies
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  5a201db9-2e0b-480d-80e0-8ce0a885dea5: # Interspace
    columnSuffix: tzxttiwt
    contentColumnType: string
    fieldGroup: null
    handle: interspace
    instructions: null
    name: Interspace
    searchable: true
    settings:
      referenceFile: _blocks/config/interspace.header.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  9b24caba-a07d-4707-a391-0384522221b0: # Theme
    columnSuffix: ubgdzwer
    contentColumnType: string
    fieldGroup: null
    handle: theme
    instructions: null
    name: Theme
    searchable: true
    settings:
      referenceFile: _blocks/config/theme.header.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  15a49573-5f4a-4cbe-9f48-01ef2d09552a: # Limit
    columnSuffix: iqxbxbtn
    contentColumnType: integer(10)
    fieldGroup: null
    handle: limit
    instructions: null
    name: Limit
    searchable: true
    settings:
      decimals: 0
      defaultValue: 3
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  57c70792-3dc3-41c3-b589-5905564ed8bf: # Variant
    columnSuffix: ggmzwpop
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: null
    name: Variant
    searchable: true
    settings:
      referenceFile: _blocks/config/variant.collection.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  83e0e738-2b3a-412b-9ca3-a81fef9fc5cf: # Assets in this Collection
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: assets
    instructions: null
    name: 'Assets in this Collection'
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - audio
        - compressed
        - excel
        - json
        - pdf
        - powerpoint
        - text
        - video
        - word
      branchLimit: null
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: '{{- ( object.owner.variants   ?? null  ) ? "products/#{object.owner.type.handle|lower}/" : '''' -}} {{- ( object.owner.product    ?? null  ) ? "products/#{object.owner.product.type.handle|lower}/" : '''' -}} {{- ( object.owner.section    ?? null  ) ? "#{object.owner.section.handle|lower}/" : '''' -}} {{- ( object.owner.parentUri  ?? null  ) ? "#{object.owner.parentUri|replace(''__'','''')}/" : '''' -}} {{object.owner.slug}}'
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose asset'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  93f90adb-ea61-4a42-9c1b-8e8cd9cd401a: # Items in this collection
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: null
    name: 'Items in this collection'
    searchable: true
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1924807404
      columns:
        __assoc__:
          -
            - cc85d929-74a4-4c0e-865b-e9f6908ee04f # Bit
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - cf40ed12-2f61-4865-b636-bff9d855e9fd # Headline
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 7daa91a4-3926-420c-bbe9-ff190309a2a2 # Text
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - ec76e3a7-f51a-4255-be63-5608063cfe33 # Image
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_39_items}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: none
      selectionLabel: 'Add item'
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  7924e3d9-3886-49e6-b154-7f04f943b3e1: # Feed interface
    columnSuffix: quzzcwhr
    contentColumnType: string
    fieldGroup: null
    handle: interface
    instructions: null
    name: 'Feed interface'
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - ''
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Pagination (next/previous)'
            -
              - value
              - pagination
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Full search interface'
            -
              - value
              - fullSearch
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Filter by Feed'
            -
              - value
              - filterByFeed
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Link to feed homepage (if one exists)'
            -
              - value
              - linkFeedHome
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  f2b51270-1b49-4e0a-9754-9489a1448bd1: # Supporting Copy
    columnSuffix: oreqyira
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: 'Supporting Copy'
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  f3397041-ad37-43bc-a34d-a9fd1098dc5d: # Where are the Collection items located?
    columnSuffix: smawlygh
    contentColumnType: string
    fieldGroup: null
    handle: source
    instructions: null
    name: 'Where are the Collection items located?'
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - 'Inline - create items in this block'
            -
              - value
              - items
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Specific - select existing content entries'
            -
              - value
              - entries
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Dynamic - choose a predefined content feed'
            -
              - value
              - feed
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Assets - specific files uploaded inside Craft'
            -
              - value
              - assets
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  fa5bb5a3-a50d-4e85-b791-d7fa879c4cc3: # Entries in this Collection
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entries
    instructions: null
    name: 'Entries in this Collection'
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - b788b7aa-9a49-4b54-aaef-aaab344aabc9
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - d3282cfb-d044-4890-b553-9a0b87393027 # Insights & Ideas
                      - 8000f4a4-93b8-4f5b-b6b2-b26e6c12e366 # News & Updates
                      - 9d712dc3-2d54-4b21-bbc3-251dad2d4dc9 # Default
                      - 29ded7b8-e4a1-43ce-b030-eac97433cb97 # Reusable Bits
                      - e0521335-ccc2-4893-a505-4baacf112dee # Standard
                      - 1da13089-e303-46d0-930f-aefd062df474 # Standard w/ Sidebar
                      - b26498c0-236e-4738-85e6-666d3439cbc5 # Default
                      - 912adfc2-2bca-47f1-9da2-f1ed5514623c # Topics & Themes
      selectionLabel: 'Choose entry'
      showSiteMenu: false
      sources:
        - 'section:3721b4d6-42d5-41fc-b6e7-76204b42c91a' # Articles
        - 'section:fff3cc82-2855-4031-b003-b91d6e16088b' # FAQs
        - 'section:a52e2b08-2e30-4b00-8784-4104c409d3ed' # Modular Content
        - 'section:650e7d1d-63e5-42f9-b3ab-4febfb502723' # Primary Pages
        - 'section:3552382f-ca3b-44ba-95f4-2be9f7773370' # Profiles
        - 'section:942cbdfb-d50d-4dcd-9032-4f483562d1dd' # Taxonomies
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  fc6a5bc8-a476-4c9b-abc1-03951e7655b2: # Headline
    columnSuffix: hdlobvsy
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: 'Replaces the page <title> and acts as the default SEO <h1> tag'
    name: Headline
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Headline.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: false
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  fd6d87e0-2eb5-4d92-a444-248b2b64cdc9: # Layout
    columnSuffix: fomznthw
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: null
    name: Layout
    searchable: true
    settings:
      referenceFile: _blocks/config/layout.collection.header.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
handle: collection
name: Collection
sortOrder: 5
