field: a35a0beb-0cf7-4a2b-9ec3-91e953a18116 # Sidebar Builder
fieldLayouts:
  69fb80dc-7ba3-4320-a6b5-fa7c0a4ac0f5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 87c55206-b434-47f6-844d-1d8664946c2b # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e074f42e-4643-4f3c-bff5-4268ce8004fc
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 1acf385f-ccfd-46ca-a526-91115dad48a5 # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b58baaec-776a-4a18-9652-c7d45fedd184
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 595b273f-27a3-4469-bbee-7a14141cadab # Text (Intro)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 209a52a1-170b-4b65-97a5-555db7a9f61c
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: bfbcdaa7-793d-4876-911c-c943b49061dd # Content source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b78d0a7-99af-47c1-ae8f-44f4675189aa
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 1cc41dda-2e96-4e16-967f-c1e9c567ad99 # Card design
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ccdce38-5a5b-4d7d-9aca-bbbae7aa5c22
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: dff5de1e-c92e-47c2-bed2-2e31bca44a38 # Existing entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9544d211-1d29-4f05-b25c-f3881928b697
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: b66cd5b9-c63b-48da-88e4-4f0af9f0c6e7 # Uploaded assets
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a053deac-fe49-460d-84bc-cfe3e4a4932d
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: bc32472f-668b-443f-94a8-94873d0473d2 # Saved searches
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 841d252f-66ac-44a7-9ca0-03dae8a4aefa
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4f4fd272-518d-4ece-885a-b3912bcd5eff # Limit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49c598bb-0f46-4ad4-a93d-6dd5d8cc7f79
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 1f910dd9-3b38-45b3-9b88-d01515f45a0c # Search navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1c9edbb-5719-42fb-a752-d7b12261aa59
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 606e97ed-f3fc-481c-9cfb-980f44a2b807 # Custom Bits
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc3b57f6-f3ae-4c9b-bf0c-35f48601b52b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 577dd7e1-eea7-4b11-9b21-1f402770e968 # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ad93d0c-4ec2-4199-bf26-47dd9707d941
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: d761232e-d5c6-4df1-8817-dc7893409358 # Interspace
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e7b191f-7492-4382-a2ea-f0a21d58007f
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 118a3008-759b-45f6-aca3-eb1f796e4242
        userCondition: null
fields:
  1acf385f-ccfd-46ca-a526-91115dad48a5: # Variant
    columnSuffix: bmkgicur
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: null
    name: Variant
    searchable: false
    settings:
      referenceFile: _blocks/config/variantCollection.sidebar.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  1cc41dda-2e96-4e16-967f-c1e9c567ad99: # Card design
    columnSuffix: pegniaoa
    contentColumnType: string
    fieldGroup: null
    handle: card
    instructions: null
    name: 'Card design'
    searchable: false
    settings:
      referenceFile: _blocks/config/cardDesigns.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  1f910dd9-3b38-45b3-9b88-d01515f45a0c: # Search navigation
    columnSuffix: dscmezqh
    contentColumnType: string
    fieldGroup: null
    handle: pagination
    instructions: null
    name: 'Search navigation'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - ''
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'See All'
            -
              - value
              - all
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Next / Previous'
            -
              - value
              - standard
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  4f4fd272-518d-4ece-885a-b3912bcd5eff: # Limit
    columnSuffix: uhipktkw
    contentColumnType: integer(10)
    fieldGroup: null
    handle: limit
    instructions: null
    name: Limit
    searchable: false
    settings:
      decimals: 0
      defaultValue: 3
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  87c55206-b434-47f6-844d-1d8664946c2b: # Layout
    columnSuffix: soxbrgat
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: 'Change the block layout without changing its underlying content'
    name: Layout
    searchable: false
    settings:
      referenceFile: _blocks/config/layoutCollection.sidebar.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  577dd7e1-eea7-4b11-9b21-1f402770e968: # Theme
    columnSuffix: vjfuuosn
    contentColumnType: string
    fieldGroup: null
    handle: theme
    instructions: 'Set the background style behind this block.'
    name: Theme
    searchable: false
    settings:
      referenceFile: _blocks/config/themeSidebar.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  595b273f-27a3-4469-bbee-7a14141cadab: # Text (Intro)
    columnSuffix: mmtqywpd
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: 'Optional text content to introduce or describe the content being teased'
    name: 'Text (Intro)'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  606e97ed-f3fc-481c-9cfb-980f44a2b807: # Custom Bits
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: null
    name: 'Custom Bits'
    searchable: true
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 328957973
      columns:
        __assoc__:
          -
            - a021ef5c-0aa2-450d-ba8d-1740e0ababab # Headline
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 0d222dec-052d-44e2-b502-e9e1109f695d # Text
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 5de1b0db-922b-408d-a23e-428e92dc0cc0 # Image
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_21_items}}'
      fieldLayout: table
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add Bit'
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  b66cd5b9-c63b-48da-88e4-4f0af9f0c6e7: # Uploaded assets
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: assets
    instructions: null
    name: 'Uploaded assets'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - audio
        - code
        - compressed
        - excel
        - json
        - markdown
        - pdf
        - powerpoint
        - text
        - video
        - word
      branchLimit: null
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: '{{- ( object.owner.variants   ?? null  ) ? "products/#{object.owner.type.handle|lower}/" : '''' -}} {{- ( object.owner.product    ?? null  ) ? "products/#{object.owner.product.type.handle|lower}/" : '''' -}} {{- ( object.owner.section    ?? null  ) ? "#{object.owner.section.handle|lower}/" : '''' -}} {{- ( object.owner.parentUri  ?? null  ) ? "#{object.owner.parentUri|replace(''__'','''')}/" : '''' -}} {{object.owner.slug}}'
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose Asset'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  bc32472f-668b-443f-94a8-94873d0473d2: # Saved searches
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: searches
    instructions: null
    name: 'Saved searches'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - 8708f8e8-80ac-40d2-a198-8b29dfe2919a
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - 514c0347-c4dd-4b9a-9979-452fc7db526e # Content Feeds
      selectionLabel: null
      showSiteMenu: false
      sources:
        - 'section:942cbdfb-d50d-4dcd-9032-4f483562d1dd' # Taxonomies
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  bfbcdaa7-793d-4876-911c-c943b49061dd: # Content source
    columnSuffix: jplrbrdm
    contentColumnType: string
    fieldGroup: null
    handle: contentSource
    instructions: null
    name: 'Content source'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Content Entries'
            -
              - value
              - entries
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Search Results'
            -
              - value
              - search
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Files & Assets'
            -
              - value
              - assets
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Custom Text'
            -
              - value
              - items
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  d761232e-d5c6-4df1-8817-dc7893409358: # Interspace
    columnSuffix: tautdznt
    contentColumnType: string
    fieldGroup: null
    handle: interspace
    instructions: 'Control the area between blocks'
    name: Interspace
    searchable: false
    settings:
      referenceFile: _blocks/config/interspaceSidebar.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  dff5de1e-c92e-47c2-bed2-2e31bca44a38: # Existing entries
    columnSuffix: hltpnvam
    contentColumnType: string
    fieldGroup: null
    handle: entries
    instructions: null
    name: 'Existing entries'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - d03f7e9d-81bf-49b8-924c-49efb2b5af68
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - d3282cfb-d044-4890-b553-9a0b87393027 # SEO / Blog
                      - 8000f4a4-93b8-4f5b-b6b2-b26e6c12e366 # News
                      - e0521335-ccc2-4893-a505-4baacf112dee # Standard
                      - 1da13089-e303-46d0-930f-aefd062df474 # Standard w/ Sidebar
                      - 912adfc2-2bca-47f1-9da2-f1ed5514623c # Topics & Themes
      selectionLabel: 'Choose Entry'
      showSiteMenu: false
      sources:
        - 'section:3721b4d6-42d5-41fc-b6e7-76204b42c91a' # Articles
        - 'section:a52e2b08-2e30-4b00-8784-4104c409d3ed' # Modular Content
        - 'section:650e7d1d-63e5-42f9-b3ab-4febfb502723' # Primary Pages
        - 'section:942cbdfb-d50d-4dcd-9032-4f483562d1dd' # Taxonomies
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: collection
name: Collection
sortOrder: 4
