field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
fieldLayouts:
  a1f0f4d1-9056-4f56-b262-8722794749a3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ae3f34db-5fe5-4438-86f0-377cfaebf02a # Content layout and positioning
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33aeadab-024e-46c6-9f23-3bdae21f68da
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b65678be-7ed0-4665-aaaa-bd9d406b60f4 # Style variation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27aa5c02-8af4-4d6b-b0ee-34f54488cb79
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0e2362da-4175-4b8f-a6f7-d881f03be73e # Where are the Collection items located?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b84a41ca-ff56-45f0-829b-d405ac1ea8e3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c6677eab-6c78-4ca1-93cd-0faa266d1c45 # Copy to introduce and support the Collection
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6017252d-7c65-4716-8587-0267805477aa
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9a818c17-ad1d-488d-945a-777b6b8b702f # Entries in this Collection
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3683d32b-df1e-4a5a-b7ed-621696fce332
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 14fd2961-f771-44f1-9b9c-aede9b59a565 # Assets in this Collection
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fd46570-e8f2-4db3-89dd-0b979b0dedc4
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 85a35bf9-39c4-475c-9abf-7839f75bb8e6 # Content feed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f591dd80-b8a8-49ba-8cc4-f8948b67172e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 6fe06c51-450b-43b8-8ff4-88f896048fd2 # Limit to... ?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26ea4909-3af2-46b1-ab8b-13be80591d83
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: a8dc4c16-ac4a-41eb-b5cb-a83598b8313f # Navigation and filtering
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb10bc5b-d99c-46e6-a1fe-458f4c0d0d63
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 5347a201-6da8-47ff-bc5b-20a0dc63d44e # Items in this collection
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4043fe8b-846c-4408-af28-90d689ede417
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 7b72b671-dcdc-49b2-95cd-44a8e8be7cad # Background theme and colours
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9125f69-85d0-464d-a645-9adf0935f0d9
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a1a62d7a-5173-4caf-8d92-423b6dc0dede # Area between and around the block
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6cead47-c085-40f3-975f-ce5f00b44f23
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 6272049f-8eaf-4847-a1fc-52a1f881a7a9
        userCondition: null
fields:
  0e2362da-4175-4b8f-a6f7-d881f03be73e: # Where are the Collection items located?
    columnSuffix: knlnnrsn
    contentColumnType: string
    fieldGroup: null
    handle: source
    instructions: null
    name: 'Where are the Collection items located?'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - 'Inline - create items in this block'
            -
              - value
              - items
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Specific - select existing content entries'
            -
              - value
              - entries
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Dynamic - choose a predefined content feed'
            -
              - value
              - feed
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Assets - specific files uploaded inside Craft'
            -
              - value
              - assets
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  6fe06c51-450b-43b8-8ff4-88f896048fd2: # Limit to... ?
    columnSuffix: zbgxqkrw
    contentColumnType: integer(10)
    fieldGroup: null
    handle: limit
    instructions: null
    name: 'Limit to... ?'
    searchable: false
    settings:
      decimals: 0
      defaultValue: 3
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  7b72b671-dcdc-49b2-95cd-44a8e8be7cad: # Background theme and colours
    columnSuffix: ngczrvyg
    contentColumnType: string
    fieldGroup: null
    handle: theme
    instructions: null
    name: 'Background theme and colours'
    searchable: false
    settings:
      referenceFile: _blocks/config/themeContent.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  9a818c17-ad1d-488d-945a-777b6b8b702f: # Entries in this Collection
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entries
    instructions: null
    name: 'Entries in this Collection'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - ad670189-2bcf-47e9-a6ec-7d4673cc6428
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - d3282cfb-d044-4890-b553-9a0b87393027 # Insights & Ideas
                      - 8000f4a4-93b8-4f5b-b6b2-b26e6c12e366 # News & Updates
                      - 9d712dc3-2d54-4b21-bbc3-251dad2d4dc9 # Default
                      - 29ded7b8-e4a1-43ce-b030-eac97433cb97 # Reusable Bits
                      - e0521335-ccc2-4893-a505-4baacf112dee # Standard
                      - 1da13089-e303-46d0-930f-aefd062df474 # Standard w/ Sidebar
                      - b26498c0-236e-4738-85e6-666d3439cbc5 # Default
                      - 912adfc2-2bca-47f1-9da2-f1ed5514623c # Topics & Themes
      selectionLabel: 'Choose entry'
      showSiteMenu: false
      sources:
        - 'section:3721b4d6-42d5-41fc-b6e7-76204b42c91a' # Articles
        - 'section:fff3cc82-2855-4031-b003-b91d6e16088b' # FAQs
        - 'section:a52e2b08-2e30-4b00-8784-4104c409d3ed' # Modular Content
        - 'section:650e7d1d-63e5-42f9-b3ab-4febfb502723' # Primary Pages
        - 'section:3552382f-ca3b-44ba-95f4-2be9f7773370' # Profiles
        - 'section:942cbdfb-d50d-4dcd-9032-4f483562d1dd' # Taxonomies
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  14fd2961-f771-44f1-9b9c-aede9b59a565: # Assets in this Collection
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: assets
    instructions: null
    name: 'Assets in this Collection'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - audio
        - compressed
        - excel
        - json
        - pdf
        - powerpoint
        - text
        - video
        - word
      branchLimit: null
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: '{{- ( object.owner.variants   ?? null  ) ? "products/#{object.owner.type.handle|lower}/" : '''' -}} {{- ( object.owner.product    ?? null  ) ? "products/#{object.owner.product.type.handle|lower}/" : '''' -}} {{- ( object.owner.section    ?? null  ) ? "#{object.owner.section.handle|lower}/" : '''' -}} {{- ( object.owner.parentUri  ?? null  ) ? "#{object.owner.parentUri|replace(''__'','''')}/" : '''' -}} {{object.owner.slug}}'
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose asset'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  85a35bf9-39c4-475c-9abf-7839f75bb8e6: # Content feed
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: feeds
    instructions: null
    name: 'Content feed'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - 2ce107b7-d275-4c31-a7a9-aa356ade2c90
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - 514c0347-c4dd-4b9a-9979-452fc7db526e # Content Feeds
      selectionLabel: 'Choose feed'
      showSiteMenu: false
      sources:
        - 'section:942cbdfb-d50d-4dcd-9032-4f483562d1dd' # Taxonomies
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  5347a201-6da8-47ff-bc5b-20a0dc63d44e: # Items in this collection
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: null
    name: 'Items in this collection'
    searchable: true
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 512361442
      columns:
        __assoc__:
          -
            - 1ddd814c-a3f1-4689-bb67-33d04ad8307a # Headline
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 69c2d7dc-3df8-4df1-a444-d2ae376da00c # Text
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - fd647249-c4ea-4ade-99ab-13f9e53bba3f # Image
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_16_items}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: none
      selectionLabel: 'Add item'
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  a1a62d7a-5173-4caf-8d92-423b6dc0dede: # Area between and around the block
    columnSuffix: vdailebf
    contentColumnType: string
    fieldGroup: null
    handle: interspace
    instructions: null
    name: 'Area between and around the block'
    searchable: false
    settings:
      referenceFile: _blocks/config/interspaceContent.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  a8dc4c16-ac4a-41eb-b5cb-a83598b8313f: # Navigation and filtering
    columnSuffix: bqiltrrw
    contentColumnType: string
    fieldGroup: null
    handle: pagination
    instructions: null
    name: 'Navigation and filtering'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - ''
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Simple pagination (next/previous)'
            -
              - value
              - standard
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Full search interface'
            -
              - value
              - standardWithSearch
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Filter by Feed'
            -
              - value
              - filterByFeed
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Link to feed homepage (if one exists)'
            -
              - value
              - all
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  ae3f34db-5fe5-4438-86f0-377cfaebf02a: # Content layout and positioning
    columnSuffix: ulxtrpcp
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: null
    name: 'Content layout and positioning'
    searchable: false
    settings:
      referenceFile: _blocks/config/layoutCollection.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  b65678be-7ed0-4665-aaaa-bd9d406b60f4: # Style variation
    columnSuffix: uzgufcyh
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: null
    name: 'Style variation'
    searchable: false
    settings:
      referenceFile: _blocks/config/variantCollection.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  c6677eab-6c78-4ca1-93cd-0faa266d1c45: # Copy to introduce and support the Collection
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: 'Copy to introduce and support the Collection'
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: collection
name: Collection
sortOrder: 5
