field: 89834163-b3fe-4c51-9a02-e205e03b9067 # Sidebar Builder
fieldLayouts:
  12600375-3c8e-4137-a8a7-b64b6e63c696:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 54792750-7dcd-49e2-9a83-37079d4198aa # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e9ad8b7-cfe2-4d89-b88c-965c3f16f041
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a5b244ea-d063-415f-b734-399180b09ffa # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a07f6e1-579e-4e17-8862-e6fa5f00c848
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: fdebeb5f-8977-4ea4-9b4d-289e2b73e4c9 # Collection Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b039ea9-c0fa-487a-9480-0c42c52c2618
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: bd2471a2-f2db-4375-979e-234df61dd0a7 # Extra User Interface
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d152eb1a-112b-4c27-be63-ded79388fe41
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b5987eaa-5a19-4169-8bde-3cfe1ac7d3b0 # Limit Results
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c376f0b-4d68-4726-bba1-00fbbdfea6b6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: d35c9f45-ed1c-41ee-9880-b05333b17af0 # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d9da0279-9b94-49f6-becd-241e7a1653fb
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 1be9127a-60e5-4888-bcb0-cc5b7ee55f6f # Content Feed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8992465c-be62-4530-be42-78c2937d963e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 5aacbfe1-d68f-4215-a87f-818ec5dc8f80 # Inline Content Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ddfd2e25-029a-43a5-bf98-61ae1b945ae8
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: cf42e194-fb4c-4218-a6f2-661ccc51b768 # Content Entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33192a1e-5c48-47b7-9187-5301b5b3f87f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 7ce6af04-c2ee-4ef2-b6a7-f529d2b7b65f # Downloadable Files
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4331acec-66a8-4fc5-af8e-e0ba8db93183
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: fd384d46-719e-4da0-9a0e-0e372bc88593 # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29b0202a-f9b7-4849-a07c-6d58a28a8cb4
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ae1eadbc-c67a-42dc-9ceb-9e5ac0423bcc # Interspace
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d171590-355b-4b30-a6e3-3bfb03abba01
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 001fbfbb-dc6b-4250-94d4-1a6973fecd9b
        userCondition: null
fields:
  1be9127a-60e5-4888-bcb0-cc5b7ee55f6f: # Content Feed
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: feeds
    instructions: null
    name: 'Content Feed'
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - 07b15537-9d3b-44b9-822f-025ccaefdd49
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - 514c0347-c4dd-4b9a-9979-452fc7db526e
      selectionLabel: 'Choose feed'
      showSiteMenu: false
      sources:
        - 'section:942cbdfb-d50d-4dcd-9032-4f483562d1dd' # Topics & Tags
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  5aacbfe1-d68f-4215-a87f-818ec5dc8f80: # Inline Content Items
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: null
    name: 'Inline Content Items'
    searchable: true
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 425387396
      columns:
        __assoc__:
          -
            - 6312c62d-00d4-4b29-8c70-1edd6d095729 # Bit
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 1e247634-9eec-49af-b31d-19e6888dbc95 # Headline
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - b4f98162-512f-4866-9808-0187101c848e # Text
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 0b65e8f2-d920-47d0-ada3-db139c088699 # Image
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_32_items}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: none
      selectionLabel: 'Add item'
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  7ce6af04-c2ee-4ef2-b6a7-f529d2b7b65f: # Downloadable Files
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: assets
    instructions: null
    name: 'Downloadable Files'
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - audio
        - compressed
        - excel
        - json
        - pdf
        - powerpoint
        - text
        - video
        - word
      branchLimit: null
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: '{{- ( object.owner.variants   ?? null  ) ? "products/#{object.owner.type.handle|lower}/" : '''' -}} {{- ( object.owner.product    ?? null  ) ? "products/#{object.owner.product.type.handle|lower}/" : '''' -}} {{- ( object.owner.section    ?? null  ) ? "#{object.owner.section.handle|lower}/" : '''' -}} {{- ( object.owner.parentUri  ?? null  ) ? "#{object.owner.parentUri|replace(''__'','''')}/" : '''' -}} {{object.owner.slug}}'
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose asset'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  54792750-7dcd-49e2-9a83-37079d4198aa: # Layout
    columnSuffix: kfemtjwe
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: null
    name: Layout
    searchable: true
    settings:
      configFile: _site/json/layout.collection.sidebar.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  a5b244ea-d063-415f-b734-399180b09ffa: # Variant
    columnSuffix: uistgdbn
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: null
    name: Variant
    searchable: true
    settings:
      configFile: _site/json/variant.collection.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  ae1eadbc-c67a-42dc-9ceb-9e5ac0423bcc: # Interspace
    columnSuffix: orojxfkg
    contentColumnType: string
    fieldGroup: null
    handle: interspace
    instructions: null
    name: Interspace
    searchable: true
    settings:
      configFile: _site/json/interspace.sidebar.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  b5987eaa-5a19-4169-8bde-3cfe1ac7d3b0: # Limit Results
    columnSuffix: tqxpzwva
    contentColumnType: integer(10)
    fieldGroup: null
    handle: limit
    instructions: null
    name: 'Limit Results'
    searchable: true
    settings:
      decimals: 0
      defaultValue: 3
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  bd2471a2-f2db-4375-979e-234df61dd0a7: # Extra User Interface
    columnSuffix: wpyokwcy
    contentColumnType: string
    fieldGroup: null
    handle: interface
    instructions: null
    name: 'Extra User Interface'
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - ''
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Pagination (next/previous)'
            -
              - value
              - pagination
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Full search interface'
            -
              - value
              - fullSearch
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Filter by Feed'
            -
              - value
              - filterByFeed
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Link to feed homepage (if one exists)'
            -
              - value
              - linkFeedHome
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  cf42e194-fb4c-4218-a6f2-661ccc51b768: # Content Entries
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entries
    instructions: null
    name: 'Content Entries'
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - dc07b06b-3bbe-40c5-910c-5845c7f40803
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - d3282cfb-d044-4890-b553-9a0b87393027 # Insights & Ideas
                      - 8000f4a4-93b8-4f5b-b6b2-b26e6c12e366 # News & Updates
                      - 9d712dc3-2d54-4b21-bbc3-251dad2d4dc9 # Default
                      - 29ded7b8-e4a1-43ce-b030-eac97433cb97 # Content ‘Bits’
                      - e0521335-ccc2-4893-a505-4baacf112dee # Standard
                      - 1da13089-e303-46d0-930f-aefd062df474 # Standard w/ Sidebar
                      - b26498c0-236e-4738-85e6-666d3439cbc5 # Default
                      - 912adfc2-2bca-47f1-9da2-f1ed5514623c # Public
      selectionLabel: 'Choose entry'
      showSiteMenu: false
      sources:
        - 'section:3721b4d6-42d5-41fc-b6e7-76204b42c91a' # Articles
        - 'section:fff3cc82-2855-4031-b003-b91d6e16088b' # FAQs
        - 'section:a52e2b08-2e30-4b00-8784-4104c409d3ed' # Reusable Content
        - 'section:650e7d1d-63e5-42f9-b3ab-4febfb502723' # Primary Pages
        - 'section:3552382f-ca3b-44ba-95f4-2be9f7773370' # Profiles
        - 'section:942cbdfb-d50d-4dcd-9032-4f483562d1dd' # Topics & Tags
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  d35c9f45-ed1c-41ee-9880-b05333b17af0: # Copy
    columnSuffix: pbbjjyzf
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Copy
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  fd384d46-719e-4da0-9a0e-0e372bc88593: # Theme
    columnSuffix: jfcyxeqz
    contentColumnType: string
    fieldGroup: null
    handle: theme
    instructions: null
    name: Theme
    searchable: true
    settings:
      configFile: _site/json/theme.sidebar.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  fdebeb5f-8977-4ea4-9b4d-289e2b73e4c9: # Collection Type
    columnSuffix: xrizyblc
    contentColumnType: string
    fieldGroup: null
    handle: source
    instructions: null
    name: 'Collection Type'
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - 'Single-Use Inline Content Items'
            -
              - value
              - items
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Dynamic Content Feed'
            -
              - value
              - feed
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Specific Content Entries'
            -
              - value
              - entries
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Downloadable Files (PDF, ZIP, XLS, etc)'
            -
              - value
              - assets
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
handle: collection
name: Collection
sortOrder: 4
