field: 4e35d6a3-a782-43b2-9eef-24ce9981139c # Header Builder
fieldLayouts:
  e33f433d-80d7-424f-9422-a4529e78ba28:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 57c70792-3dc3-41c3-b589-5905564ed8bf # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf88b170-93ef-47a2-952c-9e392f99fe76
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9b24caba-a07d-4707-a391-0384522221b0 # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85c5a712-2ce5-4a1a-9670-14f7b0c22644
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: fc6a5bc8-a476-4c9b-abc1-03951e7655b2 # Primary Headline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73ace366-ae63-405d-835c-de0ceec37dab
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: f3397041-ad37-43bc-a34d-a9fd1098dc5d # Collection Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c329009a-ab73-45a3-8bc0-ea03ba648b0c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 7924e3d9-3886-49e6-b154-7f04f943b3e1 # Card Interface
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4644574-4578-46d3-84e7-2f7377600861
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 3bcee476-f047-43a5-aac1-4ab876c81fc9 # Collection
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d75fbfe-7782-4db6-8fec-53e882da8fe3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 93f90adb-ea61-4a42-9c1b-8e8cd9cd401a # Inline Content Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64a162f9-54b9-4f0b-ac54-46b1f1e81355
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: fa5bb5a3-a50d-4e85-b791-d7fa879c4cc3 # Content Entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df64e4f7-ec09-43d1-8ead-ebd7fb7e1e5b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f2b51270-1b49-4e0a-9754-9489a1448bd1 # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3eea7ac2-8d2b-48ff-bfb2-82d02eb2de35
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: fd6d87e0-2eb5-4d92-a444-248b2b64cdc9 # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd0d9f87-4729-4a00-bf80-b4cf560ab4ac
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 5a201db9-2e0b-480d-80e0-8ce0a885dea5 # Interspace
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f4eb469-4b5e-4bb0-9b27-8f3c6590cf17
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 8b1f2295-a4ae-41c4-bad9-3ad9eec5ce93
        userCondition: null
fields:
  3bcee476-f047-43a5-aac1-4ab876c81fc9: # Collection
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: collections
    instructions: null
    name: Collection
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: Choose
      showSiteMenu: false
      sources:
        - 'section:2b05c141-a297-4820-ac7d-81e736dbf84b' # Collections
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  5a201db9-2e0b-480d-80e0-8ce0a885dea5: # Interspace
    columnSuffix: tzxttiwt
    contentColumnType: string
    fieldGroup: null
    handle: interspace
    instructions: null
    name: Interspace
    searchable: true
    settings:
      referenceFile: _site/json/interspace.header.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  9b24caba-a07d-4707-a391-0384522221b0: # Theme
    columnSuffix: ubgdzwer
    contentColumnType: string
    fieldGroup: null
    handle: theme
    instructions: null
    name: Theme
    searchable: true
    settings:
      referenceFile: _site/json/theme.header.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  57c70792-3dc3-41c3-b589-5905564ed8bf: # Variant
    columnSuffix: ggmzwpop
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: null
    name: Variant
    searchable: true
    settings:
      referenceFile: _site/json/variant.collection.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  93f90adb-ea61-4a42-9c1b-8e8cd9cd401a: # Inline Content Items
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: null
    name: 'Inline Content Items'
    searchable: true
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 595368515
      columns:
        __assoc__:
          -
            - cc85d929-74a4-4c0e-865b-e9f6908ee04f # Bit
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - cf40ed12-2f61-4865-b636-bff9d855e9fd # Headline
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 7daa91a4-3926-420c-bbe9-ff190309a2a2 # Text
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - ec76e3a7-f51a-4255-be63-5608063cfe33 # Image
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_22_items}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: none
      selectionLabel: 'Add item'
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  7924e3d9-3886-49e6-b154-7f04f943b3e1: # Card Interface
    columnSuffix: quzzcwhr
    contentColumnType: text
    fieldGroup: null
    handle: interface
    instructions: null
    name: 'Card Interface'
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Card
                -
                  - handle
                  - card
                -
                  - width
                  - 30%
                -
                  - type
                  - select
                -
                  - options
                  -
                    -
                      __assoc__:
                        -
                          - label
                          - Thumbnail
                        -
                          - value
                          - thumbnail
                        -
                          - default
                          - true
          -
            - col3
            -
              __assoc__:
                -
                  - heading
                  - Columns
                -
                  - handle
                  - columns
                -
                  - width
                  - 30%
                -
                  - type
                  - select
                -
                  - options
                  -
                    -
                      __assoc__:
                        -
                          - label
                          - 1-up
                        -
                          - value
                          - 1Up
                        -
                          - default
                          - false
          -
            - col4
            -
              __assoc__:
                -
                  - heading
                  - Action
                -
                  - handle
                  - action
                -
                  - width
                  - 30%
                -
                  - type
                  - select
                -
                  - options
                  -
                    -
                      __assoc__:
                        -
                          - label
                          - Auto
                        -
                          - value
                          - auto
                        -
                          - default
                          - true
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Limit
                -
                  - handle
                  - limit
                -
                  - width
                  - 10%
                -
                  - type
                  - number
      defaults: null
      maxRows: null
      minRows: null
      staticRows: true
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  f2b51270-1b49-4e0a-9754-9489a1448bd1: # Copy
    columnSuffix: oreqyira
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Copy
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  f3397041-ad37-43bc-a34d-a9fd1098dc5d: # Collection Type
    columnSuffix: smawlygh
    contentColumnType: string
    fieldGroup: null
    handle: source
    instructions: null
    name: 'Collection Type'
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - 'Single-Use Inline Content Items'
            -
              - value
              - items
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Dynamic Content Feed'
            -
              - value
              - feed
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Specific Content Entries'
            -
              - value
              - entries
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Downloadable Files (PDF, ZIP, XLS, etc)'
            -
              - value
              - assets
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  fa5bb5a3-a50d-4e85-b791-d7fa879c4cc3: # Content Entries
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entries
    instructions: null
    name: 'Content Entries'
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - b788b7aa-9a49-4b54-aaef-aaab344aabc9
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - d3282cfb-d044-4890-b553-9a0b87393027 # Insights & Ideas
                      - 8000f4a4-93b8-4f5b-b6b2-b26e6c12e366 # News & Updates
                      - 9d712dc3-2d54-4b21-bbc3-251dad2d4dc9 # Default
                      - e0521335-ccc2-4893-a505-4baacf112dee # Standard
                      - 1da13089-e303-46d0-930f-aefd062df474 # Standard w/ Sidebar
                      - b26498c0-236e-4738-85e6-666d3439cbc5 # Default
                      - 29ded7b8-e4a1-43ce-b030-eac97433cb97 # Content ‘Bits’
                      - 912adfc2-2bca-47f1-9da2-f1ed5514623c # Public
      selectionLabel: 'Choose entry'
      showSiteMenu: false
      sources:
        - 'section:3721b4d6-42d5-41fc-b6e7-76204b42c91a' # Articles
        - 'section:fff3cc82-2855-4031-b003-b91d6e16088b' # FAQs
        - 'section:650e7d1d-63e5-42f9-b3ab-4febfb502723' # Primary Pages
        - 'section:3552382f-ca3b-44ba-95f4-2be9f7773370' # Profiles
        - 'section:a52e2b08-2e30-4b00-8784-4104c409d3ed' # Reusable Content
        - 'section:942cbdfb-d50d-4dcd-9032-4f483562d1dd' # Topics & Tags
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  fc6a5bc8-a476-4c9b-abc1-03951e7655b2: # Primary Headline
    columnSuffix: hdlobvsy
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: 'Replaces the page <title> and acts as the default SEO <h1> tag'
    name: 'Primary Headline'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Headline.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: false
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  fd6d87e0-2eb5-4d92-a444-248b2b64cdc9: # Layout
    columnSuffix: fomznthw
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: null
    name: Layout
    searchable: true
    settings:
      referenceFile: _site/json/layout.collection.header.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
handle: collection
name: Collection
sortOrder: 4
