field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
fieldLayouts:
  a1f0f4d1-9056-4f56-b262-8722794749a3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ae3f34db-5fe5-4438-86f0-377cfaebf02a # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33aeadab-024e-46c6-9f23-3bdae21f68da
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b65678be-7ed0-4665-aaaa-bd9d406b60f4 # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27aa5c02-8af4-4d6b-b0ee-34f54488cb79
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0e2362da-4175-4b8f-a6f7-d881f03be73e # Collection Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b84a41ca-ff56-45f0-829b-d405ac1ea8e3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c6677eab-6c78-4ca1-93cd-0faa266d1c45 # Supporting Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6017252d-7c65-4716-8587-0267805477aa
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9a818c17-ad1d-488d-945a-777b6b8b702f # Content entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3683d32b-df1e-4a5a-b7ed-621696fce332
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 14fd2961-f771-44f1-9b9c-aede9b59a565 # Uploaded assets
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fd46570-e8f2-4db3-89dd-0b979b0dedc4
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 85a35bf9-39c4-475c-9abf-7839f75bb8e6 # Saved searches
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f591dd80-b8a8-49ba-8cc4-f8948b67172e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 6fe06c51-450b-43b8-8ff4-88f896048fd2 # Limit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26ea4909-3af2-46b1-ab8b-13be80591d83
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: a8dc4c16-ac4a-41eb-b5cb-a83598b8313f # Search navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb10bc5b-d99c-46e6-a1fe-458f4c0d0d63
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 5347a201-6da8-47ff-bc5b-20a0dc63d44e # Custom Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4043fe8b-846c-4408-af28-90d689ede417
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7b72b671-dcdc-49b2-95cd-44a8e8be7cad # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9125f69-85d0-464d-a645-9adf0935f0d9
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a1a62d7a-5173-4caf-8d92-423b6dc0dede # Partition
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6cead47-c085-40f3-975f-ce5f00b44f23
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 6272049f-8eaf-4847-a1fc-52a1f881a7a9
        userCondition: null
fields:
  0e2362da-4175-4b8f-a6f7-d881f03be73e: # Collection Type
    columnSuffix: knlnnrsn
    contentColumnType: string
    fieldGroup: null
    handle: collectionType
    instructions: null
    name: 'Collection Type'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Content Entries'
            -
              - value
              - entries
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Search Results'
            -
              - value
              - search
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Files & Assets'
            -
              - value
              - assets
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Custom Items'
            -
              - value
              - items
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  6fe06c51-450b-43b8-8ff4-88f896048fd2: # Limit
    columnSuffix: zbgxqkrw
    contentColumnType: integer(10)
    fieldGroup: null
    handle: limit
    instructions: 'How many search results to display?'
    name: Limit
    searchable: false
    settings:
      decimals: 0
      defaultValue: 3
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  7b72b671-dcdc-49b2-95cd-44a8e8be7cad: # Background
    columnSuffix: ngczrvyg
    contentColumnType: string
    fieldGroup: null
    handle: bg
    instructions: 'Set the background style behind this block.'
    name: Background
    searchable: false
    settings:
      referenceFile: _blocks/_config/bgContent.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  9a818c17-ad1d-488d-945a-777b6b8b702f: # Content entries
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entries
    instructions: 'Choose existing content entries to feature in this collection'
    name: 'Content entries'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - ad670189-2bcf-47e9-a6ec-7d4673cc6428
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - d3282cfb-d044-4890-b553-9a0b87393027 # SEO / Blog
                      - 8000f4a4-93b8-4f5b-b6b2-b26e6c12e366 # News
                      - 64029a67-3d0c-4cad-8fc6-dc0eec8c112c # Default
                      - e0521335-ccc2-4893-a505-4baacf112dee # Standard (Single Column)
                      - 1da13089-e303-46d0-930f-aefd062df474 # Standard with Sidebar (Two Columns)
                      - 7ba53c7d-afe6-4a6e-9208-a5c0d39b002d # Content Bits
                      - b99a868b-b561-4841-ad62-d4ab5eed5fad # Data
                      - 912adfc2-2bca-47f1-9da2-f1ed5514623c # Topics / Themes
      selectionLabel: 'Choose Entry'
      showSiteMenu: false
      sources:
        - 'section:3721b4d6-42d5-41fc-b6e7-76204b42c91a' # Articles
        - 'section:a52e2b08-2e30-4b00-8784-4104c409d3ed' # FAQs
        - 'section:650e7d1d-63e5-42f9-b3ab-4febfb502723' # Primary Pages
        - 'section:89093e20-515d-4e3c-b4c4-c6733d8ab56f' # Reusable Elements
        - 'section:942cbdfb-d50d-4dcd-9032-4f483562d1dd' # Taxonomies
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  14fd2961-f771-44f1-9b9c-aede9b59a565: # Uploaded assets
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: assets
    instructions: 'Choose the uploaded assets to feature in this collection'
    name: 'Uploaded assets'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - audio
        - code
        - compressed
        - excel
        - json
        - markdown
        - pdf
        - powerpoint
        - text
        - video
        - word
      branchLimit: null
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: '{{- ( object.owner.variants   ?? null  ) ? "products/#{object.owner.type.handle|lower}/" : '''' -}} {{- ( object.owner.product    ?? null  ) ? "products/#{object.owner.product.type.handle|lower}/" : '''' -}} {{- ( object.owner.section    ?? null  ) ? "#{object.owner.section.handle|lower}/" : '''' -}} {{- ( object.owner.parentUri  ?? null  ) ? "#{object.owner.parentUri|replace(''__'','''')}/" : '''' -}} {{object.owner.slug}}'
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose Asset'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  85a35bf9-39c4-475c-9abf-7839f75bb8e6: # Saved searches
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: searches
    instructions: 'Choose the saved search to feature in this collection'
    name: 'Saved searches'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - 2ce107b7-d275-4c31-a7a9-aa356ade2c90
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - 514c0347-c4dd-4b9a-9979-452fc7db526e # Saved Searches
      selectionLabel: null
      showSiteMenu: false
      sources:
        - 'section:942cbdfb-d50d-4dcd-9032-4f483562d1dd' # Taxonomies
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  5347a201-6da8-47ff-bc5b-20a0dc63d44e: # Custom Items
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: 'Create custom content items to feature in this collection'
    name: 'Custom Items'
    searchable: true
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 751688896
      columns:
        __assoc__:
          -
            - 1ddd814c-a3f1-4689-bb67-33d04ad8307a # Headline
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 69c2d7dc-3df8-4df1-a444-d2ae376da00c # Text
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - fd647249-c4ea-4ade-99ab-13f9e53bba3f # Image
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_1_items}}'
      fieldLayout: table
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add Bit'
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  a1a62d7a-5173-4caf-8d92-423b6dc0dede: # Partition
    columnSuffix: vdailebf
    contentColumnType: string
    fieldGroup: null
    handle: spacing
    instructions: 'Adjust whitespace & dividers for this block'
    name: Partition
    searchable: false
    settings:
      referenceFile: _blocks/_config/spacingContent.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  a8dc4c16-ac4a-41eb-b5cb-a83598b8313f: # Search navigation
    columnSuffix: bqiltrrw
    contentColumnType: string
    fieldGroup: null
    handle: pagination
    instructions: 'How to show results beyond the limit?'
    name: 'Search navigation'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - ''
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Endless Scroll'
            -
              - value
              - scroll
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'See All'
            -
              - value
              - all
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Next / Previous'
            -
              - value
              - standard
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  ae3f34db-5fe5-4438-86f0-377cfaebf02a: # Layout
    columnSuffix: ulxtrpcp
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: 'Change content layout/positioning without changing the underlying content'
    name: Layout
    searchable: false
    settings:
      referenceFile: _blocks/_config/layoutCollection.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  b65678be-7ed0-4665-aaaa-bd9d406b60f4: # Variant
    columnSuffix: uzgufcyh
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: 'Adjust the overall style & format of this block layout'
    name: Variant
    searchable: false
    settings:
      referenceFile: _blocks/_config/variantCollection.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  c6677eab-6c78-4ca1-93cd-0faa266d1c45: # Supporting Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: 'Optional text content to introduce or describe the collection item(s)'
    name: 'Supporting Text'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: collection
name: Collection
sortOrder: 5
