field: 0b3f350c-7d90-4fe9-b1f9-739b0696f280 # Page Extras
fieldLayouts:
  a6e27b6b-d867-4d87-9d1a-d7e496741fe1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3d53ca80-b329-484f-bad5-8d4a79f0e3f0 # Fragment
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ac7d686-5712-4326-959a-84eb0b37d142
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 18e1201a-47ad-4963-a452-35ca03bb5290
        userCondition: null
fields:
  3d53ca80-b329-484f-bad5-8d4a79f0e3f0: # Fragment
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: fragment
    instructions: null
    name: Fragment
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - ba7b6cb0-d362-480f-a8b2-b13e842630d0
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - 2dd114a5-aaaa-4e4a-872d-7a61d224b0cb # Body Fragments
                      - 2d27e08b-61f3-47ca-8a0a-e69fa2b1a226 # Sidebar Fragments
      selectionLabel: Choose
      showSiteMenu: false
      sources:
        - 'section:a52e2b08-2e30-4b00-8784-4104c409d3ed' # Reusable Content
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: entranceModal
name: 'Entrance Modal'
sortOrder: 3
