field: 4e35d6a3-a782-43b2-9eef-24ce9981139c # Header Builder
fieldLayouts:
  c9fc3149-8a75-430a-bd41-8bf10e5363c3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 36897794-c1e2-4ca1-ac86-2d3db66ed467 # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3c4b8ea-00df-4b9d-a7b6-6b63fe3f9100
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c1f7dece-b19f-492b-9649-56955cfa6e0a # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3d44078-3d1e-46ac-bb35-9bdbe0ca346d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 5632bd29-d09e-45e2-bf23-3dcddc864796 # Primary Headline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f690bfe-59f3-44ed-8eb9-45fb1085a51e
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 3f22291c-b979-4ffe-b615-df7785c996b8 # Collection
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70d84e50-3398-44e6-b469-2d25a027655f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bf158f34-b564-4314-b990-3d676ed0abb8 # Content Entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48d185e5-f6fa-4b8a-a990-952d5f79d5a1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b54524f7-9081-4ed3-9be8-7efa9ebb3e46 # Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d846f652-24bb-42e3-80c6-21d92f885f3c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bfabb251-636d-4529-a89c-44da8ba61efc # Component
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb97da75-8d00-42e2-bac6-86ecd992f09d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8e370b88-72e3-41b5-bff5-db03cb11a1d1 # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53cccb8f-c8c7-4232-b7b8-e7006a1f8dc2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 1d22a7a4-94bb-4293-bbeb-0af34e916200 # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b54b787-8bb8-45f4-b549-30486c07f1d5
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 88718d0f-b28f-4e0c-98b8-39c904573790 # Interspace
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16220bc6-4f1f-4b0f-a742-2f3785a1f06b
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 3e2acbbc-5433-4e23-9edd-8e1285f0b80b
        userCondition: null
fields:
  1d22a7a4-94bb-4293-bbeb-0af34e916200: # Layout
    columnSuffix: iyxukqlb
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: null
    name: Layout
    searchable: true
    settings:
      configFile: _site/json/layout.attention.header.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  3f22291c-b979-4ffe-b615-df7785c996b8: # Collection
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: collections
    instructions: null
    name: Collection
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: Choose
      showSiteMenu: false
      sources:
        - 'section:2b05c141-a297-4820-ac7d-81e736dbf84b' # Collections
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  8e370b88-72e3-41b5-bff5-db03cb11a1d1: # Copy
    columnSuffix: xgxuohly
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Copy
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  5632bd29-d09e-45e2-bf23-3dcddc864796: # Primary Headline
    columnSuffix: nigfjpqq
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: 'Replaces the page <title> and acts as the default SEO <h1> tag'
    name: 'Primary Headline'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Headline.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: false
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  88718d0f-b28f-4e0c-98b8-39c904573790: # Interspace
    columnSuffix: biyprnqx
    contentColumnType: string
    fieldGroup: null
    handle: interspace
    instructions: null
    name: Interspace
    searchable: true
    settings:
      configFile: _site/json/interspace.header.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  36897794-c1e2-4ca1-ac86-2d3db66ed467: # Variant
    columnSuffix: iehepocn
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: null
    name: Variant
    searchable: true
    settings:
      configFile: _site/json/variant.attention.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  b54524f7-9081-4ed3-9be8-7efa9ebb3e46: # Form
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: form
    instructions: null
    name: Form
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionLabel: 'Choose Form'
      showSiteMenu: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\formie\fields\Forms
  bf158f34-b564-4314-b990-3d676ed0abb8: # Content Entries
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entries
    instructions: null
    name: 'Content Entries'
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: Choose
      showSiteMenu: false
      sources:
        - 'section:3721b4d6-42d5-41fc-b6e7-76204b42c91a' # Articles
        - 'section:3552382f-ca3b-44ba-95f4-2be9f7773370' # Profiles
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  bfabb251-636d-4529-a89c-44da8ba61efc: # Component
    columnSuffix: yqdgwqoj
    contentColumnType: string
    fieldGroup: null
    handle: component
    instructions: null
    name: Component
    searchable: false
    settings:
      configFile: _site/json/variant.attention.component.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  c1f7dece-b19f-492b-9649-56955cfa6e0a: # Theme
    columnSuffix: vpkzjjfz
    contentColumnType: string
    fieldGroup: null
    handle: theme
    instructions: null
    name: Theme
    searchable: true
    settings:
      configFile: _site/json/theme.header.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
handle: attention
name: Attention
sortOrder: 5
