field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Body Builder
fieldLayouts:
  564ddb22-070a-4f59-9191-678a9a6aa04c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: aca4dd0e-619c-4608-97c8-dae08da9e011 # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 734f7302-766c-46fe-878f-6514b24e04e0
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 66dc7ced-9f1e-4501-9772-b9f87634267e # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abd44d6c-ad70-4778-aa11-fef9649382b6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e2cdac24-87bd-4a5b-be66-d991b0323794 # Fragment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf64b0c8-2197-4b35-882d-1efa6ff77c73
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 2cb2fc3a-17b6-4b08-be83-a2b0381ff56d # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 469f5331-dcb3-4447-b8b5-626eb0ca30a4
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bf152e62-fb69-4e45-836d-7546488987e6 # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32fc547d-c5c4-4205-a400-fed243e51d88
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d9dcfac7-2f95-4e7f-8dff-5e8f93eb6332
        userCondition: null
fields:
  2cb2fc3a-17b6-4b08-be83-a2b0381ff56d: # Copy
    columnSuffix: iebrmmvb
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Copy
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  66dc7ced-9f1e-4501-9772-b9f87634267e: # Layout
    columnSuffix: syoyuqvt
    contentColumnType: text
    fieldGroup: null
    handle: layout
    instructions: null
    name: Layout
    searchable: false
    settings:
      columnType: null
      configFile: _site/json/layout.fragment.json
      referenceFile: ''
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  aca4dd0e-619c-4608-97c8-dae08da9e011: # Variant
    columnSuffix: tttooiue
    contentColumnType: text
    fieldGroup: null
    handle: variant
    instructions: null
    name: Variant
    searchable: false
    settings:
      columnType: null
      configFile: _site/json/variant.fragment.json
      referenceFile: ''
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  bf152e62-fb69-4e45-836d-7546488987e6: # Theme
    columnSuffix: nfwtlclo
    contentColumnType: text
    fieldGroup: null
    handle: theme
    instructions: null
    name: Theme
    searchable: false
    settings:
      columnType: null
      configFile: _site/json/theme.json
      referenceFile: ''
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  e2cdac24-87bd-4a5b-be66-d991b0323794: # Fragment
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: fragments
    instructions: null
    name: Fragment
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - 05a92cda-16a4-4aec-8453-4c3d8d5fe816
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - 2dd114a5-aaaa-4e4a-872d-7a61d224b0cb # Body Fragments
      selectionLabel: Choose
      showSiteMenu: false
      sources:
        - 'section:a52e2b08-2e30-4b00-8784-4104c409d3ed' # Reusable Content
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: fragment
name: Fragment
sortOrder: 6
