field: a35a0beb-0cf7-4a2b-9ec3-91e953a18116 # Sidebar Builder
fieldLayouts:
  256ef75b-336f-439e-9295-c8b07b161c32:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e05e823a-7ea6-4c2e-8906-a71f41da91f0 # Fragment
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef39ef4e-5dec-4f34-b153-997f510329f4
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 26f7dca6-d051-4598-8236-34d1403ab36c # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3bd3cbd8-d7b1-4f32-85f6-494bb539ac80
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 01bb381e-2417-4ee8-8473-40d48d27f2e7 # Interspace
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7fba1b15-9a0d-4a3e-87eb-418dcff10d00
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 3911933e-f3f3-4edc-9e3a-26671b2d7fdb
        userCondition: null
fields:
  01bb381e-2417-4ee8-8473-40d48d27f2e7: # Interspace
    columnSuffix: dcntfjtq
    contentColumnType: string
    fieldGroup: null
    handle: interspace
    instructions: 'Control the area between blocks'
    name: Interspace
    searchable: false
    settings:
      referenceFile: _blocks/config/interspaceFragment.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  26f7dca6-d051-4598-8236-34d1403ab36c: # Theme
    columnSuffix: npsqcahg
    contentColumnType: string
    fieldGroup: null
    handle: theme
    instructions: 'Set the background style behind this block.'
    name: Theme
    searchable: false
    settings:
      referenceFile: _blocks/config/themeSidebar.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  e05e823a-7ea6-4c2e-8906-a71f41da91f0: # Fragment
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: fragments
    instructions: null
    name: Fragment
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - e304b4be-1b80-4a65-bad8-fff7faff7fe0
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - 2d27e08b-61f3-47ca-8a0a-e69fa2b1a226 # Sidebar Fragments
      selectionLabel: 'Choose Fragment'
      showSiteMenu: false
      sources:
        - 'section:a52e2b08-2e30-4b00-8784-4104c409d3ed' # Modular Content
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: fragment
name: Fragment
sortOrder: 5
