field: 89834163-b3fe-4c51-9a02-e205e03b9067 # Sidebar Builder
fieldLayouts:
  a2200feb-c994-4ae9-a91b-e387013b5861:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6e078e5b-0730-4dd6-8eea-b2ba88f6ebe7 # Fragment
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3824843-3586-40bd-8b02-15d3a6247de7
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 1a610fca-cc19-4e52-af85-49ab1ed1c26c # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c917bb3-3f17-4813-af0c-b75d252c98ea
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ee1dde07-1de2-45af-a270-440bd55baf11 # Interspace
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0d78b56-bdeb-4b99-9355-613ed8a60ef6
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 6c602257-81c9-460b-b8fc-d8c6c2a202da
        userCondition: null
fields:
  1a610fca-cc19-4e52-af85-49ab1ed1c26c: # Theme
    columnSuffix: nabxaadi
    contentColumnType: string
    fieldGroup: null
    handle: theme
    instructions: null
    name: Theme
    searchable: true
    settings:
      referenceFile: _site/json/theme.fragment.sidebar.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  6e078e5b-0730-4dd6-8eea-b2ba88f6ebe7: # Fragment
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: fragments
    instructions: null
    name: Fragment
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - f0e64893-5625-45ea-a5b7-52df55512330
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - 2d27e08b-61f3-47ca-8a0a-e69fa2b1a226 # Sidebar Fragments
      selectionLabel: 'Choose fragment'
      showSiteMenu: false
      sources:
        - 'section:a52e2b08-2e30-4b00-8784-4104c409d3ed' # Reusable Content
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  ee1dde07-1de2-45af-a270-440bd55baf11: # Interspace
    columnSuffix: dkepybst
    contentColumnType: string
    fieldGroup: null
    handle: interspace
    instructions: null
    name: Interspace
    searchable: true
    settings:
      referenceFile: _site/json/interspace.fragment.sidebar.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
handle: fragment
name: Fragment
sortOrder: 6
