field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
fieldLayouts:
  564ddb22-070a-4f59-9191-678a9a6aa04c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e2cdac24-87bd-4a5b-be66-d991b0323794 # Fragment
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf64b0c8-2197-4b35-882d-1efa6ff77c73
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: bf152e62-fb69-4e45-836d-7546488987e6 # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32fc547d-c5c4-4205-a400-fed243e51d88
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: abf72c9c-cdfc-4765-b71d-a03735da679d # Partition
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41cfa4e2-45bf-495a-8ef7-5181c17669d7
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: d9dcfac7-2f95-4e7f-8dff-5e8f93eb6332
        userCondition: null
fields:
  abf72c9c-cdfc-4765-b71d-a03735da679d: # Partition
    columnSuffix: gslywyag
    contentColumnType: string
    fieldGroup: null
    handle: spacing
    instructions: 'Adjust whitespace & dividers for this block'
    name: Partition
    searchable: false
    settings:
      referenceFile: _blocks/_config/spacingFragment.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  bf152e62-fb69-4e45-836d-7546488987e6: # Background
    columnSuffix: nfwtlclo
    contentColumnType: string
    fieldGroup: null
    handle: bg
    instructions: 'Set the background style behind this block.'
    name: Background
    searchable: false
    settings:
      referenceFile: _blocks/_config/bgFragment.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  e2cdac24-87bd-4a5b-be66-d991b0323794: # Fragment
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: fragments
    instructions: null
    name: Fragment
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - 05a92cda-16a4-4aec-8453-4c3d8d5fe816
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - 174cd975-f457-4998-8bcc-3d25963f9c3b # Content Fragments
                      - 0e3f19ed-abc2-4a3b-887d-5876ad74e994 # Forms
                      - b99a868b-b561-4841-ad62-d4ab5eed5fad # Data
      selectionLabel: 'Choose Fragment'
      showSiteMenu: false
      sources:
        - 'section:89093e20-515d-4e3c-b4c4-c6733d8ab56f' # Reusable Elements
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: fragment
name: 'Reusable Fragment'
sortOrder: 6
