field: 89834163-b3fe-4c51-9a02-e205e03b9067 # Sidebar Builder
fieldLayouts:
  7da578af-b32a-427a-80e2-24c9e17ee1ee:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6b4b70f0-a4b8-4bd1-b45f-62ab122d4d49 # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f1c8b89-5b01-46db-a2e3-395f1b142f6c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 86b1c524-24aa-43bb-8d89-c0105b9ee59d # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef17f818-6ada-4843-8e1e-5ea20ef22f6f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 311d44ff-fb95-46d2-9543-6f7870ae4425 # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18deb0de-88bd-47d8-b20f-8ffd9ba3808e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bc336883-4624-4d26-97f1-7d8cd0d15399 # Feed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea75747c-0984-44db-8887-8dfa74b46473
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 35567f32-2c8d-4cd4-8092-06c1fde0cf1f # Entry
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc46bafc-8560-4752-a40f-c724a3b04093
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e984e441-f7d6-49ce-8f1d-6131ddb57480 # Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cca8b924-62b8-4d57-9570-f276aea3eda3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0d245b48-a5bb-48ae-bb67-b2290fc531c9 # Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e067139-dba6-496c-a06b-d0a6a6a0bf8e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 7dd2f8f9-5066-4cef-a93d-ddfce83dce0f # Component
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 389a8222-f9df-4901-8d91-497250cec1b3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 69de3901-b8b0-4645-a490-7afca5d48622 # Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f12a4dd4-110e-4e3a-a9aa-d941de48d0c2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 016afe08-0081-4f5e-865f-22a360ee839f # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6aaf8b39-55bc-4be3-a6ad-c7cf37dc3d54
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4400a25e-4506-4603-9b56-395e261f730e # Interspace
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce5f4022-3ca0-485d-a51e-d6b82d07d131
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: e1644f57-7c55-4135-ae78-229cbf978bfb
        userCondition: null
fields:
  0d245b48-a5bb-48ae-bb67-b2290fc531c9: # Menu
    columnSuffix: gvxsokxv
    contentColumnType: text
    fieldGroup: null
    handle: menu
    instructions: null
    name: Menu
    searchable: true
    translationKeyFormat: null
    translationMethod: none
    type: verbb\navigation\fields\NavigationField
  6b4b70f0-a4b8-4bd1-b45f-62ab122d4d49: # Layout
    columnSuffix: ikvfrlyv
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: null
    name: Layout
    searchable: true
    settings:
      configFile: _site/json/layout.highlight.sidebar.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  7dd2f8f9-5066-4cef-a93d-ddfce83dce0f: # Component
    columnSuffix: nrkmyvkd
    contentColumnType: string
    fieldGroup: null
    handle: special
    instructions: null
    name: Component
    searchable: false
    settings:
      configFile: _site/json/variant.highlight.special.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  016afe08-0081-4f5e-865f-22a360ee839f: # Theme
    columnSuffix: zabrncdn
    contentColumnType: string
    fieldGroup: null
    handle: theme
    instructions: null
    name: Theme
    searchable: true
    settings:
      configFile: _site/json/theme.sidebar.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  69de3901-b8b0-4645-a490-7afca5d48622: # Code
    columnSuffix: fuwlhznq
    contentColumnType: text
    fieldGroup: null
    handle: code
    instructions: null
    name: Code
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  86b1c524-24aa-43bb-8d89-c0105b9ee59d: # Variant
    columnSuffix: jaxmowcx
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: null
    name: Variant
    searchable: true
    settings:
      configFile: _site/json/variant.highlight.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  311d44ff-fb95-46d2-9543-6f7870ae4425: # Copy
    columnSuffix: lwsvkupl
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Copy
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  4400a25e-4506-4603-9b56-395e261f730e: # Interspace
    columnSuffix: kwehhfxo
    contentColumnType: string
    fieldGroup: null
    handle: interspace
    instructions: null
    name: Interspace
    searchable: true
    settings:
      configFile: _site/json/interspace.sidebar.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  35567f32-2c8d-4cd4-8092-06c1fde0cf1f: # Entry
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entries
    instructions: null
    name: Entry
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: Choose
      showSiteMenu: false
      sources:
        - 'section:3721b4d6-42d5-41fc-b6e7-76204b42c91a' # Articles
        - 'section:3552382f-ca3b-44ba-95f4-2be9f7773370' # Profiles
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  bc336883-4624-4d26-97f1-7d8cd0d15399: # Feed
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: feeds
    instructions: null
    name: Feed
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - c5d3ccd9-7c8e-4b24-bb09-6b80151eaca6
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - 514c0347-c4dd-4b9a-9979-452fc7db526e
      selectionLabel: 'Choose Search'
      showSiteMenu: false
      sources:
        - 'section:942cbdfb-d50d-4dcd-9032-4f483562d1dd' # Topics & Tags
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  e984e441-f7d6-49ce-8f1d-6131ddb57480: # Form
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: form
    instructions: null
    name: Form
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionLabel: 'Choose Form'
      showSiteMenu: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\formie\fields\Forms
handle: highlight
name: Highlight
sortOrder: 5
