field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Body Builder
fieldLayouts:
  a067cac1-ec42-43cc-b56a-f98e3b5b7803:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 05016637-9828-4c3e-94f2-6db02f40308e # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a65ddadc-3316-480c-ad4f-0135500428fe
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 30b5253e-1f74-41f3-b484-e6c82e3210d5 # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ebdf9f9-f485-4eaa-8d3f-3dfbcb3e859a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8200135a-e76a-451e-bcc5-c02be274e589 # Source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3df5bfd8-bd50-4a43-b545-550bdf17c402
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 478bb62e-9b48-4259-a366-23b216633fc6 # Collection
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b517f91-4097-4d60-9953-f67fc188e289
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: dda1fa64-dd45-42b6-8df9-476cbac15152 # Image(s)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 482f9cf0-2950-4e81-a1ee-4dcd8c1a4597
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 1d242d6f-f863-4979-b2af-bb1da5c2aee2 # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25e6f7b0-ef21-41a3-bde5-2f2646a2779e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b8f98eab-bd44-4073-b73b-c5c394a00643 # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db705720-4f45-4505-8b23-dd8e4c9fd2b0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cac765d1-21c1-46d6-addb-0dfd3c50eb9e
        userCondition: null
fields:
  1d242d6f-f863-4979-b2af-bb1da5c2aee2: # Copy
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Copy
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  30b5253e-1f74-41f3-b484-e6c82e3210d5: # Layout
    columnSuffix: payanbyx
    contentColumnType: text
    fieldGroup: null
    handle: layout
    instructions: null
    name: Layout
    searchable: false
    settings:
      columnType: null
      configFile: _site/json/layout.twozone.json
      referenceFile: ''
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  478bb62e-9b48-4259-a366-23b216633fc6: # Collection
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: collections
    instructions: null
    name: Collection
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionLabel: Choose
      showSiteMenu: false
      sources:
        - 'section:2b05c141-a297-4820-ac7d-81e736dbf84b' # Collections
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  05016637-9828-4c3e-94f2-6db02f40308e: # Variant
    columnSuffix: tdkiykfz
    contentColumnType: text
    fieldGroup: null
    handle: variant
    instructions: null
    name: Variant
    searchable: false
    settings:
      columnType: null
      configFile: _site/json/variant.image.json
      referenceFile: ''
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  8200135a-e76a-451e-bcc5-c02be274e589: # Source
    columnSuffix: jsjcgvtd
    contentColumnType: text
    fieldGroup: null
    handle: source
    instructions: null
    name: Source
    searchable: false
    settings:
      columnType: null
      configFile: _site/json/block.sources.json
      referenceFile: ''
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  b8f98eab-bd44-4073-b73b-c5c394a00643: # Theme
    columnSuffix: cpekkbhk
    contentColumnType: text
    fieldGroup: null
    handle: theme
    instructions: null
    name: Theme
    searchable: false
    settings:
      columnType: null
      configFile: _site/json/theme.json
      referenceFile: ''
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  dda1fa64-dd45-42b6-8df9-476cbac15152: # Image(s)
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Image(s)
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
        - json
      branchLimit: null
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: '{{- ( object.owner.variants   ?? null  ) ? "products/#{object.owner.type.handle|lower}/" : '''' -}} {{- ( object.owner.product    ?? null  ) ? "products/#{object.owner.product.type.handle|lower}/" : '''' -}} {{- ( object.owner.section    ?? null  ) ? "#{object.owner.section.handle|lower}/" : '''' -}} {{- ( object.owner.parentUri  ?? null  ) ? "#{object.owner.parentUri|replace(''__'','''')}/" : '''' -}} {{object.owner.slug}}'
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      restrictedLocationSubpath: null
      selectionLabel: Choose
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
