field: 4e35d6a3-a782-43b2-9eef-24ce9981139c # Header Builder
fieldLayouts:
  cb09482c-da2f-4330-8225-b8785fb9ed25:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 32dce9ed-f84d-40e7-b19b-d2771aa76bd1 # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60c1d9ac-88a7-4bba-bca0-363f05326939
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 1853a4db-be6e-457e-8b1e-ce36b7077568 # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbd1b3a5-aa32-473b-a096-506329e73d45
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8143564b-14ab-43e0-9281-9c48f493ee63 # Primary Headline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da44f040-65c1-4118-a96f-ab3867fce191
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: ab34c21b-4d43-41da-8301-8da25a28b912 # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 848f3fb3-f9f9-4070-b16c-8b33797d2afe
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9b0e0463-89fb-4b43-8572-8ac1ae6f54c8 # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4e07ad8-d54e-4934-ad26-b1100f81be89
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 116b2d60-dfda-45af-91ba-a4d2af3e89ca # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b3024e8-6d08-4dc5-9de4-9f18e6cff585
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 25748488-1092-4758-b3e6-e7f7212faae6 # Interspace
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53db43d6-e09b-4ca0-aa34-30614e811799
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 6d0070c7-76fe-47df-9fd1-8d9bd676f8f2
        userCondition: null
fields:
  9b0e0463-89fb-4b43-8572-8ac1ae6f54c8: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Images
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
        - json
      branchLimit: null
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: '{{- ( object.owner.variants   ?? null  ) ? "products/#{object.owner.type.handle|lower}/" : '''' -}} {{- ( object.owner.product    ?? null  ) ? "products/#{object.owner.product.type.handle|lower}/" : '''' -}} {{- ( object.owner.section    ?? null  ) ? "#{object.owner.section.handle|lower}/" : '''' -}} {{- ( object.owner.parentUri  ?? null  ) ? "#{object.owner.parentUri|replace(''__'','''')}/" : '''' -}} {{object.owner.slug}}'
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose Image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  32dce9ed-f84d-40e7-b19b-d2771aa76bd1: # Layout
    columnSuffix: xdsmpaxo
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: null
    name: Layout
    searchable: true
    settings:
      referenceFile: _blocks/config/layout.image.header.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  116b2d60-dfda-45af-91ba-a4d2af3e89ca: # Theme
    columnSuffix: hohpobvj
    contentColumnType: string
    fieldGroup: null
    handle: theme
    instructions: null
    name: Theme
    searchable: true
    settings:
      referenceFile: _blocks/config/theme.header.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  1853a4db-be6e-457e-8b1e-ce36b7077568: # Variant
    columnSuffix: rqbwprsx
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: null
    name: Variant
    searchable: true
    settings:
      referenceFile: _blocks/config/variant.image.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  8143564b-14ab-43e0-9281-9c48f493ee63: # Primary Headline
    columnSuffix: zkkfpekw
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: 'Replaces the page <title> and acts as the default SEO <h1> tag'
    name: 'Primary Headline'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Headline.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: false
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  25748488-1092-4758-b3e6-e7f7212faae6: # Interspace
    columnSuffix: bgguilkr
    contentColumnType: string
    fieldGroup: null
    handle: interspace
    instructions: null
    name: Interspace
    searchable: true
    settings:
      referenceFile: _blocks/config/interspace.header.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  ab34c21b-4d43-41da-8301-8da25a28b912: # Copy
    columnSuffix: jldqsloe
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Copy
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: SimpleAir.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: image
name: Image
sortOrder: 3
