field: a35a0beb-0cf7-4a2b-9ec3-91e953a18116 # Sidebar Builder
fieldLayouts:
  6a521951-ee4a-490a-93da-631e4286c554:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0554821f-40fc-4bf7-bd90-a3a2581c88ab # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b020226-579d-4e9a-9d09-f019db9c797a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9a98ee26-bff8-4ae4-b942-9a367fca906d # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c88c4f99-e9c4-4edb-ae7b-7a8c8d8f57c8
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4e1fbf94-015b-4a5b-880a-8e7051457536 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b6b12061-1c20-4a22-beb8-139fa8024cfb
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a99de532-088e-484b-94fc-945b766ee947 # Image(s)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 339349c3-d933-493a-ac39-7ead1e90ab9f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 1aa226f6-fbd8-4cb9-94b9-26bca8299a04 # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 91e9064c-7a4f-4ae5-b780-379354f7dd9f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e2490fe0-802e-4be2-8173-d77847a05e26 # Spacers & Dividers
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ebf53c92-59b5-485f-90e0-24feb2144145
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b04167bb-2563-4547-99d7-2f6a3331a57b # Widget
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e714675-b281-46bc-8b74-766940d696df
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 04b77bf4-524c-4e70-8fad-86c4b383525c
        userCondition: null
fields:
  1aa226f6-fbd8-4cb9-94b9-26bca8299a04: # Background
    columnSuffix: qwymistc
    contentColumnType: string
    fieldGroup: null
    handle: bg
    instructions: 'Set the background style behind this block.'
    name: Background
    searchable: false
    settings:
      referenceFile: _blocks/_config/bgSidebar.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  4e1fbf94-015b-4a5b-880a-8e7051457536: # Text
    columnSuffix: tjslxfvc
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  9a98ee26-bff8-4ae4-b942-9a367fca906d: # Variant
    columnSuffix: gasxxjrp
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: null
    name: Variant
    searchable: false
    settings:
      referenceFile: ''
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  0554821f-40fc-4bf7-bd90-a3a2581c88ab: # Layout
    columnSuffix: xzyekbfe
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: 'Change the block layout without changing its underlying content'
    name: Layout
    searchable: false
    settings:
      referenceFile: _blocks/_config/layoutImageFeature.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  a99de532-088e-484b-94fc-945b766ee947: # Image(s)
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Image(s)
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
        - json
      branchLimit: null
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: '{{- ( object.owner.variants   ?? null  ) ? "products/#{object.owner.type.handle|lower}/" : '''' -}} {{- ( object.owner.product    ?? null  ) ? "products/#{object.owner.product.type.handle|lower}/" : '''' -}} {{- ( object.owner.section    ?? null  ) ? "#{object.owner.section.handle|lower}/" : '''' -}} {{- ( object.owner.parentUri  ?? null  ) ? "#{object.owner.parentUri|replace(''__'','''')}/" : '''' -}} {{object.owner.slug}}'
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b04167bb-2563-4547-99d7-2f6a3331a57b: # Widget
    columnSuffix: uhlqqmzz
    contentColumnType: string
    fieldGroup: null
    handle: widget
    instructions: null
    name: Widget
    searchable: false
    settings:
      referenceFile: _blocks/_config/widgets.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  e2490fe0-802e-4be2-8173-d77847a05e26: # Spacers & Dividers
    columnSuffix: tbjdznwk
    contentColumnType: string
    fieldGroup: null
    handle: spacing
    instructions: 'Change spacing & dividers above/below this block.'
    name: 'Spacers & Dividers'
    searchable: false
    settings:
      referenceFile: _blocks/_config/spacingSidebar.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
handle: imageFeature
name: 'Image Feature'
sortOrder: 2
