field: 89834163-b3fe-4c51-9a02-e205e03b9067 # Sidebar Builder
fieldLayouts:
  7f638325-5565-4793-bb09-a59ad9647644:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1aa1599b-4b0c-41aa-bdd3-118ae1985884 # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 044b80de-9410-41be-9c4c-b38f55bff562
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4602be9c-52c5-4352-9a75-9c4115407764 # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3920671c-225b-448a-b1e6-8a01b075a167
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 896fe078-b30d-407c-b479-675c927199b7 # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c5aeef5-84e8-459a-a579-b634de64440f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 7960626b-627f-4ad2-9238-697a9534e0dc # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77351e9a-e2f4-4d5f-8897-4007a84a0e93
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 5fc7b5d1-d8af-42a0-9f24-3c491c58dff8 # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d49f3c7c-d27a-4b73-9756-ca3c66af4bce
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 27afafd1-b38c-460b-954d-5cb2f1685d00 # Interspace
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abce20cc-8559-4af1-9757-86cadac711f7
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: d8e96474-7130-4e96-b2fd-04a7022d7679
        userCondition: null
fields:
  1aa1599b-4b0c-41aa-bdd3-118ae1985884: # Layout
    columnSuffix: aaenbjwq
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: null
    name: Layout
    searchable: true
    settings:
      configFile: _site/json/layout.image.sidebar.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  5fc7b5d1-d8af-42a0-9f24-3c491c58dff8: # Theme
    columnSuffix: omjknpxx
    contentColumnType: string
    fieldGroup: null
    handle: theme
    instructions: null
    name: Theme
    searchable: true
    settings:
      configFile: _site/json/theme.sidebar.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  27afafd1-b38c-460b-954d-5cb2f1685d00: # Interspace
    columnSuffix: vrcpojvg
    contentColumnType: string
    fieldGroup: null
    handle: interspace
    instructions: null
    name: Interspace
    searchable: true
    settings:
      configFile: _site/json/interspace.sidebar.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  896fe078-b30d-407c-b479-675c927199b7: # Copy
    columnSuffix: lcvxkgrp
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Copy
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  4602be9c-52c5-4352-9a75-9c4115407764: # Variant
    columnSuffix: cvcpwhfi
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: null
    name: Variant
    searchable: true
    settings:
      configFile: _site/json/variant.image.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  7960626b-627f-4ad2-9238-697a9534e0dc: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Images
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
        - json
      branchLimit: null
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: '{{- ( object.owner.variants   ?? null  ) ? "products/#{object.owner.type.handle|lower}/" : '''' -}} {{- ( object.owner.product    ?? null  ) ? "products/#{object.owner.product.type.handle|lower}/" : '''' -}} {{- ( object.owner.section    ?? null  ) ? "#{object.owner.section.handle|lower}/" : '''' -}} {{- ( object.owner.parentUri  ?? null  ) ? "#{object.owner.parentUri|replace(''__'','''')}/" : '''' -}} {{object.owner.slug}}'
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose Image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
