field: d05f4009-0b38-4065-a1b1-65221aa65e63 # Header Builder
fieldLayouts:
  95d89b00-d16f-4739-a893-bc7118fdb3e9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 468a14eb-fb24-4d42-85ea-51a108f68949 # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77234ae4-bd4c-458b-8160-c7ce2ce03346
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b1f008b2-9888-4564-baa3-efdc6644ac0e # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1dea3b7e-841a-455b-bdde-0e79c3eeb23a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c1193bb1-b500-4050-8b68-a0a7bee4594f # Headline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 834dbe1f-7223-4c42-8f85-a2d0c90841c6
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: ec26ccd6-8b77-446f-83e4-5a157ab84ee5 # Subhead
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47b29ed0-d72a-4b71-8929-6df841e61907
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 25414516-f079-42de-9891-f9dd403af271 # Image(s)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62df11bc-39f6-447f-9ece-b024dd93def8
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: fb8236c7-dc6f-45c6-b62d-6d6ffaaf1657 # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da21838e-b116-4936-b3a5-42bdd92af0f3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a53977b7-95c0-4ac6-bd66-2547ac6caa22 # Interspace
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7fbfa69-35ec-47dd-a3d7-3e328ea96ae6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 2a64e6bd-a23b-4826-bc19-829c037e6e39 # Widget
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 887aee5f-0935-49c2-a6b9-a2287f9cf273
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 70caaf25-ddf7-4109-b3f1-81e24c4423f5
        userCondition: null
fields:
  2a64e6bd-a23b-4826-bc19-829c037e6e39: # Widget
    columnSuffix: gquevifw
    contentColumnType: string
    fieldGroup: null
    handle: widget
    instructions: 'Add a custom feature to this block.'
    name: Widget
    searchable: false
    settings:
      referenceFile: _blocks/config/widgets.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  468a14eb-fb24-4d42-85ea-51a108f68949: # Layout
    columnSuffix: udmwrcap
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: 'Position & arrange the content'
    name: Layout
    searchable: false
    settings:
      referenceFile: _blocks/config/layoutImage.header.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  25414516-f079-42de-9891-f9dd403af271: # Image(s)
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Image(s)
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
        - json
      branchLimit: null
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: '{{- ( object.owner.variants   ?? null  ) ? "products/#{object.owner.type.handle|lower}/" : '''' -}} {{- ( object.owner.product    ?? null  ) ? "products/#{object.owner.product.type.handle|lower}/" : '''' -}} {{- ( object.owner.section    ?? null  ) ? "#{object.owner.section.handle|lower}/" : '''' -}} {{- ( object.owner.parentUri  ?? null  ) ? "#{object.owner.parentUri|replace(''__'','''')}/" : '''' -}} {{object.owner.slug}}'
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose Image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  a53977b7-95c0-4ac6-bd66-2547ac6caa22: # Interspace
    columnSuffix: xfkxramj
    contentColumnType: string
    fieldGroup: null
    handle: interspace
    instructions: 'Control the area inside the header'
    name: Interspace
    searchable: false
    settings:
      referenceFile: _blocks/config/interspaceHeader.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  b1f008b2-9888-4564-baa3-efdc6644ac0e: # Variant
    columnSuffix: skiheswo
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: 'Adjust the overall style & format of this block layout'
    name: Variant
    searchable: false
    settings:
      referenceFile: _blocks/config/variantImage.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  c1193bb1-b500-4050-8b68-a0a7bee4594f: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: 'Replaces the default page <title> and <h1> tag'
    name: Headline
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Headline.json
      removeEmptyTags: true
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  ec26ccd6-8b77-446f-83e4-5a157ab84ee5: # Subhead
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Subhead
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: SimpleAir.json
      removeEmptyTags: true
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  fb8236c7-dc6f-45c6-b62d-6d6ffaaf1657: # Theme
    columnSuffix: rqyqbtbd
    contentColumnType: string
    fieldGroup: null
    handle: theme
    instructions: 'Set the background style behind this block.'
    name: Theme
    searchable: false
    settings:
      referenceFile: _blocks/config/themeHeader.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
handle: image
name: Image
sortOrder: 2
