field: 0b3f350c-7d90-4fe9-b1f9-739b0696f280 # Page Extras
fieldLayouts:
  b61edb70-07e6-4bed-8351-26640e8060de:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a5e7245d-85fd-4eb2-a1af-93ebbadd17f3 # Code
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4dd17137-f67f-444d-b840-9bc8a55e07cc
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: de24a3ba-4bba-4e37-a851-f2e5d949f3da
        userCondition: null
fields:
  a5e7245d-85fd-4eb2-a1af-93ebbadd17f3: # Code
    columnSuffix: iykckvre
    contentColumnType: text
    fieldGroup: null
    handle: code
    instructions: null
    name: Code
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 1
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: jsEvent
name: 'JS Event'
sortOrder: 4
