field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
fieldLayouts:
  4b0e5059-247d-4ef8-a8a6-3d1c7461be34:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 56c5070f-cf62-458c-9dc1-f775ee6f2380 # Content layout and positioning
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2806c478-4604-42a9-8371-84017a7f9e9a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bf30b8e7-f739-4f32-8795-a8c5b92d92bb # Style variation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f089e894-a7b7-4706-bf4a-c0db12b84567
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 20618b1a-5f20-4479-8fa4-842e4def10c7 # Where are the media files located?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28eb4ea5-c712-4aed-b39c-822ebb6971c7
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: cf8fe7e3-d6b1-4626-bd5f-9816c7b1cd1a # Copy to introduce and support the Media
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc6cb3c0-b5fd-4220-8970-0f845442acd2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: aa5de47f-bd21-4e66-9e6b-93f174062abc # Local media assets
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f037bcf9-aaf4-45cd-90c7-d310d4f4679c
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 8384d65a-1c88-4960-8c6e-7091bf390c9d # External embeds
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63ce160a-6094-4753-ae3d-8feb2ab9fcfd
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: e55d7836-b3e5-49a2-a9bf-afb1e7fd91d9 # Background theme and colours
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5484552-2e33-4296-af9d-2fea3f641d8f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bdb06b40-a3b0-4a5c-a000-82f87c2f70d0 # Area between and around the block
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65929d1c-1f38-46eb-992b-977b1ce68b98
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 06fcfa84-a4b0-40d3-9fa4-5e8e032778cd
        userCondition: null
fields:
  56c5070f-cf62-458c-9dc1-f775ee6f2380: # Content layout and positioning
    columnSuffix: grrnasml
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: null
    name: 'Content layout and positioning'
    searchable: false
    settings:
      referenceFile: _blocks/_config/layoutMedia.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  8384d65a-1c88-4960-8c6e-7091bf390c9d: # External embeds
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: embeds
    instructions: null
    name: 'External embeds'
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1707955543
      columns:
        __assoc__:
          -
            - 6f041ff5-12b3-44d7-8efe-5d70ddc8dbb0 # URL
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 096499a3-2127-49c5-be6c-165653e39d0e # Headline
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - e0c81195-0381-4fd7-a65b-5aca8f093e71 # Summary
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 1239b2c2-2836-44d6-ae4a-a88cf2283493 # Images
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_3_embeds}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: none
      selectionLabel: 'Add media'
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  20618b1a-5f20-4479-8fa4-842e4def10c7: # Where are the media files located?
    columnSuffix: szcmthzq
    contentColumnType: string
    fieldGroup: null
    handle: source
    instructions: null
    name: 'Where are the media files located?'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'External - on site like Youtube or Vimeo'
            -
              - value
              - external
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Locally - as Craft CMS Assets'
            -
              - value
              - local
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  aa5de47f-bd21-4e66-9e6b-93f174062abc: # Local media assets
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: assets
    instructions: null
    name: 'Local media assets'
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - audio
        - code
        - compressed
        - excel
        - json
        - markdown
        - pdf
        - powerpoint
        - video
        - word
      branchLimit: null
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: '{{- ( object.owner.variants   ?? null  ) ? "products/#{object.owner.type.handle|lower}/" : '''' -}} {{- ( object.owner.product    ?? null  ) ? "products/#{object.owner.product.type.handle|lower}/" : '''' -}} {{- ( object.owner.section    ?? null  ) ? "#{object.owner.section.handle|lower}/" : '''' -}} {{- ( object.owner.parentUri  ?? null  ) ? "#{object.owner.parentUri|replace(''__'','''')}/" : '''' -}} {{object.owner.slug}}'
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose media'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  bdb06b40-a3b0-4a5c-a000-82f87c2f70d0: # Area between and around the block
    columnSuffix: lcpsbupz
    contentColumnType: string
    fieldGroup: null
    handle: interspace
    instructions: null
    name: 'Area between and around the block'
    searchable: false
    settings:
      referenceFile: _blocks/_config/interspaceContent.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  bf30b8e7-f739-4f32-8795-a8c5b92d92bb: # Style variation
    columnSuffix: pjiqqqah
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: null
    name: 'Style variation'
    searchable: false
    settings:
      referenceFile: _blocks/_config/variantMedia.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  cf8fe7e3-d6b1-4626-bd5f-9816c7b1cd1a: # Copy to introduce and support the Media
    columnSuffix: lriaudff
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: 'Copy to introduce and support the Media'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  e55d7836-b3e5-49a2-a9bf-afb1e7fd91d9: # Background theme and colours
    columnSuffix: qbjriieh
    contentColumnType: string
    fieldGroup: null
    handle: theme
    instructions: null
    name: 'Background theme and colours'
    searchable: false
    settings:
      referenceFile: _blocks/_config/themeContent.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
handle: media
name: Media
sortOrder: 4
