field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Body Builder
fieldLayouts:
  4b0e5059-247d-4ef8-a8a6-3d1c7461be34:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bf30b8e7-f739-4f32-8795-a8c5b92d92bb # Block Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f089e894-a7b7-4706-bf4a-c0db12b84567
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 56c5070f-cf62-458c-9dc1-f775ee6f2380 # Content Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2806c478-4604-42a9-8371-84017a7f9e9a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 20618b1a-5f20-4479-8fa4-842e4def10c7 # Source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28eb4ea5-c712-4aed-b39c-822ebb6971c7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8d636ebd-27c5-46e0-afe6-b4232eabf2fa # Collection
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc65d03f-00dc-4a09-ba78-27f04945387d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: aa5de47f-bd21-4e66-9e6b-93f174062abc # Local Assets
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f037bcf9-aaf4-45cd-90c7-d310d4f4679c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8384d65a-1c88-4960-8c6e-7091bf390c9d # External Sources
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63ce160a-6094-4753-ae3d-8feb2ab9fcfd
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a3273f9c-b38b-4163-9f60-92174692b499 # Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c75336fe-5160-4a04-acc8-2dd0c2df61c4
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: cf8fe7e3-d6b1-4626-bd5f-9816c7b1cd1a # Primary Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc6cb3c0-b5fd-4220-8970-0f845442acd2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e55d7836-b3e5-49a2-a9bf-afb1e7fd91d9 # Theme & Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5484552-2e33-4296-af9d-2fea3f641d8f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 06fcfa84-a4b0-40d3-9fa4-5e8e032778cd
        userCondition: null
fields:
  8d636ebd-27c5-46e0-afe6-b4232eabf2fa: # Collection
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: collections
    instructions: null
    name: Collection
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionLabel: Choose
      showSiteMenu: false
      sources:
        - 'section:2b05c141-a297-4820-ac7d-81e736dbf84b' # Collections
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  56c5070f-cf62-458c-9dc1-f775ee6f2380: # Content Layout
    columnSuffix: grrnasml
    contentColumnType: text
    fieldGroup: null
    handle: layout
    instructions: null
    name: 'Content Layout'
    searchable: false
    settings:
      columnType: null
      configFile: _config/layout.twozone.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  8384d65a-1c88-4960-8c6e-7091bf390c9d: # External Sources
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: external
    instructions: null
    name: 'External Sources'
    searchable: true
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1840358841
      columns:
        __assoc__:
          -
            - 6f041ff5-12b3-44d7-8efe-5d70ddc8dbb0 # Source URL
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 096499a3-2127-49c5-be6c-165653e39d0e # Headline
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - e0c81195-0381-4fd7-a65b-5aca8f093e71 # Summary
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 1239b2c2-2836-44d6-ae4a-a88cf2283493 # Poster
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_3_external}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: none
      selectionLabel: 'Add URL'
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  20618b1a-5f20-4479-8fa4-842e4def10c7: # Source
    columnSuffix: szcmthzq
    contentColumnType: text
    fieldGroup: null
    handle: source
    instructions: null
    name: Source
    searchable: false
    settings:
      columnType: null
      configFile: _config/block.sources.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  a3273f9c-b38b-4163-9f60-92174692b499: # Code
    columnSuffix: dblnmrly
    contentColumnType: text
    fieldGroup: null
    handle: code
    instructions: null
    name: Code
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 2
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  aa5de47f-bd21-4e66-9e6b-93f174062abc: # Local Assets
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: assets
    instructions: null
    name: 'Local Assets'
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - audio
        - compressed
        - excel
        - json
        - pdf
        - powerpoint
        - video
        - word
      branchLimit: null
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: '{{- ( object.owner.variants   ?? null  ) ? "products/#{object.owner.type.handle|lower}/" : '''' -}} {{- ( object.owner.product    ?? null  ) ? "products/#{object.owner.product.type.handle|lower}/" : '''' -}} {{- ( object.owner.section    ?? null  ) ? "#{object.owner.section.handle|lower}/" : '''' -}} {{- ( object.owner.parentUri  ?? null  ) ? "#{object.owner.parentUri|replace(''__'','''')}/" : '''' -}} {{object.owner.slug}}'
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      restrictedLocationSubpath: null
      selectionLabel: Choose
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  bf30b8e7-f739-4f32-8795-a8c5b92d92bb: # Block Variant
    columnSuffix: pjiqqqah
    contentColumnType: text
    fieldGroup: null
    handle: variant
    instructions: null
    name: 'Block Variant'
    searchable: false
    settings:
      columnType: null
      configFile: _config/block.media.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  cf8fe7e3-d6b1-4626-bd5f-9816c7b1cd1a: # Primary Copy
    columnSuffix: lriaudff
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: 'Primary Copy'
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  e55d7836-b3e5-49a2-a9bf-afb1e7fd91d9: # Theme & Spacing
    columnSuffix: qbjriieh
    contentColumnType: text
    fieldGroup: null
    handle: theme
    instructions: null
    name: 'Theme & Spacing'
    searchable: false
    settings:
      columnType: null
      configFile: _config/theme.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
handle: media
name: 'Media Content'
sortOrder: 3
