field: 0b3f350c-7d90-4fe9-b1f9-739b0696f280 # Page Extras
fieldLayouts:
  3e6af0af-0c0c-4dbc-8667-219dc325f50e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 218fe74b-1f0a-45bc-bed5-7fece20536d3 # Menu
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19e83788-4234-486a-ad29-92bb778b0454
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 5884b887-8412-4a1a-9325-5848a3ce3469
        userCondition: null
fields:
  218fe74b-1f0a-45bc-bed5-7fece20536d3: # Menu
    columnSuffix: kogidldh
    contentColumnType: text
    fieldGroup: null
    handle: menu
    instructions: null
    name: Menu
    searchable: false
    translationKeyFormat: null
    translationMethod: none
    type: verbb\navigation\fields\NavigationField
handle: navigation
name: Navigation
sortOrder: 5
