field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
fieldLayouts:
  4b0e5059-247d-4ef8-a8a6-3d1c7461be34:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 56c5070f-cf62-458c-9dc1-f775ee6f2380 # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2806c478-4604-42a9-8371-84017a7f9e9a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 20618b1a-5f20-4479-8fa4-842e4def10c7 # Asset source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28eb4ea5-c712-4aed-b39c-822ebb6971c7
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: cf8fe7e3-d6b1-4626-bd5f-9816c7b1cd1a # Supporting Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc6cb3c0-b5fd-4220-8970-0f845442acd2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: aa5de47f-bd21-4e66-9e6b-93f174062abc # Local assets
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f037bcf9-aaf4-45cd-90c7-d310d4f4679c
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 9e4fa41f-fd14-4cd9-bc39-6ace1e57fe5c # External assets
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d6508d2-6cce-4cb1-b2ad-af30426626ff
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: e55d7836-b3e5-49a2-a9bf-afb1e7fd91d9 # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5484552-2e33-4296-af9d-2fea3f641d8f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bdb06b40-a3b0-4a5c-a000-82f87c2f70d0 # Partition
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65929d1c-1f38-46eb-992b-977b1ce68b98
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 06fcfa84-a4b0-40d3-9fa4-5e8e032778cd
        userCondition: null
fields:
  9e4fa41f-fd14-4cd9-bc39-6ace1e57fe5c: # External assets
    columnSuffix: uhslrpql
    contentColumnType: text
    fieldGroup: null
    handle: externalUrls
    instructions: 'Paste direct links to 3rd party hosted media (Youtube, Vimeo, etc)'
    name: 'External assets'
    searchable: false
    settings:
      addRowLabel: 'Add External Media'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - URL
                -
                  - handle
                  - url
                -
                  - width
                  - ''
                -
                  - type
                  - url
      defaults: null
      maxRows: null
      minRows: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  56c5070f-cf62-458c-9dc1-f775ee6f2380: # Layout
    columnSuffix: grrnasml
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: 'Change content positioning without changing the underlying content'
    name: Layout
    searchable: false
    settings:
      referenceFile: _blocks/_config/layoutRichMedia.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  20618b1a-5f20-4479-8fa4-842e4def10c7: # Asset source
    columnSuffix: szcmthzq
    contentColumnType: string
    fieldGroup: null
    handle: assetSource
    instructions: null
    name: 'Asset source'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Choose from uploaded assets / files'
            -
              - value
              - localAssets
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Embed external assets by URL'
            -
              - value
              - externalUrls
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  aa5de47f-bd21-4e66-9e6b-93f174062abc: # Local assets
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: assets
    instructions: 'Files uploaded direcrtly to the CMS.'
    name: 'Local assets'
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - audio
        - code
        - compressed
        - excel
        - json
        - markdown
        - pdf
        - powerpoint
        - video
        - word
      branchLimit: null
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: '{{- ( object.owner.variants   ?? null  ) ? "products/#{object.owner.type.handle|lower}/" : '''' -}} {{- ( object.owner.product    ?? null  ) ? "products/#{object.owner.product.type.handle|lower}/" : '''' -}} {{- ( object.owner.section    ?? null  ) ? "#{object.owner.section.handle|lower}/" : '''' -}} {{- ( object.owner.parentUri  ?? null  ) ? "#{object.owner.parentUri|replace(''__'','''')}/" : '''' -}} {{object.owner.slug}}'
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose Media'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  bdb06b40-a3b0-4a5c-a000-82f87c2f70d0: # Partition
    columnSuffix: lcpsbupz
    contentColumnType: string
    fieldGroup: null
    handle: spacing
    instructions: 'Adjust whitespace & dividers for this block'
    name: Partition
    searchable: false
    settings:
      referenceFile: _blocks/_config/spacingContent.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  cf8fe7e3-d6b1-4626-bd5f-9816c7b1cd1a: # Supporting Text
    columnSuffix: lriaudff
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: 'Optional text content to introduce or describe the rich media content'
    name: 'Supporting Text'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  e55d7836-b3e5-49a2-a9bf-afb1e7fd91d9: # Background
    columnSuffix: qbjriieh
    contentColumnType: string
    fieldGroup: null
    handle: bg
    instructions: 'Set the background style behind this block.'
    name: Background
    searchable: false
    settings:
      referenceFile: _blocks/_config/bgContent.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
handle: richMedia
name: 'Rich Media'
sortOrder: 4
