field: d05f4009-0b38-4065-a1b1-65221aa65e63 # Header Builder
fieldLayouts:
  4a46a896-31c8-4705-b7f5-c484fd7002bd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f121e5ad-eddc-485f-8d18-8f74c406c771 # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c2a4e63-e0b9-42d2-9959-51a05c681169
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: de70b474-8e41-4034-8450-229b89760037 # Primary Headline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f59aff54-2470-449c-9cce-71c16a4b64f4
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: ec3f8985-4497-4f86-8396-86135c553080 # Asset source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ace7220-7e4b-4ef6-9770-3a16ffbdf179
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b750d657-987a-41b2-953b-807b6c688a88 # Subtext
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a390413-414b-4734-96be-abec31d6d760
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 17687c83-d165-4736-b0ae-59020efcb749 # Local assets
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c242e2d-dc7e-4b85-be7b-3638b1ceffd3
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: b59e7580-ace7-4006-92f2-1304047e2d68 # External assets
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: acf97ee0-bed7-48c8-9e29-c289c5db47aa
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 87482970-1ffe-4760-a28d-cf986bbb8c72 # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86947ec2-5295-40f3-a934-a32dee77abc9
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 887c7e34-0b1f-40b8-b330-27d660a47d50 # Inner Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97033d36-32f9-4d74-9f9b-da7524ba74dd
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: aebe2498-55fa-4926-8908-8a0bc8d303ba # Widget
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ca869e4-46de-49ea-9f3e-9d3cccc2ad20
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 0c30a478-2b78-42e3-a501-8bf256ff5cb9
        userCondition: null
fields:
  887c7e34-0b1f-40b8-b330-27d660a47d50: # Inner Spacing
    columnSuffix: kqtbfzex
    contentColumnType: string
    fieldGroup: null
    handle: spacing
    instructions: 'Change the spacing & size of this block.'
    name: 'Inner Spacing'
    searchable: false
    settings:
      referenceFile: _blocks/_config/spacingHeader.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  17687c83-d165-4736-b0ae-59020efcb749: # Local assets
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: assets
    instructions: 'Files uploaded direcrtly to the CMS.'
    name: 'Local assets'
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - audio
        - code
        - compressed
        - excel
        - json
        - markdown
        - pdf
        - powerpoint
        - video
        - word
      branchLimit: null
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: '{{- ( object.owner.variants   ?? null  ) ? "products/#{object.owner.type.handle|lower}/" : '''' -}} {{- ( object.owner.product    ?? null  ) ? "products/#{object.owner.product.type.handle|lower}/" : '''' -}} {{- ( object.owner.section    ?? null  ) ? "#{object.owner.section.handle|lower}/" : '''' -}} {{- ( object.owner.parentUri  ?? null  ) ? "#{object.owner.parentUri|replace(''__'','''')}/" : '''' -}} {{object.owner.slug}}'
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose Media'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  87482970-1ffe-4760-a28d-cf986bbb8c72: # Background
    columnSuffix: cyumhlrq
    contentColumnType: string
    fieldGroup: null
    handle: bg
    instructions: 'Set the background style behind this block.'
    name: Background
    searchable: false
    settings:
      referenceFile: _blocks/_config/bgHeader.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  aebe2498-55fa-4926-8908-8a0bc8d303ba: # Widget
    columnSuffix: kjrfytpr
    contentColumnType: string
    fieldGroup: null
    handle: widget
    instructions: 'Add a custom feature to this block.'
    name: Widget
    searchable: false
    settings:
      referenceFile: _blocks/_config/widgets.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  b59e7580-ace7-4006-92f2-1304047e2d68: # External assets
    columnSuffix: xctthixn
    contentColumnType: text
    fieldGroup: null
    handle: externalUrls
    instructions: 'Paste direct links to 3rd party hosted media (Youtube, Vimeo, etc)'
    name: 'External assets'
    searchable: false
    settings:
      addRowLabel: 'Add External Media'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - URL
                -
                  - handle
                  - url
                -
                  - width
                  - ''
                -
                  - type
                  - url
      defaults: null
      maxRows: null
      minRows: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  b750d657-987a-41b2-953b-807b6c688a88: # Subtext
    columnSuffix: ijcdahuf
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: 'Anything important to be said above the body copy (optional)'
    name: Subtext
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: SimpleAir.json
      removeEmptyTags: true
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  de70b474-8e41-4034-8450-229b89760037: # Primary Headline
    columnSuffix: gmdbuezd
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: 'Primary Headline'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Headline.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  ec3f8985-4497-4f86-8396-86135c553080: # Asset source
    columnSuffix: ttjtitbq
    contentColumnType: string
    fieldGroup: null
    handle: assetSource
    instructions: null
    name: 'Asset source'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Choose from uploaded assets / files'
            -
              - value
              - localAssets
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Embed external assets by URL'
            -
              - value
              - externalUrls
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  f121e5ad-eddc-485f-8d18-8f74c406c771: # Layout
    columnSuffix: lkocjylo
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: 'Change content positioning without changing the underlying content'
    name: Layout
    searchable: false
    settings:
      referenceFile: _blocks/_config/layoutRichMedia.header.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
handle: richMedia
name: 'Media Header'
sortOrder: 3
