field: 4e35d6a3-a782-43b2-9eef-24ce9981139c # Header Builder
fieldLayouts:
  c9fc3149-8a75-430a-bd41-8bf10e5363c3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1d22a7a4-94bb-4293-bbeb-0af34e916200 # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b54b787-8bb8-45f4-b549-30486c07f1d5
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 36897794-c1e2-4ca1-ac86-2d3db66ed467 # Element
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3c4b8ea-00df-4b9d-a7b6-6b63fe3f9100
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 5632bd29-d09e-45e2-bf23-3dcddc864796 # Headline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f690bfe-59f3-44ed-8eb9-45fb1085a51e
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 3f22291c-b979-4ffe-b615-df7785c996b8 # Feed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70d84e50-3398-44e6-b469-2d25a027655f
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: b54524f7-9081-4ed3-9be8-7efa9ebb3e46 # Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d846f652-24bb-42e3-80c6-21d92f885f3c
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 9fb3a646-055f-4fa2-8287-56c9e9287cf9 # Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20798cfb-0586-42ba-a384-7b2a2ac54c4a
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: f3990ba1-e658-47ab-b64a-0b6d14610084 # Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a016f36-3070-4dec-9169-ae01cf1b5305
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 8e370b88-72e3-41b5-bff5-db03cb11a1d1 # Supporting Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53cccb8f-c8c7-4232-b7b8-e7006a1f8dc2
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: c1f7dece-b19f-492b-9649-56955cfa6e0a # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3d44078-3d1e-46ac-bb35-9bdbe0ca346d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 88718d0f-b28f-4e0c-98b8-39c904573790 # Interspace
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16220bc6-4f1f-4b0f-a742-2f3785a1f06b
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 3e2acbbc-5433-4e23-9edd-8e1285f0b80b
        userCondition: null
fields:
  1d22a7a4-94bb-4293-bbeb-0af34e916200: # Layout
    columnSuffix: iyxukqlb
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: null
    name: Layout
    searchable: true
    settings:
      referenceFile: _blocks/config/layout.special.header.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  3f22291c-b979-4ffe-b615-df7785c996b8: # Feed
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: feeds
    instructions: null
    name: Feed
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - b5bfd882-d7c4-41a1-876d-4af2f8f569e0
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - 514c0347-c4dd-4b9a-9979-452fc7db526e # Content Feeds
      selectionLabel: 'Choose Search'
      showSiteMenu: false
      sources:
        - 'section:942cbdfb-d50d-4dcd-9032-4f483562d1dd' # Taxonomies
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  8e370b88-72e3-41b5-bff5-db03cb11a1d1: # Supporting Copy
    columnSuffix: xgxuohly
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: 'Supporting Copy'
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  9fb3a646-055f-4fa2-8287-56c9e9287cf9: # Menu
    columnSuffix: kuqvcheh
    contentColumnType: text
    fieldGroup: null
    handle: menu
    instructions: null
    name: Menu
    searchable: true
    translationKeyFormat: null
    translationMethod: none
    type: verbb\navigation\fields\NavigationField
  5632bd29-d09e-45e2-bf23-3dcddc864796: # Headline
    columnSuffix: nigfjpqq
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: 'Replaces the page <title> and acts as the default SEO <h1> tag'
    name: Headline
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Headline.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: false
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  88718d0f-b28f-4e0c-98b8-39c904573790: # Interspace
    columnSuffix: biyprnqx
    contentColumnType: string
    fieldGroup: null
    handle: interspace
    instructions: null
    name: Interspace
    searchable: true
    settings:
      referenceFile: _blocks/config/interspace.header.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  36897794-c1e2-4ca1-ac86-2d3db66ed467: # Element
    columnSuffix: iehepocn
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: null
    name: Element
    searchable: true
    settings:
      referenceFile: _blocks/config/variant.special.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  b54524f7-9081-4ed3-9be8-7efa9ebb3e46: # Form
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: form
    instructions: null
    name: Form
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionLabel: 'Choose Form'
      showSiteMenu: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\formie\fields\Forms
  c1f7dece-b19f-492b-9649-56955cfa6e0a: # Theme
    columnSuffix: vpkzjjfz
    contentColumnType: string
    fieldGroup: null
    handle: theme
    instructions: null
    name: Theme
    searchable: true
    settings:
      referenceFile: _blocks/config/theme.header.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  f3990ba1-e658-47ab-b64a-0b6d14610084: # Code
    columnSuffix: snfflnwn
    contentColumnType: text
    fieldGroup: null
    handle: code
    instructions: null
    name: Code
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: special
name: Special
sortOrder: 6
