field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
fieldLayouts:
  b140a9b2-9811-44ea-82e0-e32fa3582bd8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ed9bfc64-1a0b-4a1d-9b9d-8563510c5d9d # Content layout and positioning
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f98e343-13ef-42be-aa7e-6b7a35b1ddd1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b7ec333d-193c-4bfe-b1c2-637e039f302d # Choose element
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26724913-ce96-4be7-b2f5-86dc5ffff9eb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: adc05109-eaa7-4f80-b156-5b250a28e878 # Content feed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ecb71c9-cf08-4a15-a9cc-6560a4a97919
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ca0addca-320c-4b2c-94c4-f063b00c270a # Formie form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b700b263-06f3-4225-b41a-4228bb12245a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: cbe5ac85-220c-41d2-b80f-6b2f4b4635c3 # Navigation menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c4a4aca-574b-4dea-9af7-ae7e9d393d6f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e509399b-03f5-43c0-98b1-23b9d3a0f27b # Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e57703b-8a6c-401f-923c-446ad7213def
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4e6dab12-ff70-4db1-9095-aec90d712602 # Copy to introduce and support the Element
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c6b1041-1de6-465d-af7e-5d2c49b231cd
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8ecf45da-7553-48ac-b52d-a45f8bc90317 # Background theme and colours
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fe5567a-e450-4f98-93fe-f5daa278c6e6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 846fcb98-b56b-479d-9d99-3502ed63ef09 # Area between and around the block
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56853d75-f63f-42d2-be02-559aff395542
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 4e479aee-581c-4e9e-9c85-c891dca6fd51
        userCondition: null
fields:
  4e6dab12-ff70-4db1-9095-aec90d712602: # Copy to introduce and support the Element
    columnSuffix: wwmudfrl
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: 'Copy to introduce and support the Element'
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  8ecf45da-7553-48ac-b52d-a45f8bc90317: # Background theme and colours
    columnSuffix: sbrwrmrk
    contentColumnType: string
    fieldGroup: null
    handle: theme
    instructions: null
    name: 'Background theme and colours'
    searchable: false
    settings:
      referenceFile: _blocks/_config/themeContent.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  846fcb98-b56b-479d-9d99-3502ed63ef09: # Area between and around the block
    columnSuffix: svjbxtmy
    contentColumnType: string
    fieldGroup: null
    handle: interspace
    instructions: null
    name: 'Area between and around the block'
    searchable: false
    settings:
      referenceFile: _blocks/_config/interspaceContent.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  adc05109-eaa7-4f80-b156-5b250a28e878: # Content feed
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: feeds
    instructions: null
    name: 'Content feed'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - 8ac0c4bd-e425-4d70-bf38-6b614cf5e8d7
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - 514c0347-c4dd-4b9a-9979-452fc7db526e # Content Feeds
      selectionLabel: 'Choose Search'
      showSiteMenu: false
      sources:
        - 'section:942cbdfb-d50d-4dcd-9032-4f483562d1dd' # Taxonomies
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  b7ec333d-193c-4bfe-b1c2-637e039f302d: # Choose element
    columnSuffix: fvriqqes
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: null
    name: 'Choose element'
    searchable: false
    settings:
      referenceFile: _blocks/_config/variantSpecial.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  ca0addca-320c-4b2c-94c4-f063b00c270a: # Formie form
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: form
    instructions: null
    name: 'Formie form'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionLabel: 'Choose Form'
      showSiteMenu: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\formie\fields\Forms
  cbe5ac85-220c-41d2-b80f-6b2f4b4635c3: # Navigation menu
    columnSuffix: czuybujj
    contentColumnType: text
    fieldGroup: null
    handle: menu
    instructions: null
    name: 'Navigation menu'
    searchable: false
    translationKeyFormat: null
    translationMethod: none
    type: verbb\navigation\fields\NavigationField
  e509399b-03f5-43c0-98b1-23b9d3a0f27b: # Code
    columnSuffix: zbcaudof
    contentColumnType: text
    fieldGroup: null
    handle: code
    instructions: null
    name: Code
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ed9bfc64-1a0b-4a1d-9b9d-8563510c5d9d: # Content layout and positioning
    columnSuffix: htdbqbuc
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: null
    name: 'Content layout and positioning'
    searchable: false
    settings:
      referenceFile: _blocks/_config/layoutSpecial.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
handle: special
name: Special
sortOrder: 7
