field: b09bda91-6d4a-42c4-a824-f3d402ce20e7 # Chunks
fieldLayouts:
  01865706-b1bf-4be6-bced-0738a08097c7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: fa8573f7-ea9b-4f06-8ecd-1b91a778dbd9 # Identifier
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46966d97-b451-4b52-bd32-1f8c52565bc8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ebab35b1-2b82-4883-aa61-9c554557708f # Table
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a01208a5-4ff6-4fee-adf1-0482deb856fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d40f6841-ce5c-4010-b41a-f7d8a1b30c93 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd6c223b-1548-4210-841b-eed3a6f0b114
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 239e475d-18aa-4c25-9330-9f5c18b67919
        userCondition: null
fields:
  d40f6841-ce5c-4010-b41a-f7d8a1b30c93: # Caption
    columnSuffix: ckfsdsda
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: null
    name: Caption
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: SimpleAir.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  ebab35b1-2b82-4883-aa61-9c554557708f: # Table
    columnSuffix: dhajqazy
    contentColumnType: text
    fieldGroup: null
    handle: table
    instructions: null
    name: Table
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'ID #'
                -
                  - handle
                  - id
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Name
                -
                  - handle
                  - name
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col3
            -
              __assoc__:
                -
                  - heading
                  - Status
                -
                  - handle
                  - status
                -
                  - width
                  - ''
                -
                  - type
                  - select
                -
                  - options
                  -
                    -
                      __assoc__:
                        -
                          - label
                          - Available
                        -
                          - value
                          - available
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - Unavailable
                        -
                          - value
                          - unavailable
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - Unknown
                        -
                          - value
                          - unknown
                        -
                          - default
                          - false
          -
            - col4
            -
              __assoc__:
                -
                  - heading
                  - Date
                -
                  - handle
                  - date
                -
                  - width
                  - ''
                -
                  - type
                  - date
      defaults: null
      maxRows: null
      minRows: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  fa8573f7-ea9b-4f06-8ecd-1b91a778dbd9: # Identifier
    columnSuffix: luuslhqe
    contentColumnType: text
    fieldGroup: null
    handle: identifier
    instructions: null
    name: Identifier
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: table
name: Table
sortOrder: 1
