field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
fieldLayouts:
  030b6d0b-c5dc-459c-b3e0-6e508313ca31:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9d4f8876-987f-46fc-9042-aaf824a7131d # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ab4375b-4552-4f3d-be6c-051e5f50b17d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 26abec17-a1be-4c82-90e1-f6d48f7f4fb0 # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b32b6a9e-c660-4416-8152-855c9b198ffb
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 07a0012a-4bdf-4aaa-8415-bbe06adaf62c # __blank__
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1935261-af10-4a93-9d6e-ac4e9cd50639
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 0dabdba1-b0ed-4220-8bfd-115e5127ee42 # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58085824-b0ac-4ccb-be35-e8f3181916d5
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a7b99dca-7b58-438c-b57e-9d7965c3093b # Interspace
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8819b91b-089d-4d95-b23f-752efb7df8bb
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 17da5594-72ac-4f5d-9596-133476199500
        userCondition: null
fields:
  0dabdba1-b0ed-4220-8bfd-115e5127ee42: # Theme
    columnSuffix: dqtdfrpw
    contentColumnType: string
    fieldGroup: null
    handle: theme
    instructions: null
    name: Theme
    searchable: false
    settings:
      referenceFile: _site/config/theme.content.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  07a0012a-4bdf-4aaa-8415-bbe06adaf62c: # __blank__
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: __blank__
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  9d4f8876-987f-46fc-9042-aaf824a7131d: # Layout
    columnSuffix: qfgjxwao
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: null
    name: Layout
    searchable: false
    settings:
      referenceFile: _site/config/layout.text.content.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  26abec17-a1be-4c82-90e1-f6d48f7f4fb0: # Variant
    columnSuffix: dcsjywnh
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: null
    name: Variant
    searchable: false
    settings:
      referenceFile: _site/config/variant.text.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  a7b99dca-7b58-438c-b57e-9d7965c3093b: # Interspace
    columnSuffix: lhqmhzea
    contentColumnType: string
    fieldGroup: null
    handle: interspace
    instructions: null
    name: Interspace
    searchable: false
    settings:
      referenceFile: _site/config/interspace.content.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
handle: text
name: Text
sortOrder: 1
