field: d05f4009-0b38-4065-a1b1-65221aa65e63 # Header Builder
fieldLayouts:
  71a6d7a6-25ac-452b-be15-ac1e85ee1f0c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 34c8b184-a3df-4101-9525-d2c4a65aa9cb # Variant layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bcd0b055-368d-4601-a190-ccedeb506394
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d08c5ca6-5020-4ac5-9460-c831d0921585 # Hero title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9097578-15ac-44ef-87fd-cc84292d97e2
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 6bd61b45-415d-4702-8b93-c734e25ed41e # Headnote
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0312ee83-431f-46df-8213-cda6f2af4ed2
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: ea2610d5-eecb-4d99-916e-90ce7e2c2bbc # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78543238-2420-49c8-b9c8-9c94fb98ce92
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bfcd0468-97ee-40dd-9344-996e63ff7beb # Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77738567-525c-4225-89b5-47b760aa84df
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 7d750c4a-98f2-471f-b70b-27b31afd4974
        userCondition: null
fields:
  6bd61b45-415d-4702-8b93-c734e25ed41e: # Headnote
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: 'Anything important to be said above the body copy (optional)'
    name: Headnote
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: SimpleAir.json
      removeEmptyTags: true
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  34c8b184-a3df-4101-9525-d2c4a65aa9cb: # Variant layout
    columnSuffix: ntqzccqg
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: 'Changes the block layout without changing its underlying content'
    name: 'Variant layout'
    searchable: false
    settings:
      referenceFile: _builders/references/blockText.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  bfcd0468-97ee-40dd-9344-996e63ff7beb: # Spacing
    columnSuffix: gloywvje
    contentColumnType: string
    fieldGroup: null
    handle: spacing
    instructions: 'Change spacing & dividers above/below this block.'
    name: Spacing
    searchable: false
    settings:
      referenceFile: _components/spacers/references/spacingHero.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  d08c5ca6-5020-4ac5-9460-c831d0921585: # Hero title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: 'Replaces the page <title> and acts as the default SEO <h1> tag'
    name: 'Hero title'
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Headline.json
      removeEmptyTags: true
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  ea2610d5-eecb-4d99-916e-90ce7e2c2bbc: # Background
    columnSuffix: unpwravq
    contentColumnType: string
    fieldGroup: null
    handle: bg
    instructions: 'Set the background style behind this block.'
    name: Background
    searchable: false
    settings:
      referenceFile: _components/backgrounds/references/backgroundsHero.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
handle: text
name: Text
sortOrder: 2
