field: a35a0beb-0cf7-4a2b-9ec3-91e953a18116 # Sidebar Builder
fieldLayouts:
  11ac70c8-3f82-4242-a7e6-04387ce9d1c7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 98433f5b-b542-41ff-a0ca-915026fb4455 # Layout Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d2bfba5-3be5-4c1c-a617-dbf656a06bbf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b6689e78-2cda-4120-a5a3-7337cec63b2c # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc8eaf9b-92bf-44e6-8eab-15700aea91ab
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 0553ed4a-8d9c-42be-855a-82fb23a24aac # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd20ca56-f365-43b4-bfab-55fa2f5db314
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 2d9e094a-7b59-4560-841c-138c5391fe7c # Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7fb2e6cb-6236-417c-831b-720e8aa698a6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 5f8fc242-fe03-4416-9cd3-f32841e4b6ca # Widget
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e41ae63-b864-4c85-9e8d-3713412392c5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 964906e7-2633-4e1b-b324-1deefe2b0bb3
        userCondition: null
fields:
  2d9e094a-7b59-4560-841c-138c5391fe7c: # Spacing
    columnSuffix: imzhlgvq
    contentColumnType: string
    fieldGroup: null
    handle: spacing
    instructions: null
    name: Spacing
    searchable: false
    settings:
      referenceFile: _components/spacers/references/spacing.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  5f8fc242-fe03-4416-9cd3-f32841e4b6ca: # Widget
    columnSuffix: vpnhxvtr
    contentColumnType: string
    fieldGroup: null
    handle: widget
    instructions: null
    name: Widget
    searchable: false
    settings:
      referenceFile: _components/widgets/references/widgets.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  0553ed4a-8d9c-42be-855a-82fb23a24aac: # Background
    columnSuffix: yxvtjfiq
    contentColumnType: string
    fieldGroup: null
    handle: bg
    instructions: null
    name: Background
    searchable: false
    settings:
      referenceFile: _components/backgrounds/references/backgrounds.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  98433f5b-b542-41ff-a0ca-915026fb4455: # Layout Variant
    columnSuffix: kvgukfcy
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: null
    name: 'Layout Variant'
    searchable: false
    settings:
      referenceFile: _builders/references/blockSidebarText.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  b6689e78-2cda-4120-a5a3-7337cec63b2c: # Text
    columnSuffix: jnelsrsi
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: text
name: Text
sortOrder: 2
