field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Body Builder
fieldLayouts:
  030b6d0b-c5dc-459c-b3e0-6e508313ca31:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 26abec17-a1be-4c82-90e1-f6d48f7f4fb0 # Block Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b32b6a9e-c660-4416-8152-855c9b198ffb
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9d4f8876-987f-46fc-9042-aaf824a7131d # Content Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ab4375b-4552-4f3d-be6c-051e5f50b17d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 07a0012a-4bdf-4aaa-8415-bbe06adaf62c # Primary Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1935261-af10-4a93-9d6e-ac4e9cd50639
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 1d3033c2-47a1-4245-8f9c-4dfb1365de27 # Secondary Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f37f73a2-fe78-429d-b6de-891535551e00
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8438332e-2695-4b07-9020-50e01cceb79a # Secondary Bit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4454de3c-ed87-4998-856f-007ed6d393ba
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 76524650-0d67-458b-aa17-7f666528b363 # Secondary Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 820ab4b1-5555-4a35-8858-ff2cf28687ce
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 0dabdba1-b0ed-4220-8bfd-115e5127ee42 # Theme & Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58085824-b0ac-4ccb-be35-e8f3181916d5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 17da5594-72ac-4f5d-9596-133476199500
        userCondition: null
fields:
  0dabdba1-b0ed-4220-8bfd-115e5127ee42: # Theme & Spacing
    columnSuffix: dqtdfrpw
    contentColumnType: text
    fieldGroup: null
    handle: theme
    instructions: null
    name: 'Theme & Spacing'
    searchable: false
    settings:
      columnType: null
      configFile: _config/theme.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  1d3033c2-47a1-4245-8f9c-4dfb1365de27: # Secondary Copy
    columnSuffix: epalhtgq
    contentColumnType: text
    fieldGroup: null
    handle: summary
    instructions: null
    name: 'Secondary Copy'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  07a0012a-4bdf-4aaa-8415-bbe06adaf62c: # Primary Copy
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: 'Primary Copy'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  9d4f8876-987f-46fc-9042-aaf824a7131d: # Content Layout
    columnSuffix: qfgjxwao
    contentColumnType: text
    fieldGroup: null
    handle: layout
    instructions: null
    name: 'Content Layout'
    searchable: false
    settings:
      columnType: null
      configFile: _config/layout.twozone.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  26abec17-a1be-4c82-90e1-f6d48f7f4fb0: # Block Variant
    columnSuffix: dcsjywnh
    contentColumnType: text
    fieldGroup: null
    handle: variant
    instructions: null
    name: 'Block Variant'
    searchable: false
    settings:
      columnType: null
      configFile: _config/block.text.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\selectplus\fields\SelectPlusField
  8438332e-2695-4b07-9020-50e01cceb79a: # Secondary Bit
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: bits
    instructions: null
    name: 'Secondary Bit'
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\entries\TypeConditionRule
                  -
                    - uid
                    - b515f0d5-f0ab-4586-9b3b-29364df6b967
                  -
                    - operator
                    - in
                  -
                    - values
                    -
                      - 29ded7b8-e4a1-43ce-b030-eac97433cb97 # Content Bits ★
      selectionLabel: Choose
      showSiteMenu: false
      sources:
        - 'section:a52e2b08-2e30-4b00-8784-4104c409d3ed' # Reusable Content
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  76524650-0d67-458b-aa17-7f666528b363: # Secondary Copy
    columnSuffix: pjitfloq
    contentColumnType: text
    fieldGroup: null
    handle: text2
    instructions: null
    name: 'Secondary Copy'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: text
name: 'Text Content'
sortOrder: 1
