field: 4e35d6a3-a782-43b2-9eef-24ce9981139c # Header Builder
fieldLayouts:
  960faec0-3a5e-49ce-b6bf-c45d4b8c1df9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f7ee617a-aa34-4177-8a64-6d5b73c22307 # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d9fa10db-62fa-4117-b9e3-598a6e237779
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 89ad23cf-644f-448c-acca-40cb82f76c79 # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2462b331-4ae8-48a2-97e0-5e73b79c5009
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e77036ce-5f69-4250-aec4-76f98b0cd9f1 # Headline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e205b9d6-ae24-4907-9a61-183e7ac4d7e5
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 40ab5767-fd8b-4a9c-8db5-1155e19f9d5d # __blank__
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbd9e9b9-e970-4abc-9881-57e40c3ca3b0
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 5c18b32e-4378-443b-8e6f-cae0f58c1966 # __blank__
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f20f7b58-5a8a-496b-b565-34675aabeb0b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 1d99c693-2d2d-4add-a303-b47f06797e0e # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9417f8c6-6bf4-47e4-971d-6b52a99cbc58
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 178db8f8-8bb2-4400-add2-6a5817532c73 # Interspace
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41f62ff0-7493-4b1c-a569-d906fc540c32
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: ce20d342-fbe7-42da-a70e-97a93475ed6b
        userCondition: null
fields:
  1d99c693-2d2d-4add-a303-b47f06797e0e: # Theme
    columnSuffix: sridfyza
    contentColumnType: string
    fieldGroup: null
    handle: theme
    instructions: null
    name: Theme
    searchable: true
    settings:
      referenceFile: _blocks/config/theme.header.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  5c18b32e-4378-443b-8e6f-cae0f58c1966: # __blank__
    columnSuffix: qfwnqpwo
    contentColumnType: text
    fieldGroup: null
    handle: text2
    instructions: null
    name: __blank__
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: SimpleAir.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  40ab5767-fd8b-4a9c-8db5-1155e19f9d5d: # __blank__
    columnSuffix: gnlqmooe
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: __blank__
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: SimpleAir.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  89ad23cf-644f-448c-acca-40cb82f76c79: # Variant
    columnSuffix: hxkmvdzd
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: null
    name: Variant
    searchable: true
    settings:
      referenceFile: _blocks/config/variant.textDouble.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  178db8f8-8bb2-4400-add2-6a5817532c73: # Interspace
    columnSuffix: gtekpffu
    contentColumnType: string
    fieldGroup: null
    handle: interspace
    instructions: null
    name: Interspace
    searchable: true
    settings:
      referenceFile: _blocks/config/interspace.header.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  e77036ce-5f69-4250-aec4-76f98b0cd9f1: # Headline
    columnSuffix: tvlfceyy
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: 'Replaces the page <title> and acts as the default SEO <h1> tag'
    name: Headline
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Headline.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: false
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  f7ee617a-aa34-4177-8a64-6d5b73c22307: # Layout
    columnSuffix: tncfcugh
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: null
    name: Layout
    searchable: true
    settings:
      referenceFile: _blocks/config/layout.textDouble.header.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
handle: textDouble
name: 'Text (Double)'
sortOrder: 2
