columnSuffix: ctnpaqgb
contentColumnType: string
fieldGroup: 3be366bf-8e5e-4f28-8502-7ebf1d83e26e # Reference Fields
handle: contentSource
instructions: null
name: 'Content Source'
searchable: false
settings:
  referenceFile: _site/settings/feed.sources.json
translationKeyFormat: null
translationMethod: none
type: simplicateca\referencefield\fields\Dropdown
