altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  dcb8d7bf-d5f4-472e-aa37-035ff55baf90:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-14T18:41:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ece9e932-ef1a-45ad-8a78-cb8be0eda416
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-14T18:44:13+00:00'
            elementCondition: null
            fieldUid: ec92452d-10f2-4a41-a9ee-bf384facb572 # Topics
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a87d4df-e28f-4e0d-b2bf-464b358a4014
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 37d8176e-9e89-4ead-881d-6bb221f8498b
        userCondition: null
fs: private
handle: confidential
name: Confidential
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: _transforms
