fieldLayouts:
  155d9590-a8a9-44a0-b379-c089f17b9c37:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c38c79bd-37a2-436d-b5b2-425ffbcff512
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition:
              class: craft\elements\conditions\assets\AssetCondition
              conditionRules:
                -
                  class: craft\elements\conditions\assets\FileTypeConditionRule
                  operator: in
                  uid: 6746067f-ecaa-4bcd-b92d-421a65dfe38a
                  values:
                    - audio
                    - captionsSubtitles
                    - code
                    - compressed
                    - excel
                    - image
                    - json
                    - markdown
                    - pdf
                    - powerpoint
                    - video
                    - word
              elementType: craft\elements\Asset
              fieldContext: global
            id: null
            instructions: null
            label: 'Alt text / SEO title'
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: fc671211-d55d-4f5d-b286-051141138624
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e47b95bf-7a74-49e3-afa3-a938bd733ef7 # Summary
            instructions: null
            label: Summary
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8574f116-bb2f-4ed9-9225-f90e2a6756e2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\assets\AssetCondition
              conditionRules:
                -
                  class: craft\elements\conditions\assets\FileTypeConditionRule
                  operator: in
                  uid: f6fcceaf-5241-4e7a-81fe-ace2e5f75ac6
                  values:
                    - audio
                    - code
                    - compressed
                    - excel
                    - json
                    - markdown
                    - pdf
                    - powerpoint
                    - video
                    - word
              elementType: craft\elements\Asset
              fieldContext: global
            fieldUid: adcea45e-bf40-4faf-b0c8-4ce089696971 # Lead Image(s)
            instructions: null
            label: 'Cover image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aea191f8-91fb-4212-9984-9a9e70a24146
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\assets\AssetCondition
              conditionRules:
                -
                  class: craft\elements\conditions\assets\FileTypeConditionRule
                  operator: in
                  uid: 7ba479ee-f825-4f2c-a44b-0ab0a4df9aab
                  values:
                    - audio
                    - code
                    - compressed
                    - excel
                    - json
                    - markdown
                    - pdf
                    - powerpoint
                    - video
                    - word
              elementType: craft\elements\Asset
              fieldContext: global
            fieldUid: 6a1ab78a-ce1d-4e06-944f-7fa172aaa06a # Text
            instructions: 'Transcription -- Embedded Text -- Long Description --etc'
            label: 'Text content'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ebbe2b10-5bc3-49b2-bc1c-9f7f3d3afb96
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 259afe9f-bdf2-48fc-bb4b-23537e764dfa
        userCondition: null
fs: contentAssets
handle: contentAssets
name: Uploads
sortOrder: 0
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
