defaultPlacement: end
enableVersioning: true
handle: alertMessage
name: 'Alert Message'
propagationMethod: all
siteSettings:
  41b193c3-f554-4c48-8c8a-7ac2645f083f: # Main Site
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
