defaultPlacement: end
enableVersioning: true
handle: articles
name: Articles
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Content Layout'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: custom
siteSettings:
  94414f3a-f6f6-40ce-b8ea-c865fc1fc491: # Main Site
    enabledByDefault: true
    hasUrls: true
    template: _content/articles/base
    uriFormat: '{{object.type|kebab}}/{{object.slug}}'
type: channel
