defaultPlacement: end
enableVersioning: true
handle: faqs
name: FAQs
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary content entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: custom
siteSettings:
  94414f3a-f6f6-40ce-b8ea-c865fc1fc491: # Main Site
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
