defaultPlacement: end
enableVersioning: true
handle: pages
name: 'Primary Pages'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Content Layout'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: custom
siteSettings:
  94414f3a-f6f6-40ce-b8ea-c865fc1fc491: # Main Site
    enabledByDefault: true
    hasUrls: true
    template: _site/pages._entry
    uriFormat: '{% import "_site/pages._entry" as e %}{{ e.uri(object) }}'
  e278d4be-81b4-4575-b43f-75291ca49ada: # Alternate
    enabledByDefault: false
    hasUrls: true
    template: _site/pages._entry
    uriFormat: '{% import "_site/pages._entry" as e %}{{ e.uri(object) }}'
structure:
  maxLevels: null
  uid: 0f9bddc9-659f-4907-82a2-028748c7f504
type: structure
