defaultPlacement: end
enableVersioning: true
handle: pages
name: 'Primary Pages'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: custom
siteSettings:
  41b193c3-f554-4c48-8c8a-7ac2645f083f: # Main Site
    enabledByDefault: true
    hasUrls: true
    template: _page
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 0f9bddc9-659f-4907-82a2-028748c7f504
type: structure
