defaultPlacement: end
enableVersioning: true
handle: profiles
name: Profiles
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary content entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: custom
siteSettings:
  94414f3a-f6f6-40ce-b8ea-c865fc1fc491: # Main Site
    enabledByDefault: true
    hasUrls: true
    template: _site/profiles._entry
    uriFormat: '{% import "_site/profiles._entry" as e %}{{ e.uri(object) }}'
type: channel
