defaultPlacement: end
enableVersioning: true
entryTypes:
  - 215f4c77-1c97-456d-ac1a-d390d0f0cd64 # Person
  - 8209c5fd-6e8c-45d3-8dc2-b44a991dc31e # Organization
handle: profiles
maxAuthors: 1
name: Profiles
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary URL'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d34bee8e-bf22-451d-8339-a4342630833d: # Canada
    enabledByDefault: true
    hasUrls: true
    template: _site/profiles._entry
    uriFormat: '{% from ''_site/profiles._entry'' import uri %}{{ uri( object ) }}'
type: channel
