defaultPlacement: end
enableVersioning: true
entryTypes:
  - 40f8a572-f12e-49f2-849d-8fbe3395eb5c # Addon
  - 2508516d-3329-44ec-8518-04f2a29ca3f3 # Embed
  - 1eb561c2-313a-4ea5-9332-dd8effd8eb73 # Bit
  - ff76eb70-820e-4752-b138-daef62692e3f # Builder
handle: reusables
maxAuthors: 1
name: Reusables
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Context Preview'
      -
        - urlFormat
        - '_hub/reusables/{{object.type.handle}}/{{object.slug}}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d34bee8e-bf22-451d-8339-a4342630833d: # Craft CMS
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
