defaultPlacement: end
enableVersioning: true
handle: sitebook
name: Sitebook
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Content Layout'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: custom
siteSettings:
  41b193c3-f554-4c48-8c8a-7ac2645f083f: # Main Site
    enabledByDefault: true
    hasUrls: true
    template: sitebook/_entry
    uriFormat: '{{parent.uri ?? ''sitebook''}}/{{slug}}'
structure:
  maxLevels: null
  uid: d5688cfd-6a2b-4609-bc18-7e1f0c00426f
type: structure
