defaultPlacement: end
enableVersioning: true
handle: taxonomy
name: Taxonomies
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Content Layout'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: custom
siteSettings:
  41b193c3-f554-4c48-8c8a-7ac2645f083f: # Main Site
    enabledByDefault: true
    hasUrls: true
    template: _content/topics/base
    uriFormat: '{{ object.type.handle == ''topic'' ? "topic/#{object.slug}" : null }}'
type: channel
