color: pink
fieldLayouts:
  de714725-614c-4d87-8434-c730268052dc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-11T22:15:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 945ed4a6-cde1-42ec-8fe6-1f83a9c33906
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-11T22:15:15+00:00'
            elementCondition: null
            fieldUid: 31cc93a2-d38f-4943-b7c2-473b72eb69a1 # Subtype
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c852384e-4057-40cf-b3cb-32529cde2883
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-11T22:15:15+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\LineBreak
            uid: 57a23b7d-d563-4c33-a795-c53ff1217290
            userCondition: null
          -
            dateAdded: '2024-10-12T21:45:06+00:00'
            elementCondition: null
            fieldUid: ab7d33f0-3a17-47ea-a6a8-ad94734ee9a2 # Bits
            handle: null
            includeInCards: false
            instructions: null
            label: Content
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f2cac86-f67c-46b8-869c-ef440f9a3590
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-11T22:15:15+00:00'
            elementCondition: null
            template: _hub/cp-note-addons.twig
            type: craft\fieldlayoutelements\Template
            uid: 14660f4e-af96-4639-91d6-2bd103b73b9b
            userCondition: null
            width: 50
        name: Content
        uid: 994027a3-c00f-44b1-b208-22de5afd7a86
        userCondition: null
handle: addon
hasTitleField: true
icon: aperture
name: Addon
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
