color: null
fieldLayouts:
  8ef03de5-4787-4f79-9eb2-d82066c906c5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f8ed0984-48d5-4d3e-8290-0f8331213e81
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4e393d2-e3cd-402c-a300-6f42cc0553c1 # Audio MP3
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0a05cf7-9d45-4c0d-b4e7-ac8d27d8d576
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 31cc93a2-d38f-4943-b7c2-473b72eb69a1 # Variant
            handle: null
            includeInCards: false
            instructions: null
            label: Relation
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1eeee60d-e1e4-421d-9ba2-9358a2653d56
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 335b1087-e2f6-41b1-b7de-f8d4b61d6c1e # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4fdc22e7-f88a-4231-b6a1-61010b828aaf
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: 423388b4-a5b2-4c6c-acb4-d480ba79ee5b
        userCondition: null
handle: audio
hasTitleField: false
icon: microphone-stand
name: 'Audio Resource'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: '{{ object.headline ? object.headline | striptags | trim : object.mp3.one().title ??? null }}'
titleTranslationKeyFormat: ''
titleTranslationMethod: site
