fieldLayouts:
  428ba83c-5ca7-4751-9529-c3d5c77739fc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dd4c06b0-4735-4900-b07d-48ba38231994
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 772247d2-d67e-40f2-a243-6e6eca55c5f5 # Topic/Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76184b30-8fd7-4592-9f15-c8ed69afc161
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: adcea45e-bf40-4faf-b0c8-4ce089696971 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5bf51005-3bb9-412e-adf4-7f150865f2ef
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b1c52a06-4990-43f5-90d3-898a48789556 # Dek
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8eeeea5-3bf1-46eb-8f82-8abc84922946
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            template: _core/craft-ui/instructionsHeader.twig
            type: craft\fieldlayoutelements\Template
            uid: fb18a7d9-1148-4a3d-a5f5-6cb6b8ea2235
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e35d6a3-a782-43b2-9eef-24ce9981139c # Header Builder
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e03de86-7f51-49ee-8aa7-b6643a28236f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _core/craft-ui/instructionsContent.twig
            type: craft\fieldlayoutelements\Template
            uid: c9b202cd-acd4-4b2c-ad50-11492b1cc603
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4fe99b5-7832-4eb2-9833-f551177bb821 # Body Builder
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d767a26-af52-4bce-8587-abff92061600
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _core/craft-ui/matrixConditionalFields.twig
            type: craft\fieldlayoutelements\Template
            uid: 4ac17ff9-5e7e-4a33-8a4d-59ba78173584
            userCondition: null
            width: 100
        name: Content
        uid: 100480a7-38f5-4090-8ea7-6b1e1f466a64
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: decc967b-80dd-4875-ab3f-b6c700b123eb # SEO Settings
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5310ce4e-8b28-4221-a2e6-40b9c7be555f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0b3f350c-7d90-4fe9-b1f9-739b0696f280 # Page Extras
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a1d56e9-0cb5-4c91-9495-130759116428
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 8163b101-7568-4d0b-aed3-9882d54c5ad3
        userCondition: null
handle: blog
hasTitleField: true
name: 'Insights & Ideas'
section: 3721b4d6-42d5-41fc-b6e7-76204b42c91a # Articles
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
