color: null
fieldLayouts:
  0a67d942-3d40-4628-a527-a8d3665fab5f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 857d5f5a-59d1-4272-a64f-71989291cea2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31cc93a2-d38f-4943-b7c2-473b72eb69a1 # Variant
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f4bdd45-c720-4831-8a13-19f8aa9bd1b4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 76ecf304-e477-4478-8bc3-a6b55558f3fd # Organization
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0dde520b-a6e5-4c8a-a0a8-014c4d4f1413
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: df05c6d5-8180-4105-a4e6-1be6fc4aec9d
        userCondition: null
handle: collab
hasTitleField: true
icon: handshake
name: Collab
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
