color: null
fieldLayouts:
  b4475076-e702-46ac-ace4-e855d80c22be:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fc3ada7c-ee60-4eb9-b55c-8c3bd067c9a8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31cc93a2-d38f-4943-b7c2-473b72eb69a1 # Variant
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23fd25d3-7235-4545-b9fa-ea614d8f78a2
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 1fc4d14e-bdf2-4cfa-a95c-64f6dac73d40 # Collections
            handle: null
            includeInCards: true
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3095de2-479d-42ae-98db-13ce2f1f78c5
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 01c13296-4c57-49c0-802a-e980de4d84e0 # Addons
            handle: null
            includeInCards: true
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46859fa9-16bc-4e46-8c6a-399ca7db6ab2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: a407f2a7-a173-4ba8-9b3b-e51abdd706d0
            userCondition: null
          -
            elementCondition: null
            fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Content Layout
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17dcf7bc-37bb-4491-9c1f-f0d4039db57f
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 7487ca3f-f51b-40e9-a538-40ab5b2c4a27 # Text
            handle: null
            includeInCards: true
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5aad56a-3dcd-4e2b-838b-5442567707a8
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 5635a1ac-adca-4a96-816a-7ae1b664bc4d # Block Theme
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6824c328-4e52-4ddf-833b-5fac45cf817d
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: 2e11ef68-53fd-41c4-9396-c451aac88a1c
        userCondition: null
handle: component
hasTitleField: false
icon: gear
name: Component
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
