fieldLayouts:
  9695f657-a967-4281-abbd-1a6de295a795:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bbe2c30f-d0d0-429d-9149-64b82444a42a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 772247d2-d67e-40f2-a243-6e6eca55c5f5 # Topic / Theme / Collection
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70d7aa3e-f408-4581-8c5d-e777d1591a09
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 6a1ab78a-ce1d-4e06-944f-7fa172aaa06a # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8549b9f-cc36-4355-ad85-957581115e06
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: adcea45e-bf40-4faf-b0c8-4ce089696971 # Lead Image(s)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03e46366-3dc4-4652-b9e6-2bc9e235958e
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: ad863afb-06b1-41bf-818d-8f098633c654
        userCondition: null
handle: contentBit
hasTitleField: true
name: 'Content Bits'
section: 89093e20-515d-4e3c-b4c4-c6733d8ab56f # Reusable Elements
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
