fieldLayouts:
  5a4e165b-a74f-4068-a56a-57ae7f9f482f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a35b0ea6-af36-4ee1-9dec-b5d051a64c75
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fde3769d-9be8-400b-a915-9c3c06469466 # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7fad6a1a-7342-4352-85e4-390b112a124c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b1c52a06-4990-43f5-90d3-898a48789556 # Dek
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43ab46a3-9caf-48a2-9bb9-ab7990833ad0
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: f3184e90-d4b9-4cd0-bccd-1f1921a09a80
            userCondition: null
          -
            elementCondition: null
            fieldUid: 8088055c-4494-404b-8adf-8c9e45da9a85 # Content Type
            instructions: null
            label: 'Content Source'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f952607c-f84c-46d7-a096-64ffcbdcfa45
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\referencefield\fields\conditions\ReferenceFieldConditionRule
                  fieldUid: 8088055c-4494-404b-8adf-8c9e45da9a85 # Content Type
                  operator: ni
                  uid: a76bc1ab-c69d-4691-8dcd-0a64c463a3e0
                  values:
                    - rss
                    - siteSearch
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 984098f0-f085-4059-9146-a22742da49f7 # Sort
            instructions: null
            label: 'Sort By'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 934ec1c7-31e1-432b-b021-7153d9d17a05
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\referencefield\fields\conditions\ReferenceFieldConditionRule
                  fieldUid: 8088055c-4494-404b-8adf-8c9e45da9a85 # Content Type
                  operator: ni
                  uid: 9d0766ac-e00a-42ce-9129-de55a931c886
                  values:
                    - rss
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 6788be2a-03be-4a82-8c88-9e8a1af1acf4 # Preset
            instructions: null
            label: 'Starting Search Term'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5fceda29-ab21-4caa-aa25-98c451976116
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\referencefield\fields\conditions\ReferenceFieldConditionRule
                  fieldUid: 8088055c-4494-404b-8adf-8c9e45da9a85 # Content Type
                  operator: ni
                  uid: 648908ae-db25-4aeb-be7b-56181d950c3e
                  values:
                    - rss
                    - taxonomy.topic
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 772247d2-d67e-40f2-a243-6e6eca55c5f5 # Topic/Theme/Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a9167fb-327a-44ff-aef4-4dbe558d9ff6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\referencefield\fields\conditions\ReferenceFieldConditionRule
                  fieldUid: 8088055c-4494-404b-8adf-8c9e45da9a85 # Content Type
                  operator: in
                  uid: 2a59f3fd-2c86-4e1a-9519-d0448ea270e1
                  values:
                    - rss
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: e5d4f510-e52f-4791-afac-46a644f03003 # Source URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef5bfa8f-cf05-4cd2-8290-73d1574efce7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 14d7d858-e4eb-4c44-90bc-a606a5a2372a # Hyperlink
            instructions: 'Does this feed have a dedicated page for displaying all results?'
            label: 'Feed Homepage'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99ed0f88-2a6a-4cd4-a653-eff439acf007
            userCondition: null
            warning: null
            width: 100
        name: Essentials
        uid: 7b3582ca-52c3-4f69-aec4-f49bbc0d6fa0
        userCondition: null
handle: contentFeed
hasTitleField: true
name: 'Content Feeds'
section: 942cbdfb-d50d-4dcd-9032-4f483562d1dd # Taxonomies
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
