fieldLayouts:
  40684536-4ae6-410b-9ab9-ce1f423c9427:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: 'Page Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 47231d35-0018-4377-b46c-ae84f4e46fcc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _components/builders/_ui/instructionsHeader.twig
            type: craft\fieldlayoutelements\Template
            uid: ea61fb96-468b-4427-a0b4-a1b5dbb29752
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: d05f4009-0b38-4065-a1b1-65221aa65e63 # Header Builder
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77db6e21-1b04-4dc7-b055-8b4e14e30ef3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _components/builders/_ui/instructionsContent.twig
            type: craft\fieldlayoutelements\Template
            uid: 0a342393-374b-4c57-8dcc-e08a394b84fd
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90dfabd8-446b-40c7-958c-984a9647211d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _components/builders/_ui/matrixConditionalFields.twig
            type: craft\fieldlayoutelements\Template
            uid: e8450ae2-36ee-4f3b-837c-dd11c1cf4538
            userCondition: null
            width: 100
        name: Content
        uid: 201e19ec-430f-436f-bc75-9985641f2352
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: adcea45e-bf40-4faf-b0c8-4ce089696971 # Feature Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2afd6a8-b5fe-4b5f-8d55-af5c501dcb75
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b1c52a06-4990-43f5-90d3-898a48789556 # Dek
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 373a4f64-b4a5-40fc-a09d-030d18293177
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 772247d2-d67e-40f2-a243-6e6eca55c5f5 # Topic / Theme / Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4125718-7942-4545-8e0a-edb64323c89a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 4201b712-518a-4250-b610-a6c9ad84551b
            userCondition: null
          -
            elementCondition: null
            fieldUid: decc967b-80dd-4875-ab3f-b6c700b123eb # SEO Settings
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0ec0ce3-948d-466a-b62d-152254ed89cd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0b3f350c-7d90-4fe9-b1f9-739b0696f280 # Page Extras
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1186f787-685b-4ee4-a652-56c9f9e3d554
            userCondition: null
            warning: null
            width: 100
        name: 'Page Settings'
        uid: 2b82df5f-5521-4d7c-b079-1432a96c9a75
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: fdb77561-cbd1-4a4e-a2a5-eb559a5361cb # Sitebook
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
