fieldLayouts:
  499c102f-3c43-414d-a040-3058e837b7ca:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ab78efc8-ad58-44d0-b72b-b5c6645e6b74
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: fde3769d-9be8-400b-a915-9c3c06469466 # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b597d9e7-3cd3-44e3-a595-507dae4eb24a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b1c52a06-4990-43f5-90d3-898a48789556 # Dek
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d24d8304-bd2f-4115-8813-2203ab19fb2a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: adcea45e-bf40-4faf-b0c8-4ce089696971 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07ea40c5-f3e1-450f-99f8-d4f480575f36
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8088055c-4494-404b-8adf-8c9e45da9a85 # Content Source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb2cd8c2-36f9-44f9-ab2d-6cfbc8b8d297
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 984098f0-f085-4059-9146-a22742da49f7 # Sort
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 769045a2-8d42-4b92-823e-f942e0b99aed
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 6788be2a-03be-4a82-8c88-9e8a1af1acf4 # Preset
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 549d383a-db19-4213-bf33-66bccf5e3663
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 772247d2-d67e-40f2-a243-6e6eca55c5f5 # Topic/Theme/Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0eae9502-9294-44dd-8c00-e88ef70626a2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e5d4f510-e52f-4791-afac-46a644f03003 # Source URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e42f4d73-2381-4df5-af27-69da8d016f64
            userCondition: null
            warning: null
            width: 50
        name: Essentials
        uid: afdc5fa5-756f-48f4-a69a-9a787254e639
        userCondition: null
handle: dynamic
hasTitleField: true
name: Dynamic
section: 2b05c141-a297-4820-ac7d-81e736dbf84b # Collections
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
