color: null
fieldLayouts:
  645125bd-a9d4-4a89-9473-0b31f120ad4f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0ced76d2-45fd-4a95-98d0-d4aace59627a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 335b1087-e2f6-41b1-b7de-f8d4b61d6c1e # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 896d8ac6-191d-4191-bcc4-172cddd8c259
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8fdbf754-ae65-42c5-ba4b-09de9259cad2 # Source
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9283ceb7-142e-4115-804b-e3918ea8d85e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\selectplus\fields\SelectPlusConditionRule
                  fieldUid: 8fdbf754-ae65-42c5-ba4b-09de9259cad2 # Source
                  layoutElementUid: 9283ceb7-142e-4115-804b-e3918ea8d85e
                  operator: ni
                  uid: b0472ea4-a1a8-4d09-9c58-da55f5301ed6
                  values:
                    - topics
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: ec92452d-10f2-4a41-a9ee-bf384facb572 # Topics & Tags
            handle: null
            includeInCards: false
            instructions: null
            label: 'Related Topics'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3752405c-4e53-4c88-b7f3-c0b365be754f
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\selectplus\fields\SelectPlusConditionRule
                  fieldUid: 8fdbf754-ae65-42c5-ba4b-09de9259cad2 # Source
                  layoutElementUid: 9283ceb7-142e-4115-804b-e3918ea8d85e
                  operator: in
                  uid: 967f5c70-d3e6-49e5-a49a-7eb2a6f581ea
                  values:
                    - articles
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 615b4078-5891-406a-ba93-6eb8e1528924 # Users
            handle: null
            includeInCards: false
            instructions: null
            label: Author
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c3b7dc5-c1e3-4a79-bfff-401a9ec35084
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 13018e87-c248-4884-8a35-03e84d892886
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f3d34d10-7741-40ba-9fae-27d87f771b4d # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ffd1279-df72-47a9-bf95-73628ac0d32c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4b104ed0-4b08-424b-a744-f9bbf418fc2f # Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39f58f4e-1210-4a42-9d1b-65d50521a123
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b54aca1f-5631-4f76-a248-e953c4ada5bd # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32e2c7bd-36af-454f-a9d9-835d55d580eb
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 581b9070-f50c-49a0-91c7-2921437ad0fb # Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc610369-305f-47b3-ae7d-39768425f03a
            userCondition: null
            warning: null
            width: 25
        name: Meta
        uid: 67541a6b-bae9-4471-8b01-40863872301a
        userCondition: null
handle: dynamic
hasTitleField: true
icon: radar
name: 'Dynamic Collection'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
