color: lime
fieldLayouts:
  20f7068f-77f2-4115-a2ad-31f91392a3f8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-12T21:18:22+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 81d42a94-a7c2-4674-94d6-0117fee6cd57
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-12T21:22:38+00:00'
            elementCondition: null
            fieldUid: ec92452d-10f2-4a41-a9ee-bf384facb572 # Topics
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5540661e-419b-4246-8ae1-854cb155f3e8
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-12T21:21:37+00:00'
            elementCondition: null
            fieldUid: 335b1087-e2f6-41b1-b7de-f8d4b61d6c1e # Headline
            handle: question
            includeInCards: false
            instructions: null
            label: Question
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1baa8e65-a1be-4f94-989d-f7119502971e
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-10-12T21:21:37+00:00'
            elementCondition: null
            fieldUid: 2a4489c4-88e2-4c89-a35c-77ee92f225c0 # Outline
            handle: answer
            includeInCards: false
            instructions: null
            label: Answer
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3299d20-95f0-4133-8ddf-0723c5f43a35
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-10-12T21:22:38+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 08850ed1-5cc4-4041-b26a-75e3324d47ba
            userCondition: null
          -
            dateAdded: '2024-10-12T21:22:38+00:00'
            elementCondition: null
            fieldUid: 4b104ed0-4b08-424b-a744-f9bbf418fc2f # Cover Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 364c82c0-2e9f-45a5-b056-88f2f6c7f619
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-12T21:22:38+00:00'
            elementCondition: null
            fieldUid: f3d34d10-7741-40ba-9fae-27d87f771b4d # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd927616-f498-4c60-961a-7c18498aa412
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 43fe26fa-c7bd-49e3-9a7c-89c1ee88bad6
        userCondition: null
handle: faq
hasTitleField: true
icon: circle-question
name: FAQ
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
