color: null
fieldLayouts:
  c78854db-e1e0-457e-81b6-8637252ac031:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ed397e10-39e7-447f-8f93-35eee2d0bc7f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b4753be4-da84-4306-82e8-a9473ca5398f # Body Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a83ec247-8188-46ad-8dd3-fb5acd4caec8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 84e2ea5c-d6e3-44cf-ac8f-207b0fb8c88a
        userCondition: null
handle: fullpage
hasTitleField: true
icon: shutters
name: Fullpage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
