color: null
fieldLayouts:
  4692c3a1-7fdc-4952-ab00-6037ac03f4d4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            template: _sitehub/ui-template-header-builder.twig
            type: craft\fieldlayoutelements\Template
            uid: 2b7c5144-9da7-4067-a9f9-62f4e8cb302e
            userCondition: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: 'Typically: Issue 01, Issue 02, Special Edition, etc.'
            label: 'Issue Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 10419d1c-242d-40db-a147-c4f46aa269d4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 545f1fed-e750-457f-91f5-47b4faf56f85 # Full Title
            handle: null
            includeInCards: false
            instructions: null
            label: 'Full Title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4011c97-b143-4749-87e0-6894e9dde0b2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Header Builder
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94432945-378e-4430-bb6f-1490191df043
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 05628c22-4b9f-4da0-8a38-1ffbbeaae4d9
            userCondition: null
          -
            elementCondition: null
            fieldUid: 7487ca3f-f51b-40e9-a538-40ab5b2c4a27 # Text
            handle: null
            includeInCards: false
            instructions: 'In This Issue, Letter from the Editor, Opening Remarks, etc.'
            label: 'Foreword (Long text)'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d0f50ed-7b5c-48e4-9d7a-49b39a0674bc
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 34184a55-ddcb-4573-8156-20e90806caf3 # Related Resources
            handle: null
            includeInCards: false
            instructions: 'Relationships to Assets & Content'
            label: 'Issue Resources'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8de6d3d-cbea-4f0b-a937-c8d9710059f8
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: e84ac7a8-6b56-4331-9c0d-11a9ba49fee9
            userCondition: null
          -
            elementCondition: null
            fieldUid: f3d34d10-7741-40ba-9fae-27d87f771b4d # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 200f2c54-2472-4eed-b055-4f313a155db4
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4b104ed0-4b08-424b-a744-f9bbf418fc2f # Images
            handle: null
            includeInCards: false
            instructions: null
            label: 'Cover Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6282a36-7162-49bc-965c-ce4bb246931b
            userCondition: null
            warning: null
            width: 50
        name: 'Main Content'
        uid: a6e71f62-164a-414b-8d0f-df5aa74ecfce
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ec92452d-10f2-4a41-a9ee-bf384facb572 # Topics & Tags
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80641756-b854-4402-bb60-e8c433463ada
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 153a25cc-5bbe-4809-85b6-332cdc9e9dc1
            userCondition: null
          -
            elementCondition: null
            template: _sitehub/ui-template-addons.twig
            type: craft\fieldlayoutelements\Template
            uid: cb788170-d0f4-4241-9248-0f6cb59a5b4f
            userCondition: null
            width: 50
          -
            elementCondition: null
            fieldUid: 01c13296-4c57-49c0-802a-e980de4d84e0 # Addons
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 133c8742-dd40-422a-b812-af5a6ca13ceb
            userCondition: null
            warning: null
            width: 50
        name: 'Secondary Content'
        uid: 3ff104a0-fb54-4559-8d45-56c12ea87c18
        userCondition: null
handle: issue
hasTitleField: true
icon: receipt
name: 'Magazine Issue'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
