color: null
fieldLayouts:
  fe862de5-d89b-42a1-ae6f-634da39083c0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 954a40e1-5340-40fd-af3c-bb6da35660df
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 85e153af-481d-4275-9d51-c3378b42e7e1 # Knowledge
            handle: null
            includeInCards: false
            instructions: null
            label: 'Knowledge Base Content'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d865651f-f7b6-4071-8e59-03c4b98ae81f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 31cc93a2-d38f-4943-b7c2-473b72eb69a1 # Variant
            handle: null
            includeInCards: false
            instructions: null
            label: Relation
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d866cab-aca8-47eb-a7cc-5a02b36d2f7e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 335b1087-e2f6-41b1-b7de-f8d4b61d6c1e # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f0b9cba-b575-4f5a-9eaa-4d028ab6b4ec
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: b24f1298-62ac-4de3-9ac3-32e644553bab # Code
            handle: null
            includeInCards: false
            instructions: null
            label: 'Page | Code'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a0dcef6-8352-4e2d-9209-d37dab978b36
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 92d19944-7218-4420-8b15-834452b33751
        userCondition: null
handle: knowledge
hasTitleField: false
icon: shelves
name: 'Knowledge Resource'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: '{{ object.headline ? object.headline | striptags | trim : object.knowledge.one().title ??? null }}'
titleTranslationKeyFormat: ''
titleTranslationMethod: site
