color: null
fieldLayouts:
  0043a478-7bc5-4a6f-b717-de689da18143:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8f8c6d9e-ccae-4474-b5a9-278798c778e9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31cc93a2-d38f-4943-b7c2-473b72eb69a1 # Variant
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36cfdd17-7a79-4f5a-b45f-46ded5796f39
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7487ca3f-f51b-40e9-a538-40ab5b2c4a27 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9526c500-4357-4b56-bef9-d88b8e65cf0b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d8bf6768-4ff5-4727-ac20-12f8f0344542 # Media
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd9863d6-70f6-4b2f-a1bb-98f5cf9bf95b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 408a25d4-998d-45d3-a875-c9038a60f203
        userCondition: null
handle: media
hasTitleField: false
icon: tv-retro
name: Media
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
