fieldLayouts:
  0f1fd293-e76a-4372-9a95-40a53b2e7f90:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 50657399-b0cc-41fb-9bf4-6e65c27ea494
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: e47b95bf-7a74-49e3-afa3-a938bd733ef7 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd45edcf-f590-4152-b072-8eb8d244a340
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 772247d2-d67e-40f2-a243-6e6eca55c5f5 # Topic / Theme / Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba4b3960-86e3-4e6d-9b4a-a33cd4bf723d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0878fe69-0bad-4cb0-97fb-6bd18e7f716a # Stats
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8b8eca0-cb7f-4c17-b2b3-345a9b0b3460
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 87ab58ac-713d-4045-ba53-93b4c1dfa605
        userCondition: null
handle: metric
hasTitleField: true
name: Metrics
section: a52e2b08-2e30-4b00-8784-4104c409d3ed # Modular Content
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
