color: null
fieldLayouts:
  6c1f48bc-ee02-404b-a8b4-bf4e71dc5af4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            template: _sitehub/ui-template-header-builder.twig
            type: craft\fieldlayoutelements\Template
            uid: 6aa6e897-b56c-4388-b1cf-33e7c8ca5e28
            userCondition: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ba7dd751-8636-418a-bfa9-95f884452c1b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 545f1fed-e750-457f-91f5-47b4faf56f85 # Full Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48d96b7c-ca71-4cf5-8c00-d1422d9fc8de
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Header Builder
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84a681eb-456b-41cc-913e-24bf38b22add
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: cd4e6347-1a3f-42b6-9465-76ddc6e3f731
            userCondition: null
          -
            elementCondition: null
            fieldUid: f3d34d10-7741-40ba-9fae-27d87f771b4d # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 973fe5e0-0e7d-47b5-8911-40d904185969
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4b104ed0-4b08-424b-a744-f9bbf418fc2f # Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: efe23f70-334b-4552-b355-276b22e95a34
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 0149c13a-ece1-4810-90cf-9f793377b80c
            userCondition: null
          -
            elementCondition: null
            fieldUid: 29b673a0-177d-4ed0-b1e0-7328e02495e4 # Outbound Links & Accounts
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf210d28-c29a-4695-a986-e1998bb28cd0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec92452d-10f2-4a41-a9ee-bf384facb572 # Topics & Tags
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f02b6dd-f7c4-4884-8544-b9c267c13956
            userCondition: null
            warning: null
            width: 100
        name: 'Primary Content'
        uid: 5797553d-fc94-413e-8054-fdd5e5ccd90c
        userCondition: null
handle: organization
hasTitleField: true
icon: landmark
name: Organization
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
