color: purple
fieldLayouts:
  c78854db-e1e0-457e-81b6-8637252ac031:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-11T16:39:51+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ed397e10-39e7-447f-8f93-35eee2d0bc7f
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-11T16:39:51+00:00'
            elementCondition: null
            fieldUid: ec92452d-10f2-4a41-a9ee-bf384facb572 # Topics
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa90e5bd-112c-42d7-9639-22c09116af46
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-12T21:50:41+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\SectionConditionRule
                  operator: in
                  uid: 0b41be71-e180-4005-9844-ee49185c64e7
                  values:
                    - 4688dcb4-257f-4a94-b8b7-db234f63e0a9 # Landing Pages
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 2a4489c4-88e2-4c89-a35c-77ee92f225c0 # Outline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08feec3b-e544-4463-b9af-a7b9ba141461
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-10-12T21:50:41+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\SectionConditionRule
                  operator: in
                  uid: 63acde7d-d1c1-449d-baee-23e5e1c4bcca
                  values:
                    - 4688dcb4-257f-4a94-b8b7-db234f63e0a9 # Landing Pages
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 04de3988-1519-432d-92a4-e455f30a3afc # Form
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78fff5c1-e747-4603-b81a-84428ea3a83d
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-10-11T16:39:51+00:00'
            elementCondition: null
            template: _hub/cp-note-builder-header.twig
            type: craft\fieldlayoutelements\Template
            uid: fb7bcd4f-a8fe-4688-9dc3-54f1d02efa3a
            userCondition: null
            width: 100
          -
            dateAdded: '2024-10-12T16:09:27+00:00'
            elementCondition: null
            fieldUid: 8e0c5153-844b-4e8d-b9e8-8b6283d97ea7 # Headline + Subheading
            handle: null
            includeInCards: false
            instructions: 'How to use this [field](http://www.field.whatever)'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e695580a-5084-4f0b-8374-c9eddec08a87
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-11T16:39:51+00:00'
            elementCondition: null
            fieldUid: a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Header Builder
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a032eab6-7596-4f92-bd18-4d8fd254c6a9
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-12T16:09:27+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 24a887ad-db60-4c84-96e7-494b7c7956b3
            userCondition: null
          -
            dateAdded: '2024-10-11T16:39:51+00:00'
            elementCondition: null
            template: _hub/cp-note-builder-body.twig
            type: craft\fieldlayoutelements\Template
            uid: 966444fe-f535-4f49-ab04-e680993cbc99
            userCondition: null
            width: 25
          -
            dateAdded: '2024-10-11T16:39:51+00:00'
            elementCondition: null
            fieldUid: b4753be4-da84-4306-82e8-a9473ca5398f # Body Builder
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a83ec247-8188-46ad-8dd3-fb5acd4caec8
            userCondition: null
            warning: null
            width: 75
        name: Primary
        uid: 84e2ea5c-d6e3-44cf-ac8f-207b0fb8c88a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-11T16:39:51+00:00'
            elementCondition: null
            fieldUid: 4b104ed0-4b08-424b-a744-f9bbf418fc2f # Cover Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1feb8506-1993-4113-a1de-1832cc39948f
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-11T16:39:51+00:00'
            elementCondition: null
            fieldUid: f3d34d10-7741-40ba-9fae-27d87f771b4d # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e683c6f-3f9e-472f-9df7-2a7a3b889601
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-12T16:09:27+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 4f2f4df7-6e9a-4c7c-aba7-549eb97882c6
            userCondition: null
          -
            dateAdded: '2024-10-11T16:39:51+00:00'
            elementCondition: null
            template: _hub/cp-note-builder-sidebar.twig
            type: craft\fieldlayoutelements\Template
            uid: 4d9695ec-a8ec-4782-aeaf-44d6cdb8556f
            userCondition: null
            width: 50
          -
            dateAdded: '2024-10-11T16:39:51+00:00'
            elementCondition: null
            fieldUid: a6272176-e780-4d5e-90f2-df0115d1a324 # Sidebar Builder
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e14cdcca-0d93-444d-878b-94feb898b43d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-12T16:09:27+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: f07f2609-83ed-4e87-8906-83292191bbfc
            userCondition: null
          -
            dateAdded: '2024-10-12T16:09:27+00:00'
            elementCondition: null
            template: _hub/cp-note-addons.twig
            type: craft\fieldlayoutelements\Template
            uid: bedd7a92-60b8-494c-848b-133fa95758af
            userCondition: null
            width: 50
          -
            dateAdded: '2024-10-12T16:09:27+00:00'
            elementCondition: null
            fieldUid: 01c13296-4c57-49c0-802a-e980de4d84e0 # Addons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c410e24-3c41-4a7f-885c-0ace14071ce6
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-12T21:46:54+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\SectionConditionRule
                  operator: in
                  uid: 81dc16bc-bbc6-4fe3-a845-c1b03ec81530
                  values:
                    - 4688dcb4-257f-4a94-b8b7-db234f63e0a9 # Landing Pages
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 9c962ad3-9909-48ef-9ab8-74da65a85268 # Articles
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47999015-a538-473d-808a-117f1b0df8f4
            userCondition: null
            warning: null
            width: 100
        name: Secondary
        uid: 2860d157-6bee-4254-a52d-fef4f14c1a64
        userCondition: null
handle: page
hasTitleField: true
icon: table-tree
name: Page
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
