fieldLayouts:
  3dfd712d-559c-4099-9f96-58d7e591e5ff:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 66b19dcc-3c7c-4183-8914-5ef4a921400e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b1c52a06-4990-43f5-90d3-898a48789556 # Dek
            instructions: 'What is this tag used for?'
            label: Purpose
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 407d60a2-fb6d-4f19-bc5e-8ae0d8470053
            userCondition: null
            warning: null
            width: 50
        name: Essentials
        uid: 7d435989-cada-4c87-929c-cb36c4aa1be6
        userCondition: null
handle: privateTag
hasTitleField: true
name: 'Private Tags'
section: 942cbdfb-d50d-4dcd-9032-4f483562d1dd # Taxonomies
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
