color: green
fieldLayouts:
  20a3ddad-623b-4663-964e-e44f50f276ef:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-12T21:22:23+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 43a10213-d07b-4ec1-84ab-ac5a20ef10e5
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-12T21:29:15+00:00'
            elementCondition: null
            fieldUid: ec92452d-10f2-4a41-a9ee-bf384facb572 # Topics
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1149660-9185-44d1-aad5-10395533a185
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-12T21:32:58+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: f02c3559-c8b7-4b82-b472-e0707be1add2
            userCondition: null
          -
            dateAdded: '2024-10-12T21:29:15+00:00'
            elementCondition: null
            fieldUid: 2a4489c4-88e2-4c89-a35c-77ee92f225c0 # Outline
            handle: text
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8319ee6d-44f1-4133-8fd2-1b5ac4d27311
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-10-12T21:31:51+00:00'
            elementCondition: null
            fieldUid: 7fec92fc-c12e-4150-94ff-af029a1b24ca # Richtext
            handle: byline
            includeInCards: false
            instructions: null
            label: Byline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d44df17-6be6-4bfe-976a-bed522e576c3
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-10-12T21:29:15+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: bd52d4b8-bc4f-4d73-a011-340eb1492cd2
            userCondition: null
          -
            dateAdded: '2024-10-12T21:29:15+00:00'
            elementCondition: null
            fieldUid: 4b104ed0-4b08-424b-a744-f9bbf418fc2f # Cover Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47211f2f-f538-4970-952e-fb2f84cb87b6
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-12T21:29:15+00:00'
            elementCondition: null
            fieldUid: f3d34d10-7741-40ba-9fae-27d87f771b4d # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f24e6f3-8d24-4afb-906d-a572b221bf95
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: efbe7a16-c926-44c0-894e-c9325d603e65
        userCondition: null
handle: quote
hasTitleField: true
icon: quotes
name: Quote
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
