fieldLayouts:
  5a4e165b-a74f-4068-a56a-57ae7f9f482f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a35b0ea6-af36-4ee1-9dec-b5d051a64c75
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8088055c-4494-404b-8adf-8c9e45da9a85 # Content Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f952607c-f84c-46d7-a096-64ffcbdcfa45
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\referencefield\fields\conditions\ReferenceFieldConditionRule
                  fieldUid: 8088055c-4494-404b-8adf-8c9e45da9a85 # Content Type
                  operator: in
                  uid: 2a59f3fd-2c86-4e1a-9519-d0448ea270e1
                  values:
                    - rss
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: e5d4f510-e52f-4791-afac-46a644f03003 # Feed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef5bfa8f-cf05-4cd2-8290-73d1574efce7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\referencefield\fields\conditions\ReferenceFieldConditionRule
                  fieldUid: 8088055c-4494-404b-8adf-8c9e45da9a85 # Content Type
                  operator: ni
                  uid: df79d476-63e1-4b1d-a9b3-62869a3ff72f
                  values:
                    - rss
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 984098f0-f085-4059-9146-a22742da49f7 # Sort
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 934ec1c7-31e1-432b-b021-7153d9d17a05
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\referencefield\fields\conditions\ReferenceFieldConditionRule
                  fieldUid: 8088055c-4494-404b-8adf-8c9e45da9a85 # Content Type
                  operator: ni
                  uid: 648908ae-db25-4aeb-be7b-56181d950c3e
                  values:
                    - rss
                    - taxonomy.topic
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 772247d2-d67e-40f2-a243-6e6eca55c5f5 # Topic / Theme / Collection
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a9167fb-327a-44ff-aef4-4dbe558d9ff6
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 7b3582ca-52c3-4f69-aec4-f49bbc0d6fa0
        userCondition: null
handle: searches
hasTitleField: true
name: 'Saved Searches'
section: 942cbdfb-d50d-4dcd-9032-4f483562d1dd # Taxonomies
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
