color: null
fieldLayouts:
  bd9621cf-2d9d-4772-928f-037835444a33:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            template: _sitehub/ui-template-header-builder.twig
            type: craft\fieldlayoutelements\Template
            uid: 6761f756-8dcd-4ba7-b5c8-907766249ee2
            userCondition: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 039e67e6-f9f8-44be-a311-32d9576608dd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 545f1fed-e750-457f-91f5-47b4faf56f85 # Full Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f89af48-12d0-4f72-8a5b-fb9cf7cc11eb
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Header Builder
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7385a34b-079e-4be6-86c9-7a54c18fb97c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 2dc67986-d0e6-4103-b58a-30b247f93ea4
            userCondition: null
          -
            elementCondition: null
            fieldUid: c5da4c05-a571-456d-aa75-00a7802b85f1 # People • Organizations
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09eb3d62-4b96-4e6c-b670-0df64c296c36
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 31cc93a2-d38f-4943-b7c2-473b72eb69a1 # Variant
            handle: null
            includeInCards: false
            instructions: null
            label: Format
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 477f0ed7-57bd-47ee-bec3-945a2e8c040c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: f8861d43-fc51-4397-ade7-1e9740087501
            userCondition: null
          -
            elementCondition: null
            fieldUid: 7487ca3f-f51b-40e9-a538-40ab5b2c4a27 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: Outline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1275feea-fc06-41c0-a7fa-f130482d90fa
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: ec92452d-10f2-4a41-a9ee-bf384facb572 # Topics & Tags
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 820e1910-7591-4769-aab5-3468b026469d
            userCondition: null
            warning: null
            width: 25
        name: 'Primary Content'
        uid: 99820798-0045-473d-a944-5af153c86db5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f3d34d10-7741-40ba-9fae-27d87f771b4d # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a75300e0-654b-475f-b4db-97dcd4621174
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4b104ed0-4b08-424b-a744-f9bbf418fc2f # Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ff10495-bbce-42d0-83cf-22e8cb982205
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 9ee168ce-0fc3-4a47-a5ab-5102182fc9db
            userCondition: null
          -
            elementCondition: null
            fieldUid: 34184a55-ddcb-4573-8156-20e90806caf3 # Related Resources
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88ceb52c-8394-46af-9fb7-3f0be3b20ea7
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 29b673a0-177d-4ed0-b1e0-7328e02495e4 # Outbound Links & Accounts
            handle: null
            includeInCards: false
            instructions: null
            label: 'External Links'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27e42a6a-cd41-434e-9773-fcf5187b9239
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: cb12ec28-5832-4a18-88bc-a35a7a7687ab
            userCondition: null
        name: 'Secondary Content'
        uid: f7a3fe42-5fab-4a52-9773-e587b00172be
        userCondition: null
handle: session
hasTitleField: true
icon: person-chalkboard
name: Session
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
