color: null
fieldLayouts:
  ef80f310-e634-4441-bce7-2fb52df1c73d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c9a2d0ff-e766-487a-b361-efe424d7beb8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cb64d21d-e05c-4212-9f7b-f4379eba5346
        userCondition: null
handle: sidebar
hasTitleField: true
icon: sidebar-flip
name: Sidebar
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
