fieldLayouts:
  1a82b273-bb1c-458c-b9a5-2722aa9e1020:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: 'This is the main page title. It will appear on the page unless you used the header builder.'
            label: 'Page Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: aff7c356-6d38-41f0-8ad6-1611b9d0470f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _blocks/_admin/instructionsHeader.twig
            type: craft\fieldlayoutelements\Template
            uid: a9440325-5030-48ac-8db3-064cc4750400
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: d05f4009-0b38-4065-a1b1-65221aa65e63 # Header Builder
            instructions: 'Use the block below to customize the hero section for this page'
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45d1c2b8-3ae2-4ac7-b698-663d5e301564
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _blocks/_admin/instructionsContent.twig
            type: craft\fieldlayoutelements\Template
            uid: 868120ed-342e-4a60-b979-5bc194680518
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
            instructions: 'Use the blocks below to construct the body of your entry. Each block contains specific settings and content requirements.'
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f1c3647-1a55-497b-a7c2-33cbf90ecae4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _blocks/_admin/matrixConditionalFields.twig
            type: craft\fieldlayoutelements\Template
            uid: 64393159-3e89-4faa-9aaa-11de8dcd8b2a
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0b3f350c-7d90-4fe9-b1f9-739b0696f280 # Page Extras
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e41413ad-49ae-426d-baa8-77dfb45cb48a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7309709a-e27a-4226-a2c1-5685670c4c51
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            template: _blocks/_admin/instructionsSidebar.twig
            type: craft\fieldlayoutelements\Template
            uid: ad4c755b-f0ca-48dc-b0d9-211e845bc0fb
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: a35a0beb-0cf7-4a2b-9ec3-91e953a18116 # Sidebar Builder
            instructions: 'Use the blocks below to construct the sidebar of your entry. Each block contains specific settings and content requirements.'
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6cccab6-cc19-437f-84cc-fcbd912b8ae6
            userCondition: null
            warning: null
            width: 100
        name: Sidebar
        uid: e6f941ab-670b-4aa1-83f6-1ebb29e90282
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: adcea45e-bf40-4faf-b0c8-4ce089696971 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 645515ab-242d-4610-a4e6-2238a3f66628
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b1c52a06-4990-43f5-90d3-898a48789556 # Dek
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d29e982c-a5a6-4cf0-979c-70c6ce0cf0fb
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 772247d2-d67e-40f2-a243-6e6eca55c5f5 # Topic/Theme/Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d61974ce-b568-4fe3-8df6-8c5325cd4f91
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: dd36ddd8-2856-4593-8650-c734f0ff3bc7
            userCondition: null
          -
            elementCondition: null
            fieldUid: decc967b-80dd-4875-ab3f-b6c700b123eb # SEO Settings
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 240f6145-1590-4eca-8a5f-e25901026ae0
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 25183390-3692-4379-9b10-d39ff01ebbbb
        userCondition: null
handle: sidebar
hasTitleField: true
name: 'Standard w/ Sidebar'
section: 650e7d1d-63e5-42f9-b3ab-4febfb502723 # Primary Pages
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
