fieldLayouts:
  40ba85ae-8777-45a0-8a5c-840cb180a30c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1e78c7a2-c40d-442d-b8f1-a78d9649460c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 3def122c-77bc-465f-b54f-4bba4ecfab39 # Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 92ffd67a-c637-4012-adde-93321e4b39dd
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            template: _components/builders/_ui/instructionsSidebar.twig
            type: craft\fieldlayoutelements\Template
            uid: 19f209ca-2fc7-44e8-bb88-184d0ec861dd
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: a35a0beb-0cf7-4a2b-9ec3-91e953a18116 # Sidebar Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7dbc0645-a97e-4573-8cd3-36159a4cba05
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _components/builders/_ui/matrixConditionalFields.twig
            type: craft\fieldlayoutelements\Template
            uid: 283bd601-c3e9-4af4-a981-77e68bee26bc
            userCondition: null
            width: 100
        name: Content
        uid: 3c710580-c853-4064-acc8-b96485b4921e
        userCondition: null
handle: sidebarFragment
hasTitleField: true
name: 'Sidebar Fragments'
section: 89093e20-515d-4e3c-b4c4-c6733d8ab56f # Reusable Elements
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
