fieldLayouts:
  666923c1-1d21-425e-a40e-a6507e45fe23:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f718a7f9-d723-44d6-8a2e-1b8da3f83423
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _blocks/craft-ui/instructionsSidebar.twig
            type: craft\fieldlayoutelements\Template
            uid: 9e863f6d-a200-4a22-aae4-4f7c2a64cf80
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: 89834163-b3fe-4c51-9a02-e205e03b9067 # Sidebar Builder
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b38465d3-874c-42e3-8ee3-2db8c893c53a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _blocks/craft-ui/matrixConditionalFields.twig
            type: craft\fieldlayoutelements\Template
            uid: df217d7f-fc95-4ea7-8c8d-b09b16f897b6
            userCondition: null
            width: 100
        name: Content
        uid: ed917f19-62a0-407d-ba0c-3e71a6a48c61
        userCondition: null
handle: sidebarFragment
hasTitleField: true
name: 'Sidebar Fragments'
section: a52e2b08-2e30-4b00-8784-4104c409d3ed # Modular Content
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 5
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
