fieldLayouts:
  b31791aa-909d-43be-a352-7970cd695247:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: 'This is the main page title. It will appear on the page unless you used the header builder.'
            label: 'Page Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3f9ed9b7-3cde-4499-a7a2-396bf7a3d33b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _blocks/craft-ui/instructionsHeader.twig
            type: craft\fieldlayoutelements\Template
            uid: 706c3a05-0cce-4331-8d53-2c66f752969d
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: d05f4009-0b38-4065-a1b1-65221aa65e63 # Header Builder
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: afef7495-b715-4717-900c-146a33e75450
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _blocks/craft-ui/instructionsContent.twig
            type: craft\fieldlayoutelements\Template
            uid: 1e1b2698-ace8-444b-af5d-e333a70dad96
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3013d139-6ccf-4920-8105-9d74fb779d9c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _blocks/craft-ui/matrixConditionalFields.twig
            type: craft\fieldlayoutelements\Template
            uid: 1d2d5820-d225-4571-aba5-cb8f0f45d81d
            userCondition: null
            width: 100
        name: Content
        uid: 20e7b132-6229-47bf-8c01-9a2142ccfc2b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: adcea45e-bf40-4faf-b0c8-4ce089696971 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da6fc831-aaa6-4d44-a48a-6c7ddd44dbf4
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b1c52a06-4990-43f5-90d3-898a48789556 # Dek
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 179a2beb-2983-434b-b1b1-4f7203ee0206
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 772247d2-d67e-40f2-a243-6e6eca55c5f5 # Topic/Theme/Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d94261f6-2a33-4d40-9720-6f7d626ce8c0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 16570506-b4ba-4946-b860-d261deea643c
            userCondition: null
          -
            elementCondition: null
            fieldUid: decc967b-80dd-4875-ab3f-b6c700b123eb # SEO Settings
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e59f3494-0aa8-479e-b04c-14a5755515e0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0b3f350c-7d90-4fe9-b1f9-739b0696f280 # Page Extras
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f99d4539-f98c-4355-a3c3-39535b52f646
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 9f8c970f-637c-425e-b58c-19deaf4b7a95
        userCondition: null
handle: standard
hasTitleField: true
name: 'Standard (Single Column)'
section: 8c9174b7-2c31-491e-a3f9-0374374c967c # Landing Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
