fieldLayouts:
  0e6296a2-ebef-4158-ba3d-e196af38899e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: 'This is the main page title. It will appear on the page unless you used the header builder.'
            label: 'Page Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7f78bbcb-7f32-477a-ba16-b79baf60d778
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _site/sitehub/craft-ui/instructionsHeader.twig
            type: craft\fieldlayoutelements\Template
            uid: d766d6d4-3d04-465a-b1ae-88f0c0d02827
            userCondition: null
            width: 100
          -
            elementCondition: null
            template: _site/sitehub/craft-ui/instructionsContent.twig
            type: craft\fieldlayoutelements\Template
            uid: 31763d74-d9d5-429f-8fe7-1d8ba7d5f229
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ac47f09-ee20-4f31-93a1-d14442cfdd2f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _site/sitehub/craft-ui/matrixConditionalFields.twig
            type: craft\fieldlayoutelements\Template
            uid: 0aa7ff39-373d-49b2-bfcb-9b428ba0bf6b
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0b3f350c-7d90-4fe9-b1f9-739b0696f280 # Page Extras
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac2c8236-7c0e-4ddf-9043-83152544ab4b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 818faf38-587a-432a-ae15-0223cdae2343
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: adcea45e-bf40-4faf-b0c8-4ce089696971 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc50be8e-c504-4f3f-aa26-ba68f45b4f80
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b1c52a06-4990-43f5-90d3-898a48789556 # Dek
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7777e9e-253d-42bc-92ba-52af6fb6bf4d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 772247d2-d67e-40f2-a243-6e6eca55c5f5 # Topic/Theme/Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7e8b1b6-6e23-4309-8750-e27c23cd78af
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 4d26604f-fbe3-4aba-bf49-40d901789770
            userCondition: null
          -
            elementCondition: null
            fieldUid: decc967b-80dd-4875-ab3f-b6c700b123eb # SEO Settings
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0042a3fc-d4a2-42bd-b6d4-7146ca313311
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: a533ce47-f77f-4d3b-add6-fa261e2823b1
        userCondition: null
handle: standard
hasTitleField: true
name: Standard
section: 650e7d1d-63e5-42f9-b3ab-4febfb502723 # Primary Pages
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
