color: teal
fieldLayouts:
  515bd174-4246-4c42-ad38-10b61c0d63b6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-12T21:57:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a9e2760a-d655-48a8-950d-f2c54f72e0a3
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-12T22:00:58+00:00'
            elementCondition: null
            fieldUid: 4b104ed0-4b08-424b-a744-f9bbf418fc2f # Cover Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3d3fe17-eab3-4ce6-8e67-fca2dca8c5bb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-12T22:00:58+00:00'
            elementCondition: null
            fieldUid: f3d34d10-7741-40ba-9fae-27d87f771b4d # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f99a0a8-4e40-43aa-a855-a7fadfd50685
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b1bd3b82-99f4-4ce4-8bfc-47a8f0e5f883
        userCondition: null
handle: stat
hasTitleField: true
icon: chart-line
name: Stat
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
