color: null
fieldLayouts:
  3a5fcba1-7080-4398-abf6-19311eb4d489:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c56a05a3-8a2a-4dcc-8672-dff79e54ad39
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 335b1087-e2f6-41b1-b7de-f8d4b61d6c1e # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71d7bcce-0916-4208-8fda-32dcd120e8d4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4b104ed0-4b08-424b-a744-f9bbf418fc2f # Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 666635d9-2d5e-458c-9a43-8e47aa26ffb1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d8bf6768-4ff5-4727-ac20-12f8f0344542 # Media
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53b6cf52-bc6c-4834-a2d1-6dc3b95c9e6f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a186d4ae-477e-4b06-868e-add5e8f44b0c # Embeds
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28dc5307-cb18-48c1-bab5-93d2fbc9aa17
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ab7d33f0-3a17-47ea-a6a8-ad94734ee9a2 # Bits
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: feb5d264-2559-4289-a720-ead9625e7187
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f240ce26-8d9d-4668-b18b-73371d5c5211 # Entries
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fed7f0df-9432-4ff6-8679-941a9c14d09f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2ca4add9-ebec-491f-a9b6-b090360c7775
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f3d34d10-7741-40ba-9fae-27d87f771b4d # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0c41cbf-c3de-48e9-809e-b25b7d0b580c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b54aca1f-5631-4f76-a248-e953c4ada5bd # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8a3b334-1d88-4a19-b72a-a831ecb6a97f
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 581b9070-f50c-49a0-91c7-2921437ad0fb # Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 301bd905-1ec9-45bc-b4d2-ae75e1cfa722
            userCondition: null
            warning: null
            width: 25
        name: Meta
        uid: f9901616-135e-431a-9e50-9c2d7523aee6
        userCondition: null
handle: static
hasTitleField: true
icon: list-radio
name: 'Static Collection'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
