fieldLayouts:
  28668593-39e2-476b-8d57-2ce194b7be83:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 991ce889-6703-406a-b564-c679947c81fb
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: fde3769d-9be8-400b-a915-9c3c06469466 # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 379f9355-c6b5-4a17-ba3c-e6a748ec5ae3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b1c52a06-4990-43f5-90d3-898a48789556 # Dek
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b60194f-a1af-41f0-b3d1-e66e6da33413
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ea66543f-5492-4de3-ae81-d8d456902992 # Icons
            instructions: null
            label: Icon
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a40a1ee5-71db-4c42-9b2d-9dc2238d69f9
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: 12ebd69f-28fa-42bb-ae95-8ff3d3eb5135 # Media
                  operator: empty
                  uid: 113c36b7-658a-43c6-8e87-a6973e0d233a
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: f1cff8b7-1d6e-4cdd-824a-520183822908 # Entries
                  operator: empty
                  uid: 40cfc6bd-cee6-47b9-a819-789a5f2a911d
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: adcea45e-bf40-4faf-b0c8-4ce089696971 # Image
            instructions: null
            label: Images
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df865a53-39c7-4ac5-9a6d-e682498f6139
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: 12ebd69f-28fa-42bb-ae95-8ff3d3eb5135 # Media
                  operator: empty
                  uid: 68e9fb5d-6b17-4254-846c-d01acb5d076a
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: adcea45e-bf40-4faf-b0c8-4ce089696971 # Image
                  operator: empty
                  uid: ca6464a1-28de-430b-908e-eca4f00d876b
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: f1cff8b7-1d6e-4cdd-824a-520183822908 # Entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cbb0c29c-e377-4693-83c8-46f4d61cf8a7
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: f1cff8b7-1d6e-4cdd-824a-520183822908 # Entries
                  operator: empty
                  uid: 890ed55f-29c7-4cbe-ad37-cf9e2e0aeb8e
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: adcea45e-bf40-4faf-b0c8-4ce089696971 # Image
                  operator: empty
                  uid: eea4a766-5482-4e03-bc7a-4c1ddfeb2762
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 12ebd69f-28fa-42bb-ae95-8ff3d3eb5135 # Media
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e5a9e1d-3e5b-4a73-868f-f1d89e42b57c
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: 304b8af6-cde3-4990-9b45-2b5cad40a8bb
        userCondition: null
handle: static
hasTitleField: true
name: Static
section: 2b05c141-a297-4820-ac7d-81e736dbf84b # Collections
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
