fieldLayouts:
  6d89d782-8ec8-449f-9485-0863df883597:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6909f8d4-4f55-4f0b-ba70-f931db078535
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 16ea4eb8-377b-4740-955d-89f60729fce4 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78ca5d7f-a6d5-41ae-8160-8cac7b2bbe92
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e47b95bf-7a74-49e3-afa3-a938bd733ef7 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e834c304-da57-403e-ba6b-09430d71fde6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: adcea45e-bf40-4faf-b0c8-4ce089696971 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e6bae1b-29c8-49d7-9bc8-c805096c0b20
            userCondition: null
            warning: null
            width: 50
        name: Essentials
        uid: 2174b7ee-9151-4332-ad0a-3715fafa203f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            template: _core/craft-ui/instructionsHeader.twig
            type: craft\fieldlayoutelements\Template
            uid: 2e18bf53-bfc2-4f3c-bda8-85afc88c2f66
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e35d6a3-a782-43b2-9eef-24ce9981139c # Header Builder
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1fabf7d-0352-4790-a3a0-c88b486d0373
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _core/craft-ui/instructionsContent.twig
            type: craft\fieldlayoutelements\Template
            uid: e307103c-5702-44df-b0ed-ee0d52bfcd56
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4fe99b5-7832-4eb2-9833-f551177bb821 # Body Builder
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 084983d7-7a3b-4ea9-8952-ebdf3a54951a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _core/craft-ui/matrixConditionalFields.twig
            type: craft\fieldlayoutelements\Template
            uid: 7a6d58b1-2a72-42e4-945a-c9963fc18e5e
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0b3f350c-7d90-4fe9-b1f9-739b0696f280 # Page Extras
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 532d6546-c764-465e-abea-a11971666cba
            userCondition: null
            warning: null
            width: 100
        name: 'Content Layout'
        uid: 09439561-11ba-46e2-a83d-956691d64481
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: decc967b-80dd-4875-ab3f-b6c700b123eb # SEO Settings
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 469504d5-1d4d-4c77-9349-c3db228b3209
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: e4c5d9d5-f1f1-4971-9fe7-8ef51da4bf33
        userCondition: null
handle: topic
hasTitleField: true
name: Public
section: 942cbdfb-d50d-4dcd-9032-4f483562d1dd # Topics & Tags
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
