defaultPlacement: end
enableVersioning: true
handle: news
name: News
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary Content'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  34463b82-dd3f-441c-b9c6-59c351e847aa: # Wireframe Site (En)
    enabledByDefault: true
    hasUrls: true
    template: _sections/news/_entry.twig
    uriFormat: 'news/{slug}'
type: channel
