defaultPlacement: end
enableVersioning: true
handle: topics
name: Topics
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  41b193c3-f554-4c48-8c8a-7ac2645f083f: # Main Site
    enabledByDefault: true
    hasUrls: true
    template: _sections/topics/_entry
    uriFormat: 'topics/{slug}'
type: channel
