field: b09bda91-6d4a-42c4-a824-f3d402ce20e7 # Chunks
fieldLayouts:
  8bdf956f-22c4-496a-9941-c6b7426ef9be:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 68b93e4b-8d64-4598-b7c7-7e34609198b2 # Identifier
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7d5a905-296f-41be-8522-8a08ada18196
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f92a01b3-02b6-427e-9141-3dd789bbef6f # Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43a89a21-6e23-49ac-8412-0a26a4d3c3d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c832b847-2fbc-4a68-ac50-698b165e4fc3 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e31380db-5e73-4fdd-92ae-8d0aa327ad62
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dae834e1-6140-423f-bd63-1f6c477bb162
        userCondition: null
fields:
  68b93e4b-8d64-4598-b7c7-7e34609198b2: # Identifier
    columnSuffix: ajvokjou
    contentColumnType: text
    fieldGroup: null
    handle: identifier
    instructions: null
    name: Identifier
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c832b847-2fbc-4a68-ac50-698b165e4fc3: # Caption
    columnSuffix: sqjwhpfm
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: null
    name: Caption
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: SimpleAir.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  f92a01b3-02b6-427e-9141-3dd789bbef6f: # Code
    columnSuffix: sbypotws
    contentColumnType: text
    fieldGroup: null
    handle: code
    instructions: null
    name: Code
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 10
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: code
name: Code
sortOrder: 2
