field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
fieldLayouts:
  a1f0f4d1-9056-4f56-b262-8722794749a3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ae3f34db-5fe5-4438-86f0-377cfaebf02a # Layout Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33aeadab-024e-46c6-9f23-3bdae21f68da
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c6677eab-6c78-4ca1-93cd-0faa266d1c45 # Text (Intro)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6017252d-7c65-4716-8587-0267805477aa
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a6c56b68-6955-44a2-a86d-198b65955f13 # Image(s)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f595a52-9846-4c22-a6d4-d5436eca92a9
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 5347a201-6da8-47ff-bc5b-20a0dc63d44e # Repeating Content Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4043fe8b-846c-4408-af28-90d689ede417
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7b72b671-dcdc-49b2-95cd-44a8e8be7cad # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9125f69-85d0-464d-a645-9adf0935f0d9
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a1a62d7a-5173-4caf-8d92-423b6dc0dede # Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6cead47-c085-40f3-975f-ce5f00b44f23
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 6272049f-8eaf-4847-a1fc-52a1f881a7a9
        userCondition: null
fields:
  7b72b671-dcdc-49b2-95cd-44a8e8be7cad: # Background
    columnSuffix: ngczrvyg
    contentColumnType: string
    fieldGroup: null
    handle: bg
    instructions: 'Set the background style behind this block.'
    name: Background
    searchable: false
    settings:
      referenceFile: _builders/references/backgrounds.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  5347a201-6da8-47ff-bc5b-20a0dc63d44e: # Repeating Content Items
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: 'Individual content snippets to be arranged based on the layout'
    name: 'Repeating Content Items'
    searchable: true
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 13520478
      columns:
        __assoc__:
          -
            - 1ddd814c-a3f1-4689-bb67-33d04ad8307a # Headline
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 69c2d7dc-3df8-4df1-a444-d2ae376da00c # Text
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - fd647249-c4ea-4ade-99ab-13f9e53bba3f # Image / Icon
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_1_items}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add Content Item'
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  a1a62d7a-5173-4caf-8d92-423b6dc0dede: # Spacing
    columnSuffix: vdailebf
    contentColumnType: string
    fieldGroup: null
    handle: spacing
    instructions: 'Change spacing & dividers above/below this block.'
    name: Spacing
    searchable: false
    settings:
      referenceFile: _builders/references/spacing.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  a6c56b68-6955-44a2-a86d-198b65955f13: # Image(s)
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Image(s)
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
        - json
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: '{{- ( object.owner.variants   ?? null  ) ? "products/#{object.owner.type.handle|lower}/" : '''' -}} {{- ( object.owner.product    ?? null  ) ? "products/#{object.owner.product.type.handle|lower}/" : '''' -}} {{- ( object.owner.section    ?? null  ) ? "#{object.owner.section.handle|lower}/" : '''' -}} {{- ( object.owner.parentUri  ?? null  ) ? "#{object.owner.parentUri|replace(''__'','''')}/" : '''' -}} {{object.owner.slug}}'
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  ae3f34db-5fe5-4438-86f0-377cfaebf02a: # Layout Variant
    columnSuffix: ulxtrpcp
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: 'Change the block layout without changing its underlying content'
    name: 'Layout Variant'
    searchable: false
    settings:
      referenceFile: _builders/references/blockContentRepeater.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  c6677eab-6c78-4ca1-93cd-0faa266d1c45: # Text (Intro)
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: 'Headline / headnote regarding the repeating content items (optional)'
    name: 'Text (Intro)'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: contentRepeater
name: 'Content Repeater'
sortOrder: 4
