field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
fieldLayouts:
  740cffdc-873e-42da-ab3b-9f6a01003077:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dea0077f-b1c4-4d4d-be6c-72ae2f47e105 # Layout Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6608cdda-0c26-4552-8081-38603a7865de
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 20c62722-b003-461f-a9e8-763b2a9cbc21 # How do you want to pick  which entries to embed?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 918a62a4-ab2c-457c-a8af-17d26af6cf87
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b911f8a5-3dbc-4aa9-8be2-9eb2c9c8a2ed # Text (Intro)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8681f02a-2210-4f45-9404-ca6b2379ba31
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a1609989-70ec-42e9-a2d0-ce1a902593c7 # Content Entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33fad8c0-e55c-48fa-a820-4a3b1170da8e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 654452af-16fc-46e0-8dc7-0865935a5d62 # Alternate card
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d19462e3-126a-44aa-8a47-c3866e36dbee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c71f0a73-bd49-42fd-8d60-075e1800d924 # Filter by content type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a639dce8-c509-42c9-bceb-d6b914f14eb3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e29f44d4-5676-46d2-9a24-b7dce4058c40 # Filter by topic(s)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4c8d78c-c856-467b-9881-eb19c01d5072
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 1a73a849-2233-4157-a6bf-b59605d0f83c # Sort order
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9710241a-2726-4fe2-b278-2a92d6a64e90
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 1fcfe5f1-d6bb-41d8-a50a-14c2998b0b66 # Total results to return
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83da7c64-7fbb-4ba4-aac6-30568b3bdd69
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: c0c7cafe-5642-4171-81fa-ef73b6d7a36d # Results per page
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 389e7c7c-63fb-456e-a55a-a1a9d5f63940
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: b114569d-4057-4cc7-acc0-04ff0d55ef41 # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 289f32b0-d40f-4ea6-a183-d04811a7fd19
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ffda0f34-d718-475b-b8ed-99c25f516b8b # Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a4d90e1-ea57-4c18-9a12-137dd2f165d9
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: d1aaa0a6-b73f-406c-bc76-8576bc43d59b
        userCondition: null
fields:
  1a73a849-2233-4157-a6bf-b59605d0f83c: # Sort order
    columnSuffix: ympxzups
    contentColumnType: string
    fieldGroup: null
    handle: order
    instructions: null
    name: 'Sort order'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Most Recent'
            -
              - value
              - mostRecent
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Random
            -
              - value
              - random
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Alphabetical by Title'
            -
              - value
              - alphabeticalByTitle
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  1fcfe5f1-d6bb-41d8-a50a-14c2998b0b66: # Total results to return
    columnSuffix: xctinfgl
    contentColumnType: integer(10)
    fieldGroup: null
    handle: limit
    instructions: 'Limit your search to a specific number of results.'
    name: 'Total results to return'
    searchable: false
    settings:
      decimals: 0
      defaultValue: 3
      max: null
      min: 1
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: 4
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  20c62722-b003-461f-a9e8-763b2a9cbc21: # How do you want to pick  which entries to embed?
    columnSuffix: eqfrdkfb
    contentColumnType: string
    fieldGroup: null
    handle: method
    instructions: null
    name: 'How do you want to pick  which entries to embed?'
    searchable: false
    settings:
      referenceFile: _builders/references/selectionMethod.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  654452af-16fc-46e0-8dc7-0865935a5d62: # Alternate card
    columnSuffix: odhcrdvx
    contentColumnType: string
    fieldGroup: null
    handle: card
    instructions: 'Override the suggested card design for this variant and use this one'
    name: 'Alternate card'
    searchable: false
    settings:
      referenceFile: _builders/references/overrideCards.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  a1609989-70ec-42e9-a2d0-ce1a902593c7: # Content Entries
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: 'Choose the existing content items to embed here.'
    name: 'Content Entries'
    searchable: true
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: 'Add Content'
      showSiteMenu: true
      source: null
      sources:
        - 'section:a52e2b08-2e30-4b00-8784-4104c409d3ed' # FAQs
        - 'section:c2b6d2e5-34ab-410c-8b3b-f752217b7552' # Feedback
        - 'section:3721b4d6-42d5-41fc-b6e7-76204b42c91a' # News
        - 'section:650e7d1d-63e5-42f9-b3ab-4febfb502723' # Pages
        - 'section:942cbdfb-d50d-4dcd-9032-4f483562d1dd' # Topics
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  b911f8a5-3dbc-4aa9-8be2-9eb2c9c8a2ed: # Text (Intro)
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: 'Headline / headnote regarding the content being embedded (optional)'
    name: 'Text (Intro)'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  b114569d-4057-4cc7-acc0-04ff0d55ef41: # Background
    columnSuffix: ccgrpbfv
    contentColumnType: string
    fieldGroup: null
    handle: bg
    instructions: 'Set the background style behind this block.'
    name: Background
    searchable: false
    settings:
      referenceFile: _builders/references/backgrounds.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  c0c7cafe-5642-4171-81fa-ef73b6d7a36d: # Results per page
    columnSuffix: pmubvmbx
    contentColumnType: integer(10)
    fieldGroup: null
    handle: perPage
    instructions: 'Pagination (next/previous links) will appear after this many results (if supported by the layout)'
    name: 'Results per page'
    searchable: false
    settings:
      decimals: 0
      defaultValue: 12
      max: null
      min: -1
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: 4
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  c71f0a73-bd49-42fd-8d60-075e1800d924: # Filter by content type
    columnSuffix: wzxkluqz
    contentColumnType: string
    fieldGroup: null
    handle: contentType
    instructions: 'Results will only include this type of content'
    name: 'Filter by content type'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - FAQs
            -
              - value
              - faqs
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Feedback
            -
              - value
              - feedback
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - News
            -
              - value
              - news
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Pages
            -
              - value
              - pages
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Topics
            -
              - value
              - topics
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  dea0077f-b1c4-4d4d-be6c-72ae2f47e105: # Layout Variant
    columnSuffix: mljzpfmg
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: 'Change the block layout without changing its underlying content'
    name: 'Layout Variant'
    searchable: false
    settings:
      referenceFile: _builders/references/blockEmbeddedEntries.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
  e29f44d4-5676-46d2-9a24-b7dce4058c40: # Filter by topic(s)
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: topics
    instructions: 'Only return records associated with these topics'
    name: 'Filter by topic(s)'
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: false
      source: null
      sources:
        - 'section:942cbdfb-d50d-4dcd-9032-4f483562d1dd' # Topics
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  ffda0f34-d718-475b-b8ed-99c25f516b8b: # Spacing
    columnSuffix: sotrfnux
    contentColumnType: string
    fieldGroup: null
    handle: spacing
    instructions: 'Change spacing & dividers above/below this block.'
    name: Spacing
    searchable: false
    settings:
      referenceFile: _builders/references/spacing.json
    translationKeyFormat: null
    translationMethod: none
    type: simplicateca\referencefield\fields\Dropdown
handle: entries
name: 'Embedded Entries'
sortOrder: 6
