field: 00464ad8-4fb3-4d70-8ad0-202ad79cbc2c # Content Builder - Test
fieldLayouts:
  28250438-d9bd-4b01-9316-6ca8648d5b32:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 29f157fc-9918-4177-bcd3-55c2c5c9a38f # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a7b7ab8-2057-4a87-abf6-7710f61631a5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8217fe05-a738-46ef-940d-19f1348f18d6 # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 185f0b37-ba39-4f30-bc42-6e34e0d95919
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 6cf35dcf-8c52-416d-8ce6-736d91b93f74 # Coverage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c255194-215d-44d5-83d0-f805e0d55a9c
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: a57a80dd-895b-4db9-9fb1-02ecff2a9086 # Choose Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8a7716f-d3ab-461a-b71d-479465f745c5
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: ecc76848-26ca-4eb1-bcdf-621e0e250ad2
        userCondition: null
fields:
  6cf35dcf-8c52-416d-8ce6-736d91b93f74: # Coverage
    columnSuffix: gadmyogw
    contentColumnType: string
    fieldGroup: null
    handle: coverage
    instructions: null
    name: Coverage
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Full Bleed'
            -
              - value
              - fullBleed
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Restrict to Container'
            -
              - value
              - containerOnly
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  29f157fc-9918-4177-bcd3-55c2c5c9a38f: # Text
    columnSuffix: mwjhnlkj
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  8217fe05-a738-46ef-940d-19f1348f18d6: # Background
    columnSuffix: nwdxquxo
    contentColumnType: string
    fieldGroup: null
    handle: background
    instructions: null
    name: Background
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - '- Please Select -'
            -
              - value
              - ''
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Black
            -
              - value
              - black
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - white
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Choose Custom'
            -
              - value
              - chooseCustom
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  a57a80dd-895b-4db9-9fb1-02ecff2a9086: # Choose Color
    columnSuffix: vwpraacs
    contentColumnType: string(7)
    fieldGroup: null
    handle: backgroundColor
    instructions: null
    name: 'Choose Color'
    searchable: false
    settings:
      defaultColor: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
handle: text
name: Text
sortOrder: 1
