columnSuffix: jcmiyhiw
contentColumnType: text
fieldGroup: 481eb25d-9439-4ee3-85c2-e1a0e6d62d11 # Textarea
handle: code
instructions: null
name: Code
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: true
  columnType: null
  initialRows: 10
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
