columnSuffix: null
contentColumnType: string
fieldGroup: ea1a69ed-b5c5-46cf-a629-4435f7f7cad0 # Content Builders
handle: contentBuilderTest
instructions: null
name: 'Content Builder - Test'
searchable: false
settings:
  contentTable: '{{%matrixcontent_contentbuildertest}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
