columnSuffix: null
contentColumnType: string
fieldGroup: e0dac603-c510-4bb5-8701-e25672d93744 # Common
handle: form
instructions: null
name: Form
searchable: false
settings:
  allowSelfRelations: false
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: verbb\formie\fields\Forms
