columnSuffix: rdkrtdam
contentColumnType: string
fieldGroup: 3be366bf-8e5e-4f28-8502-7ebf1d83e26e # Dropdowns
handle: fragmentType
instructions: null
name: 'Fragment Subtype'
searchable: false
settings:
  referenceFile: _sections/fragments/basicFragments.json
translationKeyFormat: null
translationMethod: none
type: simplicateca\referencefield\fields\Dropdown
