columnSuffix: null
contentColumnType: string
fieldGroup: ea1a69ed-b5c5-46cf-a629-4435f7f7cad0 # Content Builders
handle: headerBuilder
instructions: null
name: 'Header Builder'
searchable: true
settings:
  contentTable: '{{%matrixcontent_headerbuilder}}'
  maxBlocks: 1
  minBlocks: 0
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
