columnSuffix: null
contentColumnType: string
fieldGroup: e0dac603-c510-4bb5-8701-e25672d93744 # Common
handle: images
instructions: null
name: 'Lead Image(s)'
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
  defaultUploadLocationSubpath: '{%- set folder = object.folder ??? false -%} {%- if folder %}{{ ( folder == ''Uploads'' ) ? ''asset-meta'' : folder ~ ''/asset-meta'' }}{% endif -%} {%- if not folder -%}     {{- ( object.variants   ?? null  ) ? "products/#{object.type.handle|lower}/" : '''' -}}     {{- ( object.product    ?? null  ) ? "products/#{object.product.type.handle|lower}/" : '''' -}}     {{- ( object.section    ?? null  ) ? "#{object.section.handle|lower}/" : '''' -}}     {{- ( object.parentUri  ?? null  ) ? "#{object.parentUri|replace(''__'','''')}/" : '''' -}}     {{object.slug}} {%- endif -%}'
  localizeRelations: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: 'Choose image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources:
    - 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
