columnSuffix: hjoahmzs
contentColumnType: string
fieldGroup: b7f29b8a-788f-4f46-a93e-cdfdfa91d44b # Buttons & Links
handle: redirect
instructions: null
name: Redirect
searchable: false
settings:
  allowCustomText: false
  allowTarget: false
  autoNoReferrer: false
  customTextMaxLength: 0
  customTextRequired: false
  defaultLinkName: entry
  defaultText: ''
  enableAllLinkTypes: false
  enableAriaLabel: false
  enableElementCache: false
  enableTitle: false
  typeSettings:
    asset:
      allowCrossSiteLink: false
      allowCustomQuery: false
      enabled: false
      sources: '*'
    category:
      allowCrossSiteLink: false
      allowCustomQuery: false
      enabled: true
      sources: '*'
    custom:
      allowAliases: false
      disableValidation: false
      enabled: true
    email:
      allowAliases: false
      disableValidation: false
      enabled: false
    entry:
      allowCrossSiteLink: false
      allowCustomQuery: false
      enabled: true
      sources: '*'
    site:
      enabled: true
      sites: '*'
    tel:
      allowAliases: false
      disableValidation: false
      enabled: false
    url:
      allowAliases: false
      disableValidation: false
      enabled: true
    user:
      allowCrossSiteLink: false
      allowCustomQuery: false
      enabled: false
      sources: '*'
translationKeyFormat: null
translationMethod: none
type: lenz\linkfield\fields\LinkField
