columnSuffix: heeoxwfi
contentColumnType: string
fieldGroup: e0dac603-c510-4bb5-8701-e25672d93744 # Common
handle: testVariant
instructions: null
name: 'Test Variant'
searchable: false
settings:
  referenceFile: _components/builders/blocks/_config/backgrounds.json
translationKeyFormat: null
translationMethod: none
type: simplicateca\referencefield\fields\Dropdown
