fieldLayouts:
  0e6296a2-ebef-4158-ba3d-e196af38899e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: 'This is the main page title. It will appear on the page unless you used the header builder.'
            label: 'Page Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7f78bbcb-7f32-477a-ba16-b79baf60d778
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _builders/controlpanel/instructionsHeaderBuilder.twig
            type: craft\fieldlayoutelements\Template
            uid: d766d6d4-3d04-465a-b1ae-88f0c0d02827
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: d05f4009-0b38-4065-a1b1-65221aa65e63 # Header Builder
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 618ae43d-0a54-4835-a637-3662dbf41d4d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _builders/controlpanel/instructionsContentBuilder.twig
            type: craft\fieldlayoutelements\Template
            uid: 31763d74-d9d5-429f-8fe7-1d8ba7d5f229
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ac47f09-ee20-4f31-93a1-d14442cfdd2f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _builders/controlpanel/matrixConditionalFields.twig
            type: craft\fieldlayoutelements\Template
            uid: 0aa7ff39-373d-49b2-bfcb-9b428ba0bf6b
            userCondition: null
            width: 100
        name: 'Layout Designer'
        uid: 818faf38-587a-432a-ae15-0223cdae2343
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            template: _builders/controlpanel/instructionsContentChunks.twig
            type: craft\fieldlayoutelements\Template
            uid: 4f12c4f4-4ab4-461c-9599-72085b9f2332
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: b09bda91-6d4a-42c4-a824-f3d402ce20e7 # Chunks
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee5c96a8-687c-4b14-bfdd-267277d4066e
            userCondition: null
            warning: null
            width: 100
        name: 'Content Chunks'
        uid: 226ff169-2ef9-4c9a-adc7-4ad41fe0047e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: adcea45e-bf40-4faf-b0c8-4ce089696971 # Lead Image(s)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc50be8e-c504-4f3f-aa26-ba68f45b4f80
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b1c52a06-4990-43f5-90d3-898a48789556 # Dek
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7777e9e-253d-42bc-92ba-52af6fb6bf4d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 772247d2-d67e-40f2-a243-6e6eca55c5f5 # Topics
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7e8b1b6-6e23-4309-8750-e27c23cd78af
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c62ec2a4-1966-4b3c-a5d1-b0842235c23e # Fragment(s)
            instructions: null
            label: 'Footer Call to Action'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 454fd9d7-d9b8-459c-a082-b3b3b6886bf0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d79b3073-00bf-430c-95d5-6d03d8303032 # SEO
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a08d1a5-d7f0-4bc8-a76e-bf56684014b6
            userCondition: null
            warning: null
            width: 100
        name: 'Page Settings'
        uid: a533ce47-f77f-4d3b-add6-fa261e2823b1
        userCondition: null
handle: basic
hasTitleField: true
name: 'Standard Page (Single Column)'
section: 650e7d1d-63e5-42f9-b3ab-4febfb502723 # Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
