fieldLayouts:
  240ed303-f7fd-4dc9-bffa-07b489cb529e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: 'Describe this fragment to make it easier for content editors to find in the future.'
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8534454a-8dda-4499-8321-155586e2654c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 36dbc7a6-4add-4410-8718-a9f8d7e2da97 # Fragment Subtype
            instructions: null
            label: 'What kind of fragment do you want to create?'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c84b3440-e6c2-4cba-bb81-14384a2b665e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\TextFieldConditionRule
                  fieldUid: 36dbc7a6-4add-4410-8718-a9f8d7e2da97 # Fragment Subtype
                  operator: '='
                  uid: 91730e32-5222-421b-870a-900f971d595b
                  value: contentBuilder
              elementType: craft\elements\Entry
              fieldContext: global
            template: _builders/controlpanel/instructionsContentBuilder.twig
            type: craft\fieldlayoutelements\Template
            uid: a18c1716-fe54-40b0-82bf-63ecb26a55b6
            userCondition: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\TextFieldConditionRule
                  fieldUid: 36dbc7a6-4add-4410-8718-a9f8d7e2da97 # Fragment Subtype
                  operator: '='
                  uid: 6eb3ad1d-c65d-4fed-b60b-9c16bda02f13
                  value: contentBuilder
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4886831b-bb98-4016-8f27-ae84c1314744
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\TextFieldConditionRule
                  fieldUid: 36dbc7a6-4add-4410-8718-a9f8d7e2da97 # Fragment Subtype
                  operator: '='
                  uid: d82b4ab5-0c90-4ca9-8615-e0cfe205ad9b
                  value: contentBuilder
              elementType: craft\elements\Entry
              fieldContext: global
            template: _builders/controlpanel/matrixConditionalFields.twig
            type: craft\fieldlayoutelements\Template
            uid: b0f2bfcc-aaac-45ff-b420-08fe0a5614b2
            userCondition: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\TextFieldConditionRule
                  fieldUid: 36dbc7a6-4add-4410-8718-a9f8d7e2da97 # Fragment Subtype
                  operator: '='
                  uid: 3058fcda-d3d1-407e-9a46-fd7c40562b0c
                  value: customHTML
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 3def122c-77bc-465f-b54f-4bba4ecfab39 # Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 505f133f-0ebe-4d06-ba5a-0ca53114588f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c51ca2c5-e211-4b0f-aedb-ec23acc395a9
        userCondition: null
handle: basic
hasTitleField: true
name: 'Basic Fragments'
section: 89093e20-515d-4e3c-b4c4-c6733d8ab56f # Fragments
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
