fieldLayouts:
  40684536-4ae6-410b-9ab9-ce1f423c9427:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 47231d35-0018-4377-b46c-ae84f4e46fcc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d05f4009-0b38-4065-a1b1-65221aa65e63 # Header Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77db6e21-1b04-4dc7-b055-8b4e14e30ef3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90dfabd8-446b-40c7-958c-984a9647211d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 201e19ec-430f-436f-bc75-9985641f2352
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: fdb77561-cbd1-4a4e-a2a5-eb559a5361cb # Sitebook
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
