fieldLayouts:
  40684536-4ae6-410b-9ab9-ce1f423c9427:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: 'Page Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 47231d35-0018-4377-b46c-ae84f4e46fcc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _builders/controlpanel/instructionsHeaderBuilder.twig
            type: craft\fieldlayoutelements\Template
            uid: ea61fb96-468b-4427-a0b4-a1b5dbb29752
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: d05f4009-0b38-4065-a1b1-65221aa65e63 # Header Builder
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77db6e21-1b04-4dc7-b055-8b4e14e30ef3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _builders/controlpanel/instructionsContentBuilder.twig
            type: craft\fieldlayoutelements\Template
            uid: 0a342393-374b-4c57-8dcc-e08a394b84fd
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90dfabd8-446b-40c7-958c-984a9647211d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _builders/controlpanel/matrixConditionalFields.twig
            type: craft\fieldlayoutelements\Template
            uid: e8450ae2-36ee-4f3b-837c-dd11c1cf4538
            userCondition: null
            width: 100
        name: Content
        uid: 201e19ec-430f-436f-bc75-9985641f2352
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            template: _builders/controlpanel/instructionsContentChunks.twig
            type: craft\fieldlayoutelements\Template
            uid: abe45b6a-3af5-405c-84e0-b9c8c640e611
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: b09bda91-6d4a-42c4-a824-f3d402ce20e7 # Chunks
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e2b9296-5d6e-40a4-af59-8da58b4bf78d
            userCondition: null
            warning: null
            width: 100
        name: 'Content Chunks'
        uid: 5dd83726-a9d9-4dd3-837a-50c8a37bab20
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: adcea45e-bf40-4faf-b0c8-4ce089696971 # Lead Image(s)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2afd6a8-b5fe-4b5f-8d55-af5c501dcb75
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b1c52a06-4990-43f5-90d3-898a48789556 # Dek
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 373a4f64-b4a5-40fc-a09d-030d18293177
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 772247d2-d67e-40f2-a243-6e6eca55c5f5 # Topics
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4125718-7942-4545-8e0a-edb64323c89a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c62ec2a4-1966-4b3c-a5d1-b0842235c23e # Fragment(s)
            instructions: null
            label: 'Footer Fragment(s)'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ba2254d-ab6e-4818-a0bd-39f8002ea1e1
            userCondition: null
            warning: null
            width: 100
        name: 'Page Settings'
        uid: 2b82df5f-5521-4d7c-b079-1432a96c9a75
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: fdb77561-cbd1-4a4e-a2a5-eb559a5361cb # Sitebook
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
