fieldLayouts:
  3dfd712d-559c-4099-9f96-58d7e591e5ff:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 66b19dcc-3c7c-4183-8914-5ef4a921400e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e47b95bf-7a74-49e3-afa3-a938bd733ef7 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9d7920c-442b-4c16-b2ce-278e11fcf660
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: adcea45e-bf40-4faf-b0c8-4ce089696971 # Lead Image(s)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 145d2c09-1779-4d8e-947b-a356e58145d3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 16ea4eb8-377b-4740-955d-89f60729fce4 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0760926f-dbcc-4b22-bec6-1ef130871e47
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7d435989-cada-4c87-929c-cb36c4aa1be6
        userCondition: null
handle: private
hasTitleField: true
name: Private
section: 942cbdfb-d50d-4dcd-9032-4f483562d1dd # Topics
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
