fieldLayouts:
  b31791aa-909d-43be-a352-7970cd695247:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: 'This is the main page title. It will appear on the page unless you used the header builder.'
            label: 'Page Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3f9ed9b7-3cde-4499-a7a2-396bf7a3d33b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _builders/controlpanel/instructionsHeaderBuilder.twig
            type: craft\fieldlayoutelements\Template
            uid: 706c3a05-0cce-4331-8d53-2c66f752969d
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: d05f4009-0b38-4065-a1b1-65221aa65e63 # Header Builder
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: afef7495-b715-4717-900c-146a33e75450
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _builders/controlpanel/instructionsContentBuilder.twig
            type: craft\fieldlayoutelements\Template
            uid: 1e1b2698-ace8-444b-af5d-e333a70dad96
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3013d139-6ccf-4920-8105-9d74fb779d9c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _builders/controlpanel/matrixConditionalFields.twig
            type: craft\fieldlayoutelements\Template
            uid: 1d2d5820-d225-4571-aba5-cb8f0f45d81d
            userCondition: null
            width: 100
        name: Content
        uid: 20e7b132-6229-47bf-8c01-9a2142ccfc2b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            template: _builders/controlpanel/instructionsContentChunks.twig
            type: craft\fieldlayoutelements\Template
            uid: 14196bc8-b742-42da-b42e-d9017bf2f230
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: b09bda91-6d4a-42c4-a824-f3d402ce20e7 # Chunks
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1440ecd-041f-4ef3-9850-009970b29d4a
            userCondition: null
            warning: null
            width: 100
        name: 'Content Chunks'
        uid: 7b8a24fa-23a4-4502-a297-045769f082c9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: adcea45e-bf40-4faf-b0c8-4ce089696971 # Lead Image(s)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da6fc831-aaa6-4d44-a48a-6c7ddd44dbf4
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b1c52a06-4990-43f5-90d3-898a48789556 # Dek
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 179a2beb-2983-434b-b1b1-4f7203ee0206
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 772247d2-d67e-40f2-a243-6e6eca55c5f5 # Topics
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d94261f6-2a33-4d40-9720-6f7d626ce8c0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c62ec2a4-1966-4b3c-a5d1-b0842235c23e # Fragment(s)
            instructions: null
            label: 'Footer Fragment(s)'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64433471-dc20-433c-8c04-22dda5811bc1
            userCondition: null
            warning: null
            width: 100
        name: 'Page Settings'
        uid: 9f8c970f-637c-425e-b58c-19deaf4b7a95
        userCondition: null
handle: standard
hasTitleField: true
name: 'Standard (Single Column)'
section: 8c9174b7-2c31-491e-a3f9-0374374c967c # Landing Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
