fieldLayouts:
  835499c9-bd3e-4b73-9e66-5ffcd238b5f5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f7dd4108-60e1-4b4c-8d46-aadeb2ff0616
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 28519221-5ebd-495b-ba47-aaefcd80444b # Test Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5fcf5fd4-65ee-4654-9bd0-be8577a019b6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 00464ad8-4fb3-4d70-8ad0-202ad79cbc2c # Content Builder - Test
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d137746d-70a8-46c4-b3a5-430a7ebf9fc0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _components/builders/_cp/matrix-conditionals.twig
            type: craft\fieldlayoutelements\Template
            uid: 0e0236ea-5fff-4dd6-9243-9f1b8f943210
            userCondition: null
            width: 100
        name: Content
        uid: 5b9d0e36-b1e2-4834-9364-2f209c966123
        userCondition: null
handle: testing
hasTitleField: true
name: Testing
section: 650e7d1d-63e5-42f9-b3ab-4febfb502723 # Pages
sortOrder: 6
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
