fieldLayouts:
  533207f0-30a6-4dc9-a13c-4b33b38129de:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 23f2001a-68d1-4e13-8fad-0f5adf268f68
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e47b95bf-7a74-49e3-afa3-a938bd733ef7 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7629e19e-a60e-4c70-b2ac-8323dbf07065
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8aae87ed-a55c-4e81-9745-e112fdc10a29
        userCondition: null
handle: userComment
hasTitleField: true
name: 'User Comment'
section: c2b6d2e5-34ab-410c-8b3b-f752217b7552 # Feedback
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
