fieldLayouts:
  92968e3b-3bc8-44a7-a6bf-0b8234588bc2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            template: _site/sitehub/craft-ui/instructionsContentBit.twig
            type: craft\fieldlayoutelements\Template
            uid: 11a7f554-79a5-4d2e-a14b-dd6e844e1158
            userCondition: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9a6530ae-47fb-4e7c-9a2c-1fad6c35b3ec
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: c70698c5-9843-4d1a-9ce8-2e2e272bd096 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3ffdcf4-9a28-4ea1-81ba-01ddcca9cb72
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 772247d2-d67e-40f2-a243-6e6eca55c5f5 # Topic/Theme/Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e250f0af-7a41-46d6-b80d-0f33b1f4d0cb
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 6a1ab78a-ce1d-4e06-944f-7fa172aaa06a # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e1ea165-7c70-4003-abc3-e1869ab8c6ed
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: adcea45e-bf40-4faf-b0c8-4ce089696971 # Image
            instructions: null
            label: 'Image / Icon'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86a3d5f3-9a1f-4e2b-bc57-1e8b6d90ec77
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 42fe2ad8-4ccf-4961-b0d0-3ef034e0a6bf
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Allows a Reusable Bit to be queried from Twig without referencing Slug or ID. Only Admins can modify a Preset ID. Use Protected Elements Global to prevent accidental deletion.'
            type: craft\fieldlayoutelements\Tip
            uid: 8343e280-4670-4cff-a6a2-ad67c46b2f71
            userCondition: null
          -
            elementCondition: null
            fieldUid: 6788be2a-03be-4a82-8c88-9e8a1af1acf4 # Preset
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0eff91b3-ec01-4548-8e2c-c7d8d8236dfc
            userCondition: null
            warning: null
            width: 25
        name: 'Preset ID'
        uid: 7a20d8b6-d0f4-4831-a62d-47c803c5ee22
        userCondition:
          class: craft\elements\conditions\users\UserCondition
          conditionRules:
            -
              class: craft\elements\conditions\users\AdminConditionRule
              uid: 06ca4522-2f3d-43a2-a371-94bf57f9b22f
              value: true
          elementType: craft\elements\User
          fieldContext: global
handle: bit
hasTitleField: true
name: 'Reusable Bits'
section: a52e2b08-2e30-4b00-8784-4104c409d3ed # Modular Content
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
